### ISSUE TITLE
Error on Participate Change events

### ISSUE THREAD

**Issue by tcortega** [open-wa/wa-automate-nodejs#1045]
**Describe the bug**
It happens on participate change events

**Steps to Reproduce**
Randomly

**create() code**
This is the code you use to create the client. e.g
```javascript
create({
        licenseKey: 'XXXXXXXXXXXXXXXXXXXXXXXX',
        headless: headless,
        qrRefreshS: 20,
        qrTimeout: 0,
        authTimeout: 0,
        autoRefresh: true,
        restartOnCrash: start,
        cacheEnabled: false,
        logConsole: true,
        useChrome: true,
        killProcessOnBrowserClose: true,
        throwErrorOnTosBlock: false
    }).then((client) => start(client))
    .catch((err) => new Error(err))
```

**Expected behavior**
A error should pop-up in console.
```
Error: Evaluation failed: TypeError: t.split is not a function
    at t.value (https://web.whatsapp.com/app.4666d10327cd1dac6da3.js:1:436000)
    at t.value (https://web.whatsapp.com/app.4666d10327cd1dac6da3.js:1:434157)
    at C:\Users\tcortega\Desktop\Developing\JS\whatsapp-bot-pronto\node_modules\@open-wa\wa-automate\dist\lib\wapi.js:1278:49
    at Array.map (<anonymous>)
    at t.cb (C:\Users\tcortega\Desktop\Developing\JS\whatsapp-bot-pronto\node_modules\@open-wa\wa-automate\dist\lib\wapi.js:1276:19)
    at t.value (https://web.whatsapp.com/app.4666d10327cd1dac6da3.js:1:436544)
    at t.value (https://web.whatsapp.com/app.4666d10327cd1dac6da3.js:1:434874)
    at t.value (https://web.whatsapp.com/app.4666d10327cd1dac6da3.js:1:1042968)
    at t.value [as _triggerEvents] (https://web.whatsapp.com/app.4666d10327cd1dac6da3.js:1:436544)
    at t.value [as trigger] (https://web.whatsapp.com/app.4666d10327cd1dac6da3.js:1:434874)
    at ExecutionContext._evaluateInternal (C:\Users\tcortega\Desktop\Developing\JS\whatsapp-bot-pronto\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (C:\Users\tcortega\Desktop\Developing\JS\whatsapp-bot-pronto\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
```

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: '2.2045.15',
  PAGE_UA: 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36',
  WA_AUTOMATE_VERSION: '3.0.13',
  BROWSER_VERSION: 'HeadlessChrome/86.0.4240.183'
}
```

**Screenshots**
No need

**Host (please complete the following information):**
 - OS: Windows 10 v2004

**Additional context**
No additional context

**Comment by smashah** [comment]
@tcortega I've submitted a patch which should stop this from happening. Please try it out and report back if this issue is resolved.

**Comment by joedutra** [comment]
<img src="https://media.giphy.com/media/sNZddQMtrqpS0HEEMC/giphy.gif"></img>
Man, you know it sucks, how we copy your repo, if we have functions that you don’t even have, all for free, we perform almost every day, I came from Sulla and you too, but if you look at following the week, we redid it all lib again, now you will no longer be able to copy us, you copy and keep saying that we copy, nor compete with you ours and for free and your payment

**Comment by joedutra** [comment]
I come to apologize and say that we have nothing against this, only that they accuse us of copying and we never copied anything, if someone copied it was when someone changed our lib, I apologize and the intention was not to be slandered anymore of copying something we worked on every day. just like you, we will not do that anymore.
