### ISSUE TITLE
not sending video, audio, doc or image after 3.0.11 >

### ISSUE THREAD

**Issue by danielct59** [open-wa/wa-automate-nodejs#1059]
my code is simple when it comes to sending video, audio, doc or image messages .......

the problem started in version 3.0.11 my BOT when receiving the first message it responds with an image and a welcome text ............. it was normal until u could no longer scan the QrCode, then I needed to update, so it was like this

**Describe the bug**
✓ Authenticated
✓ WAPI Reinjected
✓ Client is ready
✓ Patches Installed
✓ Client loaded in 9.4s
✓ 🚀 @OPEN-WA ready for account: 7950

(node:4418) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'author' of undefined
    at Object.window.<computed>.<computed> [as sendImage] (__puppeteer_evaluation_script__:1:75876)
    at __puppeteer_evaluation_script__:3:45
    at ExecutionContext._evaluateInternal (/var/www/bot/admin/node_modules/puppeteer/lib/ExecutionContext.js:102:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at ExecutionContext.evaluate (/var/www/bot/admin/node_modules/puppeteer/lib/ExecutionContext.js:33:16)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/var/www/bot/admin/node_modules/puppeteer/lib/helper.js:94:19)
    at DOMWorld.evaluate (/var/www/bot/admin/node_modules/puppeteer/lib/DOMWorld.js:89:24)
  -- ASYNC --
    at Frame.<anonymous> (/var/www/bot/admin/node_modules/puppeteer/lib/helper.js:94:19)
    at Page.evaluate (/var/www/bot/admin/node_modules/puppeteer/lib/Page.js:612:14)
    at Page.<anonymous> (/var/www/bot/admin/node_modules/puppeteer/lib/helper.js:95:27)
    at Client.<anonymous> (/var/www/bot/admin/node_modules/@open-wa/wa-automate/dist/api/Client.js:381:67)
    at step (/var/www/bot/admin/node_modules/@open-wa/wa-automate/dist/api/Client.js:63:23)
    at Object.next (/var/www/bot/admin/node_modules/@open-wa/wa-automate/dist/api/Client.js:44:53)
    at /var/www/bot/admin/node_modules/@open-wa/wa-automate/dist/api/Client.js:38:71
    at new Promise (<anonymous>)
    at __awaiter (/var/www/bot/admin/node_modules/@open-wa/wa-automate/dist/api/Client.js:34:12)
    at Client.pup (/var/www/bot/admin/node_modules/@open-wa/wa-automate/dist/api/Client.js:366:16)
  -- ASYNC --
    at Page.<anonymous> (/var/www/bot/admin/node_modules/puppeteer/lib/helper.js:94:19)
    at Client.<anonymous> (/var/www/bot/admin/node_modules/@open-wa/wa-automate/dist/api/Client.js:381:67)
    at step (/var/www/bot/admin/node_modules/@open-wa/wa-automate/dist/api/Client.js:63:23)
    at Object.next (/var/www/bot/admin/node_modules/@open-wa/wa-automate/dist/api/Client.js:44:53)
    at /var/www/bot/admin/node_modules/@open-wa/wa-automate/dist/api/Client.js:38:71
    at new Promise (<anonymous>)
    at __awaiter (/var/www/bot/admin/node_modules/@open-wa/wa-automate/dist/api/Client.js:34:12)
    at Client.pup (/var/www/bot/admin/node_modules/@open-wa/wa-automate/dist/api/Client.js:366:16)
    at Client.<anonymous> (/var/www/bot/admin/node_modules/@open-wa/wa-automate/dist/api/Client.js:908:41)
    at step (/var/www/bot/admin/node_modules/@open-wa/wa-automate/dist/api/Client.js:63:23)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4418) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4418) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by smashah** [comment]
please update to the latest version (v3.0.14)

Also, I already mentioned in the other issue, please fill in the issue template. Your issues will be automatically ignored if they don't follow the issue template or are missing important context.

**Comment by smashah** [comment]
@danielct59 looks like the `quotedMsgId` is pointing to a message that does not exist.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️
