### ISSUE TITLE
function kill() throw exception

### ISSUE THREAD

**Issue by mmuniz75** [open-wa/wa-automate-nodejs#1063]
After move to version 3.0.15, when try execute kill(), got :
Shutting Down
needsToScan -> error Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at C:\Pessoal\projects\digital_marketing\codigo\api-whatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:208:63
    at new Promise (<anonymous>)
    at CDPSession.send (C:\Pessoal\projects\digital_marketing\codigo\api-whatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:207:16)
    at ExecutionContext._evaluateInternal (C:\Pessoal\projects\digital_marketing\codigo\api-whatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:200:50)
    at ExecutionContext.evaluateHandle (C:\Pessoal\projects\digital_marketing\codigo\api-whatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:151:21)
    at WaitTask.rerun (C:\Pessoal\projects\digital_marketing\codigo\api-whatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:498:71)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by smashah** [comment]
This error is fired from a leaked promise from authentication. Why this promise is leaking is unknown and I'm unable to replicate it based on the demo and you've provided no replication instructions. Please fill the issue template or just ignore this error.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️
