### ISSUE TITLE
Error send image from amazon s3

### ISSUE THREAD

**Issue by maurihn** [open-wa/wa-automate-nodejs#1074]
I try to send the image https://shimli-assets.s3-us-west-2.amazonaws.com/campaing/1604435048463.png which is public and it sends me a 400 error

Only with the images of the s3 bucket does that happen, please your help.

Before the last updates I was sending them well

TCL: getDUrl -> error Error: Request failed with status code 400
    at createError (/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/node_modules/axios/lib/adapters/http.js:244:11)

Something went wrong TypeError: Cannot read property 'match' of undefined
    at isDataURL (/node_modules/@open-wa/wa-automate/dist/api/Client.js:96:235)
    at Client.<anonymous> (/node_modules/@open-wa/wa-automate/dist/api/Client.js:889:31)
    at step (/node_modules/@open-wa/wa-automate/dist/api/Client.js:63:23)
    at Object.next (/node_modules/@open-wa/wa-automate/dist/api/Client.js:44:53)
    at /node_modules/@open-wa/wa-automate/dist/api/Client.js:38:71
    at new Promise (<anonymous>)
    at __awaiter (/node_modules/@open-wa/wa-automate/dist/api/Client.js:34:12)
    at Client.sendImage (/node_modules/@open-wa/wa-automate/dist/api/Client.js:884:16)
    at Client.<anonymous> (/node_modules/@open-wa/wa-automate/dist/api/Client.js:964:33)
    at step (/node_modules/@open-wa/wa-automate/dist/api/Client.js:63:23)

**Comment by smashah** [comment]
@maurihn the 400 error is from the s3 bucket, not really anything to do with the library. The code for getting the data URL from a URL has not changed recently. I've tried your link and it seems to be working fine. You may want to double-check the s3 bucket settings or serve your content from a 3rd party CDN? Maybe there are some origin restrictions?

**Comment by maurihn** [comment]
I was reviewing and I noticed that from version 3.0.6 (where everything works fine for me) to version 3.0.16 there is an update of the axios from 0.20 to 0.21 and that is where the problem occurs, I do not know if the problem is there, but the latest version of 3.0.16 does not work for me :(

**Comment by smashah** [comment]
Does 3.0.15 work?

**Comment by maurihn** [comment]
Throws the same error

**Comment by smashah** [comment]
@maurihn I suggest testing each version of the library until you find the exact version at which is stopped working so a fix can be identified.

**Comment by smashah** [comment]
@maurihn Did you find the specific version causing the issue?

**Comment by smashah** [comment]
Closing due to inactivity. Let me know if this is still happening.
