### ISSUE TITLE
crashes 30 seconds after starting

### ISSUE THREAD

**Issue by klokwert** [open-wa/wa-automate-nodejs#1297]
First it worked fine, Idk what's wrong now, but everytime i try to start, it stops after 30 seconds with this message:

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                                                                   ┃
┃   @open-wa/wa-automate                                                                            ┃
┃    💬 🤖 The most reliable NodeJS whatsapp library for chatbots with advanced features.           ┃
┃   Version: 3.2.5                                                                                  ┃
┃   Check out the latest changes: https://github.com/open-wa/wa-automate-nodejs#latest-changes      ┃
┃                                                                                                   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
You can also authenticate the session at: http://localhost:7000
- Initializing WA
- Browser Launched
TimeoutError: waiting for function failed: timeout 30000ms exceeded
    at new WaitTask (/home/micha/whatsapp/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:505:34)
    at DOMWorld.waitForFunction (/home/micha/whatsapp/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:460:26)
    at Frame.waitForFunction (/home/micha/whatsapp/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:910:32)
    at Page.waitForFunction (/home/micha/whatsapp/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1291:33)
    at Object.<anonymous> (/home/micha/whatsapp/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:209:39)
    at step (/home/micha/whatsapp/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:63:23)
    at Object.next (/home/micha/whatsapp/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:44:53)
    at fulfilled (/home/micha/whatsapp/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:35:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by smashah** [comment]
@klokwert please in the future use the issue template. This timeout relates to the web page not being loaded due to a bad connection or some other problem. You need to run this in `--headful` or `headless:false` and see what's going on in the browser.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️

**Comment by klokwert** [comment]
idk what was wrong, but when i did:
 rm ~/.npm -rf
 rm node_modules -rf

and then reinstalled everything, it did work again

**Comment by smashah** [comment]
@klokwert yeah most times this happens a simple restart fixes the issue. It can be due to a million things, none of which are related to the library. thanks
