### ISSUE TITLE
Getting this error when deploying to heroku

### ISSUE THREAD

**Issue by salman0ansari** [open-wa/wa-automate-nodejs#1333]
**Describe the bug**
When deploying project to heroku getting error

**Steps to Reproduce**
1. node master.js

**create() code**
This is the code you use to create the client. e.g
```
wa.create().then(client => start(client));
function start(client) {
    client.onMessage(async message => {
```

**Expected behavior**
project should be run

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
(node:76) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/app/node_modules/puppeteer/.local-chromium/linux-848005/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (events.js:327:22)
    at Interface.close (readline.js:424:8)
    at Socket.onend (readline.js:202:10)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:76) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:76) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS: [e.g. iOS]

**Additional context**
Add any other context about the problem here.

**Comment by smashah** [comment]
Make sure you're using the correct buildpacks

      https://github.com/open-wa/wa-automate-nodejs/blob/34473412d61f8e07ad3c5afb4f6c4751436adb0a/app.json#L14

**Comment by salman0ansari** [comment]
> Make sure you're using the correct buildpacks
> 
> https://github.com/open-wa/wa-automate-nodejs/blob/34473412d61f8e07ad3c5afb4f6c4751436adb0a/app.json#L14

Even with correct buildpacks still same issue

**Comment by smashah** [comment]
@salman0ansari with that builpack you have to set `useChrome: true` in your config

**Comment by apexcodexd** [comment]
> @salman0ansari with that builpack you have to set `useChrome: true` in your config

Hello i have same error how can i fix pls help

**Comment by apexcodexd** [comment]
> @salman0ansari with that builpack you have to set `useChrome: true` in your config

Where should i add usechrome true?

**Comment by apexcodexd** [comment]
> @salman0ansari with that builpack you have to set `useChrome: true` in your config

How do i fix it please help i have same error @salman0ansari  help pls @smashah

**Comment by smashah** [comment]
@apexcodexd put it in your create config
