### ISSUE TITLE
Error: Evaluation failed: z when I try use the method addParticipant

### ISSUE THREAD

**Issue by rheimon1** [open-wa/wa-automate-nodejs#1344]
I am experiencing a problem when trying to use the addParticipant method which is as follows: 
Error: Evaluation failed: z
 at ExecutionContext._evaluateInternal (/home/.../..../node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/home/.../.../node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)

**Comment by smashah** [comment]
Yo be honest you should count your blessings that this is not working right now. 

I'll look into fixing this but in the meantime I suggest using this instead

https://docs.openwa.dev/classes/client.html#getgroupinvitelink

**Comment by smashah** [comment]
@rheimon1 is this still happening?

**Comment by rheimon1** [comment]
> @rheimon1 is this still happening?

Not always... But it still occurs in some cases. Do you think it has anything to do with me if I try to add a number to a group that's not my contact?
