### ISSUE TITLE
Error on decryptMedia when reading stickers

### ISSUE THREAD

**Issue by rickricardo** [open-wa/wa-automate-nodejs#1419]
With specific stickers, which I couldn't identify a pattern, decryptMedia function returns an error.
Before the metadata update I never had this error.

**Code**
if( message.type==='sticker') {
    let stickerDecryptable = await client.getStickerDecryptable(message.id);
    mediaData = await decryptMedia(stickerDecryptable, uaOverride);   _//line 232_
}

**Error**
TCL: start -> error Error: message is missing critical data needed to download the file.
    at /Users/path/wa-automate-nodejs/node_modules/@open-wa/wa-decrypt/dist/decrypt.js:85:27
    at step (/Users/path/wa-automate-nodejs/node_modules/@open-wa/wa-decrypt/dist/decrypt.js:44:23)
    at Object.next (/Users/path/wa-automate-nodejs/node_modules/@open-wa/wa-decrypt/dist/decrypt.js:25:53)
    at /Users/path/wa-automate-nodejs/node_modules/@open-wa/wa-decrypt/dist/decrypt.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/path/wa-automate-nodejs/node_modules/@open-wa/wa-decrypt/dist/decrypt.js:15:12)
    at Object.decryptMedia (/Users/path/wa-automate-nodejs/node_modules/@open-wa/wa-decrypt/dist/decrypt.js:77:67)
    at /path/wa-automate-nodejs/WA_ZapFig/ZapALL.ts:232:43
    at step (/Users/path/wa-automate-nodejs/WA_ZapFig/ZapALL.ts:33:23)
    at Object.next (/Users/path/wa-automate-nodejs/WA_ZapFig/ZapALL.ts:14:53)

**Comment by smashah** [comment]
@rickricardo please try again and if this keeps happening then update @open-wa/wa-decrypt dependency

```bash
> npm i @open-wa/wa-decrypt@latest
```

Let me know if this is still happening. Thanks

P.S this method is an insider's feature
https://docs.openwa.dev/classes/client.html#getstickerdecryptable

**Comment by smashah** [comment]
The above info should resolve this issue, if not, feel free to bump the issue.

Closing for now.


thanks
