### ISSUE TITLE
Cannot create property 'skipBrokenMethodsCheck' on string 'Imperial'

### ISSUE THREAD

**Issue by Kanuility** [open-wa/wa-automate-nodejs#1456]
**Describe the bug**
TypeError: Cannot create property 'skipBrokenMethodsCheck' on string 'Imperial'
    at C:\Users\dinok\OneDrive\Desktop\ffe\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:386:55
    at step (C:\Users\dinok\OneDrive\Desktop\ffe\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:63:23)
    at Object.next (C:\Users\dinok\OneDrive\Desktop\ffe\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:44:53)
    at fulfilled (C:\Users\dinok\OneDrive\Desktop\ffe\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:35:58)

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. update to the newest version
2. open visual studio code 
3. open a terminal
4. npm start
5. scan QR and see an error

**create() code**
This is the code you use to create the client. e.g
```javascript
const startServer = async() => {
  create('Imperial', serverOption)
      .then((client) => {
        global.sclient = client
        global.sendingAnimatedSticker = []
        global.queueAnimatedSticker = []
        global.amdownloaden = []
        global.queuemp3 = []
        global.queuemp4 = []
          console.log('[DEV] Dominik Heiing')
          console.log('[SERVER] Server Started!')
              // Force it to keep the current session
          client.onStateChanged((state) => {
                  console.log('[Client State]', state)
                  if (state === 'CONFLICT') client.forceRefocus()
              })
              // listening on message
          client.onMessage((message) => {
              msgHandler(client, message)
          })

          client.onGlobalParicipantsChanged((event) => {
              welcomes.welcome(client, event, db)
          })

          client.onAddedToGroup((chat) => {
            let totalMem = chat.groupMetadata.participants.length
            if (totalMem < 50) { 
            	client.sendText(chat.id, `This group only has ${totalMem} members, Its needs atleast 50 members to activate the services`).then(() => client.leaveGroup(chat.id))
            	client.deleteChat(chat.id)
            } else {
              client.sendFileFromUrl(chat.groupMetadata.id, 'https://images.alphacoders.com/100/1008637.jpg', 'welcome.png', `Hi everyone, Thanks for adding me to the group! Use '&help' to see the usable commands`)
            }
              
          })
          client.onIncomingCall((call) => {
            client.sendText(call.peerJid, 'You are banned for calling, Join our support group to get unbanned')
            client.contactBlock(call.peerJid)
            moderation.callban(call.peerJid, db, time)
            client.deleteChat(call.peerJid)
        })

      })
      .catch((err) => {
          console.error(err)
      })
}
```

**Expected behaviour**
Bot starts normally

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
√ Browser Launched
┌─────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│       (index)       │                                                                    Values                                                                    │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│     WA_VERSION      │                                                                  '2.2106.5'                                                                  │
│       PAGE_UA       │ 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                   '3.9.0'                                                                    │
│   BROWSER_VERSION   │                                                         'HeadlessChrome/90.0.4427.0'                                                         │
│         OS          │                                                                 'Windows 10'                                                                 │
│      START_TS       │                                                                1615221292529                                                                 │
└─────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
√ Authenticated
√ WAPI Reinjected
√ Client is ready
TypeError: Cannot create property 'skipBrokenMethodsCheck' on string 'Imperial'
    at C:\Users\dinok\OneDrive\Desktop\ffe\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:386:55
    at step (C:\Users\dinok\OneDrive\Desktop\ffe\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:63:23)
    at Object.next (C:\Users\dinok\OneDrive\Desktop\ffe\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:44:53)
    at fulfilled (C:\Users\dinok\OneDrive\Desktop\ffe\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:35:58)
PS C:\Users\dinok\OneDrive\Desktop\ffe>
}
```

**Comment by smashah** [comment]
@Kanuility Looks like you have some upgrading to do. 

In newer versions of the library, you can no longer set the first param in `create` as the `sessionId`, it has to be in the config object itself.

Please see: https://github.com/YogaSakti/imageToSticker/blob/2462288f3b24db368d235c874a14da5e4c228a33/index.js#L71

Also, for small things like this I would suggest using the discord (click the discord badge in the readme) instead, there are people there that can help out with these types of problems.

Thanks
