### ISSUE TITLE
Error in scan a new QR

### ISSUE THREAD

**Issue by chgss** [open-wa/wa-automate-nodejs#1496]
I got this error when I try to scan new QR in a new account

`Error Evaluation failed: TypeError: Cannot read property 'user' of undefined
    at window.o (__puppeteer_evaluation_script__:1:264130)
    at __puppeteer_evaluation_script__:1:8 Error: Evaluation failed: TypeError: Cannot read property 'user' of undefined
    at window.o (__puppeteer_evaluation_script__:1:264130)
    at __puppeteer_evaluation_script__:1:8
    at ExecutionContext._evaluateInternal (/root/npm/node_modules/puppeteer/src/common/ExecutionContext.ts:219:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at ExecutionContext.evaluate (/root/npm/node_modules/puppeteer/src/common/ExecutionContext.ts:138:12)`

![image](https://user-images.githubusercontent.com/17861702/111713955-98453180-881e-11eb-99b8-3d280dbc7a1f.png)

![image](https://user-images.githubusercontent.com/17861702/111714018-b9a61d80-881e-11eb-8b60-eceb937b22cc.png)

**Comment by smashah** [comment]
@chgss does this happen every time?

**Comment by chgss** [comment]
I tried to scan the code for the first time I got the error message and the program closed, then I tried again by starting the program and it logged in with no issues without scan QR again.

I have not tried to scan the code with another account.

**Comment by smashah** [comment]
@chgss this should not happen again after the latest patches.

Thanks
