### ISSUE TITLE
Error on SimpleListener when invoke demo ts-node server.ts

### ISSUE THREAD

**Issue by ratno** [open-wa/wa-automate-nodejs#1554]
using the latest release v3.10.7 demo
ts-node server.ts

/usr/local/share/.config/yarn/global/node_modules/ts-node/src/index.ts:434
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
server.ts:9:26 - error TS2305: Module '"../src/index"' has no exported member 'SimpleListener'.

9 import { create, Client, SimpleListener } from '../src/index';
                           ~~~~~~~~~~~~~~
server.ts:22:95 - error TS2345: Argument of type '"PASTE_WEBHOOK_DOT_SITE_UNIQUE_URL_HERE"' is not assignable to parameter of type 'SimpleListener[] | "all"'.

22     Object.keys(SimpleListener).map(eventKey=>client.registerWebhook(SimpleListener[eventKey],WEBHOOK_ADDRESS))
                                                                                                 ~~~~~~~~~~~~~~~

    at createTSError (/usr/local/share/.config/yarn/global/node_modules/ts-node/src/index.ts:434:12)
    at reportTSError (/usr/local/share/.config/yarn/global/node_modules/ts-node/src/index.ts:438:19)
    at getOutput (/usr/local/share/.config/yarn/global/node_modules/ts-node/src/index.ts:578:36)
    at Object.compile (/usr/local/share/.config/yarn/global/node_modules/ts-node/src/index.ts:775:32)
    at Module.m._compile (/usr/local/share/.config/yarn/global/node_modules/ts-node/src/index.ts:858:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/share/.config/yarn/global/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)

**Comment by smashah** [comment]
![image](https://user-images.githubusercontent.com/5903821/113517689-72878e80-9579-11eb-9354-8fa70171a52b.png)
