### ISSUE TITLE
error when using --api-host

### ISSUE THREAD

**Issue by hafriz** [open-wa/wa-automate-nodejs#1670]
hi, there is error when i'm using --api-host 'https://subdomain.domain.com' 

Generating Swagger Spec
Error parseUrl is not a function TypeError: parseUrl is not a function
    at /home/pi/wa-automate-docker/node_modules/@open-wa/wa-automate/dist/build/build-postman.js:193:58
    at Array.map (<anonymous>)
    at /home/pi/wa-automate-docker/node_modules/@open-wa/wa-automate/dist/build/build-postman.js:162:28
    at step (/home/pi/wa-automate-docker/node_modules/@open-wa/wa-automate/dist/build/build-postman.js:63:23)
    at Object.next (/home/pi/wa-automate-docker/node_modules/@open-wa/wa-automate/dist/build/build-postman.js:44:53)
    at fulfilled (/home/pi/wa-automate-docker/node_modules/@open-wa/wa-automate/dist/build/build-postman.js:35:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by smashah** [comment]
This should be fixed in the latest Release [3.14.0](https://github.com/open-wa/wa-automate-nodejs/compare/3.13.2...3.14.0) (2021-05-16)

The docker image is automatically built upon a new version of the library so let me know how it's working if you decide to try it again. thanks
