### ISSUE TITLE
I can't start the bot

### ISSUE THREAD

**Issue by x000x000x000x** [open-wa/wa-automate-nodejs#1687]
Can you help me with this?

Starting
- Version: 3.15.1
- Initializing WA
- Launching Browser
- Setting Up Browser
- Loading session data
- Found session data file: /home/angelo/Downloads/iris/Iris.data.json
- Existing session data detected. Injecting...
- Existing session data injected
- Navigating to WA
- Navigating to WA
TypeError: Cannot read property 'status' of null
    at Object.<anonymous> (/home/angelo/Downloads/iris/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:138:133)
    at Generator.next (<anonymous>)
    at fulfilled (/home/angelo/Downloads/iris/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by smashah** [comment]
this was fixed in 3.15.2
