### ISSUE TITLE
getGroupInviteLink stop works in version 3.16

### ISSUE THREAD

**Issue by mmuniz75** [open-wa/wa-automate-nodejs#1699]
When try get response from getGroupInviteLink() , throws : 

(node:8264) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Error: GROUP_JID: invalid jid type: Not an instance of WID
    at t.GROUP_JID (https://web.whatsapp.com/bootstrap_qr.3ee97e011a14353fd537.js:1:551992)
    at Object.t.queryGroupInviteCode (https://web.whatsapp.com/bootstrap_main.61ccbd302106e7080867.js:2:23304)
    at Object.window.<computed>.<computed> [as getGroupInviteLink] (__puppeteer_evaluation_script__:1:339892)
    at __puppeteer_evaluation_script__:1:17
    at ExecutionContext._evaluateInternal (C:\Pessoal\projects\digital_marketing\codigo\api-whatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (C:\Pessoal\projects\digital_marketing\codigo\api-whatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8264) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8264) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️
