### ISSUE TITLE
WapQuery.profilePicFind Not Working

### ISSUE THREAD

**Issue by oltanalkan** [open-wa/wa-automate-nodejs#1757]
Uncaught TypeError: Store.WapQuery.profilePicFind is not a function at

**Comment by dngda** [comment]
I also faced the same issue. Here's mine

> (node:7376) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Store.WapQuery.profilePicFind is not a function
    at Object.window.WAPI.getProfilePicFromServer (C:\Users\Administrator\Documents\nodejs\bot-whatsapp\node_modules\@open-wa\wa-automate\dist\lib\wapi.js:942:27)
    at __puppeteer_evaluation_script__:1:17
    at ExecutionContext._evaluateInternal (C:\Users\Administrator\Documents\nodejs\bot-whatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (C:\Users\Administrator\Documents\nodejs\bot-whatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
(node:7376) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 369)

**Comment by smashah** [comment]
I just tested this again. It is working as expected.

**Comment by ajhsu** [comment]
@oltanalkan I just ran into the same issue and here's my temporary local fix for it:

https://github.com/open-wa/wa-automate-nodejs/blob/adfb326795db87cf1c4937eb6212c5022f450b55/src/lib/wapi.js#L28
```diff
- { id: "WapQuery", conditions: (module) => (module.queryExist) ? module : ((module.default && module.default.queryExist) ? module.default : null) },
+ { id: "WapQuery", conditions: (module) => (module.profilePicFind) ? module : ((module.default && module.default.profilePicFind) ? module.default : null) },
```

Not sure why but my guess is that WAW updated their modules so that the original condition matcher matches the wrong module.
