### ISSUE TITLE
deleteStaleChats not working

### ISSUE THREAD

**Issue by blackchineykh** [open-wa/wa-automate-nodejs#1819]
**Describe the bug**
The process to delete stale chats failed with the below error:
```
unhandledRejection Error: Evaluation failed: ReferenceError: conversation is not defined    at __puppeteer_evaluation_script__:1:167186
    at Array.map (<anonymous>)
    at Object.window.<computed>.<computed> [as deleteStaleChats] (__puppeteer_evaluation_script__:1:167095)
    at __puppeteer_evaluation_script__:1:29
    at ExecutionContext._evaluateInternal (C:\Development\NodeJs\ecp-wa-core\node_modules\puppeteer\lib\ExecutionContext.js:102:19) 
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at ExecutionContext.evaluate (C:\Development\NodeJs\ecp-wa-core\node_modules\puppeteer\lib\ExecutionContext.js:33:16)
  -- ASYNC --
    at ExecutionContext.<anonymous> (C:\Development\NodeJs\ecp-wa-core\node_modules\puppeteer\lib\helper.js:94:19)
    at DOMWorld.evaluate (C:\Development\NodeJs\ecp-wa-core\node_modules\puppeteer\lib\DOMWorld.js:89:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
  -- ASYNC --
    at Frame.<anonymous> (C:\Development\NodeJs\ecp-wa-core\node_modules\puppeteer\lib\helper.js:94:19)
    at Page.evaluate (C:\Development\NodeJs\ecp-wa-core\node_modules\puppeteer\lib\Page.js:591:14)
    at Page.<anonymous> (C:\Development\NodeJs\ecp-wa-core\node_modules\puppeteer\lib\helper.js:95:27)
    at Client.<anonymous> (C:\Development\NodeJs\ecp-wa-core\node_modules\@open-wa\wa-automate\dist\api\Client.js:418:42)
    at Generator.next (<anonymous>)
    at C:\Development\NodeJs\ecp-wa-core\node_modules\@open-wa\wa-automate\dist\api\Client.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Development\NodeJs\ecp-wa-core\node_modules\@open-wa\wa-automate\dist\api\Client.js:23:12)
    at Client.pup (C:\Development\NodeJs\ecp-wa-core\node_modules\@open-wa\wa-automate\dist\api\Client.js:392:16)
    at Client.<anonymous> (C:\Development\NodeJs\ecp-wa-core\node_modules\@open-wa\wa-automate\dist\api\Client.js:2890:31)
  -- ASYNC --
    at Page.<anonymous> (C:\Development\NodeJs\ecp-wa-core\node_modules\puppeteer\lib\helper.js:94:19)
    at Client.<anonymous> (C:\Development\NodeJs\ecp-wa-core\node_modules\@open-wa\wa-automate\dist\api\Client.js:418:42)
    at Generator.next (<anonymous>)
    at C:\Development\NodeJs\ecp-wa-core\node_modules\@open-wa\wa-automate\dist\api\Client.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Development\NodeJs\ecp-wa-core\node_modules\@open-wa\wa-automate\dist\api\Client.js:23:12)
    at Client.pup (C:\Development\NodeJs\ecp-wa-core\node_modules\@open-wa\wa-automate\dist\api\Client.js:392:16)
    at Client.<anonymous> (C:\Development\NodeJs\ecp-wa-core\node_modules\@open-wa\wa-automate\dist\api\Client.js:2890:31)
    at Generator.next (<anonymous>)
    at C:\Development\NodeJs\ecp-wa-core\node_modules\@open-wa\wa-automate\dist\api\Client.js:27:71
```

**Steps to Reproduce**
Try to delete the stale chats with start index value at 1000

**create() code**
This is the code you use to create the client. e.g
```javascript

  create({
    sessionId: sessionId,
    sessionDataPath: sessionDataPath,
    useChrome: false,
    restartOnCrash: start,
    headless: process.env.CHROME_HEADLESS === "true",
    resizable: true,
    throwErrorOnTosBlock: true,
    qrTimeout: 0, //set to 0 to wait forever for a qr scan
    authTimeout: 0, //set to 0 to wait forever for connection to phone
    killProcessOnBrowserClose: false, //need to be false to support reload of service from GUI
    autoRefresh: true,
    safeMode: false,
    disableSpins: false,
    qrRefreshS: 15,
    cacheEnabled: false,
    blockCrashLogs: true,
    useStealth: true,
    
  })
```

**Expected behavior**
I passed the start index as 1000 and my expectations is to clear all chats beyond index 1000 in the list. 

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
✓ Browser Launched
┌─────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│       (index)       │                                                                   Values                                                                    │
├─────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│     WA_VERSION      │                                                                 '2.2123.7'                                                                  │
│       PAGE_UA       │ 'WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                       '4.7.0 UPDATE AVAILABLE: 4.7.1'                                                       │
│   BROWSER_VERSION   │                                                            'Chrome/83.0.4103.0'                                                             │
│         OS          │                                                                'Windows 10'                                                                 │
│      START_TS       │                                                                1624631531619                                                                │
└─────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Screenshots**
N/A

**Host (please complete the following information):**
 - OS: Windows 10

**Additional context**
I have lots of chats over a couple months so I dont know how this may have impacted:
See below:

✓ Client loaded with 15489 contacts, 12473 chats & 1745 messages in 46.037s

**Comment by smashah** [comment]
Should be fixed in latest patches, thanks
