### ISSUE TITLE
Cannot read property 'battery' of undefined

### ISSUE THREAD

**Issue by edneijunior** [open-wa/wa-automate-nodejs#1897]
**I have this error printing on the console, apparently it is not able to recover the battery status**

```bash
_Error: Evaluation failed: TypeError: Cannot read property 'battery' of undefined
    at Object.window.WAPI.getBatteryLevel (/var/www/w2api/node_modules/@open-wa/wa-automate/dist/lib/wapi.js:1002:23)
    at __puppeteer_evaluation_script__:1:13 Error: Evaluation failed: TypeError: Cannot read property 'battery' of undefined
    at Object.window.WAPI.getBatteryLevel (/var/www/w2api/node_modules/@open-wa/wa-automate/dist/lib/wapi.js:1002:23)
    at __puppeteer_evaluation_script__:1:13
    at ExecutionContext._evaluateInternal (/var/www/w2api/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:218:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)_
```
**Steps to reproduce the behavior:**
Execute below sample code
Scan QR code
create() code
```javascript
Array.prototype.find = function (...args)
{
    let index = this.findIndex(...args);
    if (index >= 0)
        return index >= 0 ? this[index] : void 0;
};

global.openWA = require('@open-wa/wa-automate');
const fs = require('fs');
const async = require("async");
const request = require('request');
const moment = require('moment');
const mime = require('mime-types');
const { default: PQueue } = require("p-queue");

global.uaOverride = 'WhatsApp/2.16.352 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15';

...
 _CLIENT.onStateChanged(state => {
        that.PROCESS_STATE(state);
    });

CLIENT.onAck(ack => {
        that.PROCESS_ACK(ack);
    },{
        interval:1000,
        concurrency: 1,
        intervalCap:1
    });
...
 openWA.create({
        sessionId: "/whatsSessions/" + F.config['instance'],
        headless: true,
        useChrome:true,
        qrTimeout:0,
        authTimeout:0,
        autoRefresh:true,
        cacheEnabled:false,
        throwErrorOnTosBlock:true
    }).then(function (client) {
        //EXECUTING MODULE SETUP
        if (qrCodeManager) {_
            qrCodeManager.send({connected: true});
        }
        WA_CLIENT.SETUP(client, F.config['webhook'], F.config['token']);
  });
}); 
```

**Expected behavior**
retrieve battery level information

**DEBUG INFO**
```javascript
{
  WA_VERSION: '2.2126.11' ,
  PAGE_UA: 'WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36',
  WA_AUTOMATE_VERSION: '4.9.0' , 
  BROWSER_VERSION: ''HeadlessChrome/91.0.4472.10' ,
  OS:''Linux 4.9';
}
```

![image](https://user-images.githubusercontent.com/67341065/125522663-b5cb2af4-0dcc-4c70-9eab-59978ccef028.png)

**Comment by smashah** [comment]
@edneijunior fixed in latest patches. please restart and try again. thanks
