### ISSUE TITLE
how to fixx??

### ISSUE THREAD

**Issue by erlanggadwi** [open-wa/wa-automate-nodejs#1900]
```markdown
npm ERR! code 1
npm ERR! path C:\Users\user\bot-whatsapp\node_modules\@open-wa\wa-automate
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c cross-env npm_config_yes=true npx ignore-check@latest -p '**.data.json' -p '**.node-persist**' --comment 'managed by open-wa'
npm ERR! (node:7448) ExperimentalWarning: The ESM module loader is experimental.
npm ERR! internal/modules/run_main.js:54
npm ERR!     internalBinding('errors').triggerUncaughtException(
npm ERR!                               ^
npm ERR!
npm ERR! Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
npm ERR!     at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:698:11)
npm ERR!     at Loader.resolve (internal/modules/esm/loader.js:97:40)
npm ERR!     at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
npm ERR!     at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:47:40)
npm ERR!     at link (internal/modules/esm/module_job.js:46:36) {
npm ERR!   code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Local\npm-cache\_logs\2021-07-14T01_35_59_574Z-debug.log
```

### Environment

```markdown
- OS: windows 10 
- Node: 12.18.3
- npm: 7.9.0
```

### Screenshots

![Untitled](https://user-images.githubusercontent.com/64958442/125546957-ec8f32c8-3d4c-4bee-8b88-21851c4ee9e8.png)

**Comment by smashah** [comment]
@erlanggadwi please update to the current/lts node version 14.7.3+
