### ISSUE TITLE
I can't download videos and audios

### ISSUE THREAD

**Issue by nicolaspizzolante** [open-wa/wa-automate-nodejs#1904]
I get this error when receiving a video or an audio, any suggestions?

```
encryption error: TypeError: Cannot read property 'markWebcCryptoElapsedT' of undefined; stack: TypeError: Cannot read property 'markWebcCryptoElapsedT' of undefined
    at https://web.whatsapp.com/bootstrap_qr.4b9c044a48c9fc5005b0.js:19:331438
    at https://web.whatsapp.com/bootstrap_qr.4b9c044a48c9fc5005b0.js:2:349363
    at q (https://web.whatsapp.com/bootstrap_qr.4b9c044a48c9fc5005b0.js:2:353990)
    at MutationObserver.H (https://web.whatsapp.com/bootstrap_qr.4b9c044a48c9fc5005b0.js:2:353571)```

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️
