### ISSUE TITLE
I can't download videos and audios

### ISSUE THREAD

**Issue by nicolaspizzolante** [open-wa/wa-automate-nodejs#1905]
I get this error when receiving a video or an audio, any suggestions?

```encryption error: TypeError: Cannot read property 'markWebcCryptoElapsedT' of undefined; stack: TypeError: Cannot read property 'markWebcCryptoElapsedT' of undefined
    at https://web.whatsapp.com/bootstrap_qr.4b9c044a48c9fc5005b0.js:19:331438
    at https://web.whatsapp.com/bootstrap_qr.4b9c044a48c9fc5005b0.js:2:349363
    at q (https://web.whatsapp.com/bootstrap_qr.4b9c044a48c9fc5005b0.js:2:353990)
    at MutationObserver.H (https://web.whatsapp.com/bootstrap_qr.4b9c044a48c9fc5005b0.js:2:353571)```

**Comment by smashah** [comment]
The link on the last issue was for the old issue template.

Please fill this in: 

https://github.com/open-wa/wa-automate-nodejs/issues/new?assignees=&labels=&template=bug_report.yaml&title=
