### ISSUE TITLE
InvalidMediaFileType when sending videos with client.sendFile

### ISSUE THREAD

**Issue by Cephas369** [open-wa/wa-automate-nodejs#1916]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

Error: Evaluation failed: Error: InvalidMediaFileType
    at Object.sendToChat (https://web.whatsapp.com/bootstrap_qr.4b9c044a48c9fc5005b0.js:18:167956)
    at __puppeteer_evaluation_script__:1:167799
    at async Object.window.<computed>.<computed> [as sendImage] (__puppeteer_evaluation_script__:1:1
63861)
    at ExecutionContext._evaluateInternal (C:\Users\user\Documents\vscode\wapi\node_modules\pup
peteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (C:\Users\user\Documents\vscode\wapi\node_modules\puppet
eer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)

### Mode

My own code

### Environment

```markdown
- OS: 
- Node: 
- npm:
```

**Comment by smashah** [comment]
Unable to reproduce the issue as there is no context to this issue
