### ISSUE TITLE
Buttons only work on some groups/contacts

### ISSUE THREAD

**Issue by WolfDWyc** [open-wa/wa-automate-nodejs#1922]
### Are you using the latest version of the library?

- [x] I have checked and am using the latest version of the library.

### Current Behavior

On some groups sending buttons works fine, but on others I get this error:
```javascript
node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Object prototype may only be an Object or null: undefined
    at Function.create (<anonymous>)
    at Object.window.<computed>.<computed> [as _[I REMOVED THIS PART]I=] (__puppeteer_evaluation_script__:1:115900)
    at Object.window.<computed>.<computed> [as sendButtons] (__puppeteer_evaluation_script__:1:125612)
    at __puppeteer_evaluation_script__:2:29
    at ExecutionContext._evaluateInternal (node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
```

### Expected Behavior

It should work on all groups.

### Steps To Reproduce

1. Environment: Windows 10
2. No special configuration added.
3. Run:
```javascript
await client.sendButtons(chatId, "Body", [
        {
            id: "1",
            "text": "Click"
        },
        {
            id: "1",
            "text": "Call"
        },
        {
            id: "1",
            "text": "Open Link"
        }
    ], "title", "footer")
```
Replace the chat ID until it doesn't work. 
**INFO:**
I haven't recognized a pattern yet, here's some more info:
- Worked on the first group I tried it with, 15 people or so - I'm a manager and I created it.
- Didn't work on 2 larger groups (257 people). I assumed it just meant it doesn't work when 1 or more person in the group hasn't updated their whatsapp.
- I then tried it on a contact and it worked, but then it didn't on a different contact, or on a group that has that contact, which supported my theory.
- Then I tried it on a contact from the original group that worked, and it didn't, and also created a group only with them ands tried it and it didn't work.

**So based on that, I think the pattern is NOT that everyone needs to have a new version and NOT that I have to manage/create the group.**

### Mode

EASY API/CLI

### create() code

```markdown
wa.create().then(client => start(client));
```

### DEBUG INFO

```markdown
┌─────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│       (index)       │                                                                   Values                                                                    │
├─────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│     WA_VERSION      │                                                                 '2.2126.11'                                                                 │
│       PAGE_UA       │ 'WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                  '4.11.1'                                                                   │
│   BROWSER_VERSION   │                                                        'HeadlessChrome/92.0.4512.0'                                                         │
│         OS          │                                                                'Windows 10'                                                                 │
│      START_TS       │                                                                1626797605474                                                                │
└─────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

### Environment

```markdown
- OS: Windows 10 
- Node: 16.5.0
- npm: 7.20.0
```

**Comment by smashah** [comment]
This error should no longer show up after some updates in v4.12.0
