### ISSUE TITLE
Qrtimeout: Session closed. Most likely the page has been closed

### ISSUE THREAD

**Issue by mrbarnk** [open-wa/wa-automate-nodejs#1944]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

It's crashing the server when qrcode is not scanned.

### Expected Behavior

It will crash the server when you don't scran the qr code on time

### Mode

EASY API/CLI

### create() code

```markdown
await create({
      ...config,
      autoRefresh: true,
      killTimer: 60,
      blockCrashLogs: true,
      // headless: false,
      multiDevice: true,
      // cacheEnabled: false,
      throwErrorOnTosBlock: true,
      logConsole: false,
      logConsoleErrors: true,
      useChrome: true,
      qrLogSkip: false,
      bypassCSP: true,
      disableSpins: true,
      useStealth: true,
      qrTimeout: 120,
      authTimeout: 100,
      messagePreprocessor: 'AUTO_DECRYPT_SAVE',
      restartOnCrash: async (client) => {
       // do something
      },
    })
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2126.14",
  "WA_AUTOMATE_VERSION": "4.12.1",
  "BROWSER_VERSION": "HeadlessChrome/85.0.4183.121",
  "START_TS": 1627318400437
}
```

### Environment

```markdown
- OS: Linux 5.4
- Node: 16.1.0
- npm:
```

### Screenshots

![image](https://user-images.githubusercontent.com/37006356/127029619-c89c6241-9683-4c8a-8f7f-48637705300d.png)

**Comment by mrbarnk** [comment]
![image](https://user-images.githubusercontent.com/37006356/127032976-04ce493d-2949-4ed5-97ce-d3b39cb11acd.png)

![image](https://user-images.githubusercontent.com/37006356/127032902-1077f758-4ee7-4905-b665-b730d889ec97.png)
![image](https://user-images.githubusercontent.com/37006356/127032932-48a50097-3721-4261-a156-d4beab3e5d8c.png)

**Comment by mrbarnk** [comment]
```
https://api.wasms.vip
(node:19796) Warning: Accessing non-existent property 'products' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Postman collection generated: open-wa-session.postman_collection.json
Setting Up API Explorer

        API Explorer (​http://localhost:8082/api-docs/ ​)
Checking if port 8082 is free
Port 8082 is now free.

• Listening on port 8082!
[
  '',
  'emmanuelbankole362327',
  'create',
  '?token=lcacv1xwniq266druc8hr1'
]
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                                                                   ┃
┃   @open-wa/wa-automate                                                                            ┃
┃    💬 🤖 The most reliable NodeJS whatsapp library for chatbots with advanced features.           ┃
┃   Version: 4.12.0                                                                                 ┃
┃   Check out the latest changes: https://github.com/open-wa/wa-automate-nodejs#latest-changes      ┃
┃                                                                                                   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
- Starting
- Version: 4.12.0
- Initializing WA
- Launching Browser
- Setting Up Browser
- Loading session data
- Found session data file: C:\Users\Mrbarnk\Documents\Projects\nodejs\waabot\sessions\emmanuelbankole362327.data.json
- Existing session data detected. Injecting...
- Existing session data injected
- Navigating to WA
Request failed with status code 400
Request failed with status code 400
Request failed with status code 400
Request failed with status code 400
Request failed with status code 400
- Page loaded in 1839ms: 200
- Browser Launched
- Debug info: {
  "WA_VERSION": "2.2126.14",
  "PAGE_UA": "WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
  "WA_AUTOMATE_VERSION": "4.12.0 UPDATE AVAILABLE: 4.12.1",
  "BROWSER_VERSION": "HeadlessChrome/92.0.4515.107",
  "OS": "Windows 10",
  "START_TS": 1627320549473
}
- Use this easy pre-filled link to report an issue: https://github.com/open-wa/wa-automate-nodejs/issues/new?template=bug_report.yaml&debug_info=%7B%0A%20%20%22WA_VERSION%22:%20%222.2126.14%22,%0A%20%20%22WA_AUTOMATE_VERSION%22:%20%224.12.0%20UPDATE%20AVAILABLE:%204.12.1%22,%0A%20%20%22BROWSER_VERSION%22:%20%22HeadlessChrome/92.0.4515.107%22,%0A%20%20%22START_TS%22:%201627320549473%0A%7D&environment=-%20OS:%20Windows%2010%0A-%20Node:%2014.17.0%0A-%20npm:%20%0A
- Injecting api
- WAPI injected
- Authenticating
Request failed with status code 400
Request failed with status code 400
Request failed with status code 400
Request failed with status code 400
Request failed with status code 400
- Authenticate to continue
Request failed with status code 400
Emitting
qr event detected for session sessions/emmanuelbankole362327 27
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █▀ ▄██▄█▄█▄▀▀▀  ▄ ▄█▀▄▀▄▄ ▀▀▄  ▀ ▄▀ ▀██ ▄▄▄▄▄ █
█ █   █ █▀  █▀▀▄ ▀▀▀▀ ██ ▄▄▀  █▄ █ ▄▀▀▀▄▄▄█▀▄▀█ █   █ █
█ █▄▄▄█ █▀ ▄▀▄ ▀██▄▀ █ ██ ▄▄▄  ▄▀ ▀▀  ▄▀ ▄  ███ █▄▄▄█ █
█▄▄▄▄▄▄▄█▄█ █ █ ▀▄▀ ▀▄▀ █ █▄█ ▀ █▄█ ▀▄█ ▀ █ █▄█▄▄▄▄▄▄▄█
█ ▄▄ ▄█▄▄  ▀▀▄▄▄▄▀▄ ▀█▀█▀▄▄▄▄   ▄█▄█▀▄▀█▀▀  ▀█▄█▄▀▄▀ ██
█ █▀▀▀█▄ █▄▀▀▀▀▀▄  ▄▄▄█ ▄▀▀████ ▄▄  ▀▄ ▀██▄▀█▄ ▀██ ██▀█
██▀█▀ ▀▄▄▄▀██ ▄█▀▄▄▄▀█▀█      ▀  ██▄ ▄▀█▀█ ▀▀▄▄█ ▄   ██
█▄▄▄▀▄█▄▄ ▄███▀█▀ ▀▄ ▄█▀█▀ ▄█▀▄▄▄▄██  ▄▀▄▄██▄ ▄▄▀▄▀█▀██
█ ▄█ ██▄█▀ ▀█▄▀█▀█▄▄ ▄█▀ ▄▀▄▀█ ▀▄█▄▄▄▄ █▀█▀ ▀████▄█▀▄ █
█▀   █▀▄▄ █▀██▀▄▀█▄▄█▄██ ▀▀▄██▀▀▄ ██▄ ▀█▄▄▄▀▄█▀▀  ▀▄▀██
█ █▄█ ▄▄▄ ▀▀▄▄▄█▄█▄▄▀▄▀▀██▄   ▀▀ █▄█   █▀▀▀▀▀█▄▄▄ █▄▄▀█
█▄ ▄█▀ ▄▄▀█▄▀▀▄ ▄▄▀▄ █▄▀▄▀ ▄▀█▀ ▄▀ █ ▄ ▄█▄▀▀▄ ▄█ ▀ █ ▀█
██▄▄  ▄▄▄   █▄▄▄▄▀  ▀██▀▄ ▄▄▄ ▀  ▀█▄▀▄ █▀▀▀ ▀ ▄▄▄ ▄▀▄▄█
█ ▄▄█ █▄█  █  █▄▄ ▀ ▀▄ ▄  █▄█   ██▄▀▀ █▄ ▄▀ ▄ █▄█ ▀█▀██
████▀▄ ▄▄ ▀  ▄▀▀██  ▄▄█▀ ▄  ▄▄▄  ███▄▄▀▄██ ▀▀▄▄▄  █▀ ▀█
██▀█ ▀█▄ ██ ▀█▀█ ▄▀ ▀▄▄▀▀▄█▄▄█▄█▄▀▄ █ ██▄ ▀  █▀▀ ▀ █▀██
██▀█▀▄ ▄▀▄ █▄▀▀█▀█▀▄ █▀█▀▀▄█  ▀▀▄███▄ ▄▄▀▀▀▀██▄▄█▀██▀██
█ ▄▄█▄█▄▀▄▄█  ▄▀▀█▀  █ ▀▀██▄▄▄▀ ▄██▀ ▀     ▀▄▀▀▀ ▄█▄▀▀█
█▀▄▄ ▀▀▄▄▄▀██  ▀▄█▄ ▀███▀▄ ██▀▀▀▄█ █ ▄▀▄▀█  █  ▄  █▄▄██
█▀▀▀█▀▀▄▄  ▄▄▀▄ ▄  ▀ ▀█▄▀▀▀ ███▄  █▄█▄█▄▀▀▄▄▄ ██▄  █▀██
█ ▄▄███▄▀▄▀██ ▄▄▄▀█ ▀██▀ ▄▄█▄▄█▀██ ▄▄ ▀█▀█▀▀▀█▄▄▄▀ ▀▄ █
█▄ ▀▄▄▄▄▀ ▀█▀██ ▄ ▀▀ ▄▄▀█▄▀▀▄▄██▄▀▀▄█ █▀▀ ▀  ▀█▀ ▀ ▄▄██
████▄██▄▄▀▄ ▀  █▄█▄ ▀▄ ▀▄ ▄▄▄   ▀██▄▄▄█▄███ ▀ ▄▄▄  ▄  █
█ ▄▄▄▄▄ █▄▀▀██▀  ▄▄█ ▄ ▄▄ █▄█ ▀█▄ ▄▄▀▄▀ ▀ ▄▀  █▄█ ▀█▀▀█
█ █   █ █ ▄▄▄█▄ ▀█▄▀▄▄██▀  ▄   ▀▄█▄▄  ▀▄█▀▀▀▀▄▄▄   ████
█ █▄▄▄█ █ ▀▀█ █▄▀█▀██▀▄ ▄██ ▀▀ ▄   ▀▀▄▀▀ █▄  █▄█▄▄ ▄▀▄█
█▄▄▄▄▄▄▄█▄▄▄████▄▄▄▄████▄▄▄████████▄▄▄▄▄███▄█▄█▄▄▄▄▄███

connect ETIMEDOUT 34.195.72.180:443
connect ETIMEDOUT 206.72.194.51:443
connect ETIMEDOUT 34.195.72.180:443
connect ETIMEDOUT 34.195.72.180:443
connect ETIMEDOUT 34.195.72.180:443
connect ETIMEDOUT 34.195.72.180:443
connect ETIMEDOUT 206.72.194.51:443
connect ETIMEDOUT 206.72.194.51:443
connect ETIMEDOUT 206.72.194.51:443
connect ETIMEDOUT 206.72.194.51:443
connect ETIMEDOUT 34.195.72.180:443
connect ETIMEDOUT 34.195.72.180:443
connect ETIMEDOUT 206.72.194.51:443
connect ETIMEDOUT 206.72.194.51:443
connect ETIMEDOUT 34.195.72.180:443
 - QR scan took too long. Session Timed Out. Shutting down. Consider increasing qrTimeout config variable: https://open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#qrtimeout
1|index  | - Authenticate to continue
1|index  | Error: Protocol error (Runtime.evaluate): Session closed. Most likely the page has been closed.
1|index  |     at CDPSession.send (/root/waabot/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:208:35)
1|index  |     at ExecutionContext._evaluateInternal (/root/waabot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:166:18)
1|index  |     at ExecutionContext.evaluate (/root/waabot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:27)
1|index  |     at DOMWorld.evaluate (/root/waabot/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:91:24)
1|index  |     at runMicrotasks (<anonymous>)
1|index  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
1|index  | Error: Protocol error (Runtime.evaluate): Session closed. Most likely the page has been closed.
1|index  |     at CDPSession.send (/root/waabot/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:208:35)
1|index  |     at ExecutionContext._evaluateInternal (/root/waabot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:166:18)
1|index  |     at ExecutionContext.evaluate (/root/waabot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:27)
1|index  |     at DOMWorld.evaluate (/root/waabot/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:91:24)
1|index  |     at runMicrotasks (<anonymous>)
1|index  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

**Comment by smashah** [comment]
@mrbarnk thanks for adding the details.

It's not really unexpected that the page is closed after logging the QR timeout error. The question is what is trying to evaluate code on the page after it has been closed?

For now, you can ignore the error till I figure out where its being triggered

**Comment by mrbarnk** [comment]
Thank you.

**Comment by mrbarnk** [comment]
I get this too.

Session data most likely expired due to manual host account logout. Please re-authenticate this session.

**Comment by smashah** [comment]
@mrbarnk probably because you are attempting to use multiDevice. Please do not use multi device with this library. It is not supported yet.

**Comment by mrbarnk** [comment]
yea! That just fixed it. Thanks.

**Comment by mrbarnk** [comment]
It's still happenning.

**Comment by mrbarnk** [comment]
![image](https://user-images.githubusercontent.com/37006356/129362189-c1c0bee4-c127-4094-8f22-85ca088340b9.png)

**Comment by mrbarnk** [comment]
![image](https://user-images.githubusercontent.com/37006356/129362585-ff8de359-7ec4-4392-bc6d-f0aa54089508.png)

**Comment by mrbarnk** [comment]
I think the kill process is causing the issue.

It's crashing the whole process, so it's affecting the other WhatsApp instance on the multi-session.

**Comment by mrbarnk** [comment]
Sorry, killProcessOnTimeout was the issue, as it's true by default.
