### ISSUE TITLE
4.12.2 just does not start on Windows

### ISSUE THREAD

**Issue by lascimmia** [open-wa/wa-automate-nodejs#1953]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

When I try to start Open-WA using `npx @open-wa/wa-automate`, it does not start showing:

```Javascript
TypeError: Expected type of "cloud-bucket" to be one of ["string", "boolean", "number", "array", "string-array", "boolean-array", "number-array"], got "object"
    at c:\node\node_modules\minimist-options\index.js:84:12
    at Array.forEach (<anonymous>)
    at buildOptions (c:\node\node_modules\minimist-options\index.js:64:23)
    at Object.meow [as default] (c:\node\node_modules\meow\index.js:148:18)
    at Object.cli (c:\node\node_modules\@open-wa\wa-automate\dist\cli\setup.js:335:32)
    at c:\node\node_modules\@open-wa\wa-automate\dist\cli\index.js:44:68
    at Generator.next (<anonymous>)
    at c:\node\node_modules\@open-wa\wa-automate\dist\cli\index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (c:\node\node_modules\@open-wa\wa-automate\dist\cli\index.js:4:12)
```

### Mode

EASY API/CLI

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2126.14",
  "WA_AUTOMATE_VERSION": "4.12.2",
  "BROWSER_VERSION": "HeadlessChrome/92.0.4512.0",
  "START_TS": 1627487351243
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 14.17.3
- npm: 6.14.13
```

**Comment by smashah** [comment]
@lascimmia thanks for the info.

I'll fix this later tonight, for now please use 

```
> npx @open-wa/wa-automate@4.12.1
```

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.12.3](https://github.com/open-wa/wa-automate-nodejs/compare/4.12.2...4.12.3) (2021-07-28)

- 🐛 fix #1953 [`#1953`](https://github.com/open-wa/wa-automate-nodejs/issues/1953)
- Release 4.12.3 [`81ab8cb`](https://github.com/open-wa/wa-automate-nodejs/commit/81ab8cbf6fff4226fe8125593e45d376a19de0c8)

**Comment by smashah** [comment]
@lascimmia should be fixed in latest version. thanks

**Comment by lascimmia** [comment]
YOU'RE GREAT 🥳
