### ISSUE TITLE
forceStaleMediaUpdate returns Evaluation failed: TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by syafiqfaiz** [open-wa/wa-automate-nodejs#2063]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

this is my test code
```
var wa = require('@open-wa/wa-automate');
const mime = require('mime-types');

var _waConfig = {
	sessionId: "myId",
	licenseKey: "myKet",
};

var messageId = "false_6013xxxxxxx@c.us_3EB0C0xxxxxxxx";

var _whatsappStart = (whatsapp) => {
	whatsapp.forceStaleMediaUpdate(messageId).then(refreshedMessage => {
		wa.decryptMedia(refreshedMessage).then((mediaData) => {
			debugger
			if (mediaData) {
				var filename = `${refreshedMessage.id}_${refreshedMessage.t}.${mime.extension(refreshedMessage.mimetype)}`;
				var base64 = mediaData.toString('base64');

				// do something with media
			} else {
				callback('No media detected.', null);
			}
		}).catch((err)=>{
			_socket.emit('updateWhatsappMessageMedia', { err });
		})
	}).catch(err => {
		debugger
	})
};

wa.create(_waConfig)
.then(async client => await _whatsappStart(client))
.catch(e => {
	console.log('CREATE ERROR', e.message);
});
```

`forceStaleMediaUpdate` returns error
```
err.message
'Evaluation failed: TypeError: Cannot read properties of undefined (reading 'id')
    at 
    at Object.WAPI.<computed> [as forceStaleMediaUpdate] (eval at <anonymous> (:1:10), <anonymous>:1:23190)
    at __puppeteer_evaluation_script__:1:20'
```

```
err.stack
'Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'id')
    at 
    at Object.WAPI.<computed> [as forceStaleMediaUpdate] (eval at <anonymous> (:1:10), <anonymous>:1:23190)
    at __puppeteer_evaluation_script__:1:20
    at ExecutionContext._evaluateInternal (/home/xxxxxx-whatsapp-server/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (/home/xxxx-whatsapp-server/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)'
    ```

### Expected Behavior

`forceStaleMediaUpdate` is expected to return message

### Steps To Reproduce

run this code

```
var wa = require('@open-wa/wa-automate');
const mime = require('mime-types');

var _waConfig = {
	sessionId: "myId",
	licenseKey: "myKet",
};

var messageId = "false_6013xxxxxxx@c.us_3EB0C0xxxxxxxx";

var _whatsappStart = (whatsapp) => {
	whatsapp.forceStaleMediaUpdate(messageId).then(refreshedMessage => {
		wa.decryptMedia(refreshedMessage).then((mediaData) => {
			debugger
			if (mediaData) {
				var filename = `${refreshedMessage.id}_${refreshedMessage.t}.${mime.extension(refreshedMessage.mimetype)}`;
				var base64 = mediaData.toString('base64');

				// do something with media
			} else {
				callback('No media detected.', null);
			}
		}).catch((err)=>{
			// do something with error
		})
	}).catch(err => {
		debugger
	})
};

wa.create(_waConfig)
.then(async client => await _whatsappStart(client))
.catch(e => {
	console.log('CREATE ERROR', e.message);
});

```

### Mode

My own code

### create() code

```markdown
wa.create(_waConfig)
.then(async client => await _whatsappStart(client))
.catch(e => {
	console.log('CREATE ERROR', e.message);
});
```

### DEBUG INFO

```markdown
Debug Info {
  WA_VERSION: 2.2132.6,
  PAGE_UA: 'WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36',
  WA_AUTOMATE_VERSION: 4.20.2,
  BROWSER_VERSION: HeadlessChrome/93.0.4577.0
}
```

### Environment

```markdown
- OS: ubuntu
- Node: v14.15.5
- npm: 7.9.0
```

**Comment by smashah** [comment]
@syafiqfaiz Thanks for filling out the template thoroughly.

this should be fixed now. please restart and try again.

**Comment by syafiqfaiz** [comment]
hi @smashah tq for the fix but a different error is returned

`err.message`
```
Evaluation failed: ReferenceError: mmrr is not defined
    at Object.window.<computed>.<computed> [as getNearbyMessages] (eval at <anonymous> (:1:10), <anonymous>:1:25795)
    at Object.window.<computed>.<computed> [as loadSpecificMessageId] (eval at <anonymous> (:1:10), <anonymous>:1:23908)
    at Object.window.WAPI.<computed> [as forceStaleMediaUpdate] (eval at <anonymous> (:1:10), <anonymous>:1:26566)
    at __puppeteer_evaluation_script__:1:20
```

`err.stack`
```
Error: Evaluation failed: ReferenceError: mmrr is not defined
    at Object.window.<computed>.<computed> [as getNearbyMessages] (eval at <anonymous> (:1:10), <anonymous>:1:25795)
    at Object.window.<computed>.<computed> [as loadSpecificMessageId] (eval at <anonymous> (:1:10), <anonymous>:1:23908)
    at Object.window.WAPI.<computed> [as forceStaleMediaUpdate] (eval at <anonymous> (:1:10), <anonymous>:1:26566)
    at __puppeteer_evaluation_script__:1:20
    at ExecutionContext._evaluateInternal (/home/faiz/borak/borak-whatsapp-server/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (/home/faiz/borak/borak-whatsapp-server/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16
```

**Comment by smashah** [comment]
@syafiqfaiz patched. please restart and try again

**Comment by syafiqfaiz** [comment]
@smashah 

it return the same error as before
```
'Evaluation failed: TypeError: Cannot read properties of undefined (reading 'id')
    at https://web.whatsapp.com/bootstrap_main.3eccc658bbc599e6dda2.js:2:63464
    at W (https://web.whatsapp.com/bootstrap_qr.99f4f9824125bfd8df54.js:2:366905)
    at new v (https://web.whatsapp.com/bootstrap_qr.99f4f9824125bfd8df54.js:2:357963)
    at Object.requestMediaReupload (https://web.whatsapp.com/bootstrap_main.3eccc658bbc599e6dda2.js:2:63435)
    at F.requestMediaReupload (https://web.whatsapp.com/bootstrap_qr.99f4f9824125bfd8df54.js:40:31231)
    at Object.window.<computed>.<computed> [as forceStaleMediaUpdate] (eval at <anonymous> (:1:10), <anonymous>:1:48885)'
```

**Comment by smashah** [comment]
@syafiqfaiz try now

**Comment by syafiqfaiz** [comment]
hi @smashah , it was supposed to return a message object
but now it return an empty object `{}`
![image](https://user-images.githubusercontent.com/8923682/131599433-eb27d628-59d5-4202-8bf0-8905102bec70.png)

**Comment by smashah** [comment]
@syafiqfaiz try now please

**Comment by syafiqfaiz** [comment]
hi @smashah , it still return empty object

**Comment by smashah** [comment]
@syafiqfaiz please DM me on discord with your session data and the exact message id you are using

**Comment by syafiqfaiz** [comment]
Its working now.
Thank you @smashah
