### ISSUE TITLE
sendButtons error (function not found)

### ISSUE THREAD

**Issue by kmirea** [open-wa/wa-automate-nodejs#2094]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

Hi!

Using  latest 4.20.6,  and host phone is regular account (not business).  Just wondering if this feature requires a business account ? 

calling CLIENT.sendButtons(chatId, buttons, title, footer) results in:

`======= 2021-09-05 06:43:56: Error: Evaluation failed: TypeError: _0x171a94[_0x13ef78(...)] is not a function
    at Object.window.<computed>.<computed> [as sendButtons] (__puppeteer_evaluation_script__:1:119775)
    at __puppeteer_evaluation_script__:2:29 Error: Evaluation failed: TypeError: _0x171a94[_0x13ef78(...)] is not a function
    at Object.window.<computed>.<computed> [as sendButtons] (__puppeteer_evaluation_script__:1:119775)
    at __puppeteer_evaluation_script__:2:29
    at ExecutionContext._evaluateInternal (/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:218:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)
`

Thanks & best regards

### Mode

My own code

### create() code

```markdown
create({
		sessionId: "1",
		sessionDataPath: "/whatsSessions/",
		authTimeout: 120,
		blockCrashLogs: true,
		disableSpins: true,
		headless: true,
		hostNotificationLang: 'EN_ZA',
		logConsole: false,
		popup: true,
		qrTimeout: 0,
		qrRefreshS:16,
		bypassCSP: true,
		browserRevision: "737027"
	}
```

### Environment

```markdown
- OS: 
- Node: 
- npm:
```

**Comment by kmirea** [comment]
possible cause: "patches": "https://cdn.openwa.dev/patches.json",  gives a 403 forbidden,

**Comment by smashah** [comment]
Hi @kmirea when you first opened this issue i tried with both a normal and business account and it was working properly. Tried again today, still working.

Please add more context for this issue.

Till then, closing.

Thanks

**Comment by victorfreire100** [comment]
> Hi @kmirea when you first opened this issue i tried with both a normal and business account and it was working properly. Tried again today, still working.
> 
> Please add more context for this issue.
> 
> Till then, closing.
> 
> Thanks

case '!button':
		await client.sendButtons(chatId, "Option", [
		{
        id: "1",
        "text": "Option 1"			
		},
		{
        id: "2",
        "text": "Option 2
		},
		], "")
		
		===========================
		
When the user chooses an option I want him to make a request in an api with the option id and send a confirmation msg. Can anyone help me?

**Comment by victorfreire100** [comment]
@smashah help me hhahaha
