### ISSUE TITLE
`sendTextWithMentions` method fails silently

### ISSUE THREAD

**Issue by rafaelgalani** [open-wa/wa-automate-nodejs#2138]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

Messages with mentions are not being sent. 

### Expected Behavior

The message to be correctly sent.

### Steps To Reproduce

1. Activate the multi-device support;
2. Start a new bot session (either chromium or chrome, it doesn't matter)
3. Check that using `sendTextWithMentions` (`WAPI.sendMessageWithMentions`) fails. 

### Mode

My own code

### create() code

```markdown
const browser = await puppeteer.launch({
    headless: false,
    executablePath: require('chrome-launcher').Launcher.getInstallations()[0]
});

const options = {
    sessionId: 'bot',
    headless: false,
    qrTimeout: 0,
    authTimeout: 0,
    restartOnCrash: start,
    cacheEnabled: false,
    useChrome: true,
    browserWSEndpoint: browser.wsEndpoint(),
    devtools: false,
    killProcessOnBrowserClose: true,
    throwErrorOnTosBlock: false,
    chromiumArgs: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--aggressive-cache-discard',
        '--disable-cache',
        '--disable-application-cache',
        '--disable-offline-load-stale-cache',
        '--disk-cache-size=0'
    ]
}

create(options)
    .then((client) => start(client))
    .catch((err) => console.error(err))
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2136.10",
  "WA_AUTOMATE_VERSION": "4.21.1",
  "BROWSER_VERSION": "Chrome/93.0.4577.82",
  "START_TS": 1631888858927
}
```

### Environment

```markdown
- OS: macOS Big Sur
- Node: 16.8.0
- npm: 7.21.0
```

### Anything else?

Yup. This is what is returned when calling the `WAPI.sendMessageWithMentions` method:

```json
{
    "message": "Msg",
    "name": "ModelCreateError",
    "stack": "ModelCreateError: Msg\n    at new i (https://web.whatsapp.com/bootstrap_qr.556a46806765846fd46b.js:2:406796)\n    at new k (https://web.whatsapp.com/bootstrap_qr.556a46806765846fd46b.js:56:220346)\n    at https://web.whatsapp.com/bootstrap_qr.556a46806765846fd46b.js:2:476087\n    at V (https://web.whatsapp.com/bootstrap_qr.556a46806765846fd46b.js:2:377126)\n    at MutationObserver.K (https://web.whatsapp.com/bootstrap_qr.556a46806765846fd46b.js:2:376705)",
    "model": {
        "ack": 0,
        "id": {
            "fromMe": true,
            "remote": "MYNUMBER-GROUPID@g.us",
            "id": "OM8GEGDVEGZXSZZLWQLI",
            "_serialized": "true_MYNUMBER-GROUPID@g.us_OM8GEGDVEGZXSZZLWQLI"
        },
        "local": true,
        "self": "out",
        "t": 1631889259,
        "to": "MYNUMBER-GROUPID@g.us",
        "isNewMsg": true,
        "type": "chat",
        "body": "message content @MYNUMBER",
        "quotedMsg": null,
        "mentionedJidList": [
            "MYNUMBER@c.us"
        ]
    }
}
```

I used it like this - from the dev console (`groupId` and `myNumber` both have valid values):
```javascript
WAPI.sendMessageWithMentions( groupId, `Message content @${myNumber}`)
```

Using the open-wa client's `sendTextWithMentions` method has the same effect:
```javascript
await client.sendTextWithMentions( groupId, `Message content @${myNumber}`)
```

_Edit: removed any personal information from the message_

**Comment by smashah** [comment]
@rafaelgalani new patch. should be fixed. try again please.
