### ISSUE TITLE
Undeinfed <== Typo? 

### ISSUE THREAD

**Issue by w0LFzk1nD** [open-wa/wa-automate-nodejs#2142]
I get an error message that does not belong to my work ive done.
So i guess, there might be a typo somewhere in your files.

Here is the error message

/home/pi/Desktop/ZOMBYY/PROJECT__ZOMBY_VD3v/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: ReferenceError: undeinfed is not defined
    at Object.window.<computed>.<computed> [as getNewMessageId] (__puppeteer_evaluation_script__:1:276416)
    at Object.window.<computed>.<computed> [as reply] (__puppeteer_evaluation_script__:1:270630)
    at ExecutionContext._evaluateInternal (/home/pi/Desktop/ZOMBYY/PROJECT__ZOMBY_VD3v/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/home/pi/Desktop/ZOMBYY/PROJECT__ZOMBY_VD3v/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)

**Comment by w0LFzk1nD** [comment]
Ah and yes, i am using the latest Version.
4.21.2

**Comment by smashah** [comment]
Patches
