### ISSUE TITLE
Asks to reauthenticate every time we start session in multidevice beta.

### ISSUE THREAD

**Issue by AffanTheBest** [open-wa/wa-automate-nodejs#2191]
### Are you using the latest version of the library?

- [x] I have checked and am using the latest version of the library.

### Current Behavior

It asks to re-authenticate the session everytime I run my code. 

### Expected Behavior

After scanning and authenticating it should save session data and reuse it later.

### Mode

My own code

### create() code

```js
wa.create().then(client => start(client));

ev.on('qr.**', qr =>  {
    writeFileSync('qr.png', qr.replace('data:image/png;base64,', ''),'base64')
})

function start(client) {
    console.log(Object.keys(client));
    client.onMessage(async message => {
    if (message.body === 'Hi') {
      await client.sendText(message.from, '👋 Hello!');
    }
  });
}
```

### DEBUG INFO

```markdown
Debug Info {
  WA_VERSION: 2.2138.10,
  PAGE_UA: WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36',
  WA_AUTOMATE_VERSION: 4.22.4,
  BROWSER_VERSION: HeadlessChrome/93.0.4577.0,
  OS: windows 11,
  START_TS: 1633084091667
}
```

### Environment

```markdown
- OS: Windoes 11
- Node: v14.17.0
- npm: 7.17.0
```

### Anything else?

Is there any support group over Telegram, Discord or somewhere else?

**Comment by daniloliebelKMM** [comment]
set config multiDevice:true

**Comment by AffanTheBest** [comment]
> set config multiDevice:true

I'm also getting error in getting list of groups.

My Code:
```js
async function initializeWhatsApp() {
    const client = await wa.create({multiDevice:true});
    return client;
}
async function main(){
    const waclient = await initializeWhatsApp();    
    const groups = await waclient.getAllGroups();
    console.log(groups);
}
main()
```

Error:
```
(node:8208) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Error: GROUP_JID: invalid jid type: Not an instance of WID
    at t.GROUP_JID (https://web.whatsapp.com/bootstrap_qr.354c89faa13c8648e20b.js:3:119067)
    at https://web.whatsapp.com/bootstrap_qr.354c89faa13c8648e20b.js:3:167602
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~bootstrap_qr.ae27dc4782610dceb543.js:2:63784)
    at s (https://web.whatsapp.com/vendor1~bootstrap_qr.ae27dc4782610dceb543.js:2:63995)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.ae27dc4782610dceb543.js:2:64054
    at j (https://web.whatsapp.com/bootstrap_qr.354c89faa13c8648e20b.js:2:379576)
    at new g (https://web.whatsapp.com/bootstrap_qr.354c89faa13c8648e20b.js:2:370471)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.ae27dc4782610dceb543.js:2:63935
    at t.queryGroup (https://web.whatsapp.com/bootstrap_qr.354c89faa13c8648e20b.js:3:165077)
    at ExecutionContext._evaluateInternal (C:\Users\siddi\Downloads\Projects\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)        
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (C:\Users\siddi\Downloads\Projects\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8208) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8208) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by AffanTheBest** [comment]
> set config multiDevice:true

Now I'm not getting qr code.

Error: 
```
(node:21884) UnhandledPromiseRejectionWarning: TimeoutError: waiting for function failed: timeout 30000ms exceeded
    at new WaitTask (C:\Users\siddi\Downloads\Projects\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:513:34)
    at DOMWorld.waitForFunction (C:\Users\siddi\Downloads\Projects\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:468:26)
    at Frame.waitForFunction (C:\Users\siddi\Downloads\Projects\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:909:32)
    at Page.waitForFunction (C:\Users\siddi\Downloads\Projects\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:2433:33)
    at Object.<anonymous> (C:\Users\siddi\Downloads\Projects\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:182:26)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\siddi\Downloads\Projects\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21884) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21884) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by smashah** [comment]
#2124

**Comment by smashah** [comment]
in v4.22.5 there will be better logging for this issue.
