### ISSUE TITLE
Evaluation failed: p at ExecutionContext._evaluateInternal

### ISSUE THREAD

**Issue by riservato-thiagomelo** [open-wa/wa-automate-nodejs#2196]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

The bot won't start at a this WhatsApp account and throws the following error.

### Expected Behavior

It should work?

### Steps To Reproduce

just running the config I sent. I won't work on this specific phone number

### Mode

My own code

### create() code

```markdown
const config = {
  inbox: /1000 LINKS/,
  targets: [
    /^((?!1000 LINKS).)*$/,
  ],
  waConfig: {
    sessionId: "WA-PROD--2",
    authTimeout: 0,
    blockCrashLogs: true,
    disableSpins: true,
    headless: true,
    hostNotificationLang: 'PT_BR',
    logConsole: false,
    popup: true,
    qrTimeout: 999999,
  }
}

const wa = require('@open-wa/wa-automate');

(async () => {

  const client = await wa.create(config);

  await start(client);
})()
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2138.13",
  "WA_AUTOMATE_VERSION": "4.22.5",
  "BROWSER_VERSION": "HeadlessChrome/93.0.4577.0",
  "START_TS": 1633292948357
}
```

### Environment

```markdown
- OS: Linux 5.11
- Node: 12.21.0
- npm:
```

### Anything else?

Here's some evidences that might give you guys a clue:

- it's an account registered with a *really old sim card*;
- multi devices (BETA) version also doesn't work;
- Galaxy note 10 plus;

**Comment by smashah** [comment]
Please paste all the logs including the launch logs and the whole error.

**Comment by riservato-thiagomelo** [comment]
`You can also authenticate the session at: http://localhost:7000
- Starting
- Version: 4.22.5
- Initializing WA
- Launching Browser
- Setting Up Browser
- Loading session data
- Found session data file: /home/business/Study/wa/COVID_HELPER.data.json
- Existing session data detected. Injecting...
- Existing session data injected
- Navigating to WA
- Page loaded in 5869ms: 200
- Browser Launched
- Debug info: {
  "WA_VERSION": "2.2138.13",
  "PAGE_UA": "WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
  "WA_AUTOMATE_VERSION": "4.22.5",
  "BROWSER_VERSION": "HeadlessChrome/93.0.4577.0",
  "OS": "Linux 5.11",
  "START_TS": 1633442958296
}
- Use this easy pre-filled link to report an issue: https://github.com/open-wa/wa-automate-nodejs/issues/new?template=bug_report.yaml&debug_info=%7B%0A%20%20%22WA_VERSION%22:%20%222.2138.13%22,%0A%20%20%22WA_AUTOMATE_VERSION%22:%20%224.22.5%22,%0A%20%20%22BROWSER_VERSION%22:%20%22HeadlessChrome/93.0.4577.0%22,%0A%20%20%22START_TS%22:%201633442958296%0A%7D&environment=-%20OS:%20Linux%205.11%0A-%20Node:%2014.18.0%0A-%20npm:%20%0A
- Injecting api
- WAPI injected
- Authenticating
- Authenticated
- Waiting for ripe session...
- Reinjecting api
- WAPI Reinjected
- Checking if session is valid
- Downloading patches from https://cdn.openwa.dev/patches.json
- Client is ready
- Generating patch hash
- Downloaded patches in 13.64s
- Installing patches
- Patches Installed: 689bd
- Client loaded for normal account with 6366 contacts, 1969 chats & 6916 messages in 89.116s
- 🚀 @OPEN-WA ready for account: 5118
(node:24919) UnhandledPromiseRejectionWarning: Error: Evaluation failed: p
    at ExecutionContext._evaluateInternal (/home/business/Study/wa/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (/home/business/Study/wa/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:24919) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24919) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by riservato-thiagomelo** [comment]
@smashah 
I'm pretty sure it's the same issue (account that has joined too much groups):
https://github.com/open-wa/wa-automate-nodejs/issues/2009

From my last reduced test case: this only ever happens when calling getAllGroups();

**Comment by smashah** [comment]
@riservato-thiagomelo that would be useful once we run out of ideas here. Try this first please

```javascript
const config = {
  inbox: /1000 LINKS/,
  targets: [
    /^((?!1000 LINKS).)*$/,
  ],
  waConfig: {
    sessionId: "WA_PROD__2",
    authTimeout: 0,
    blockCrashLogs: true,
    disableSpins: true,
    headless: true,
    hostNotificationLang: 'PT_BR',
    logConsole: false,
    popup: true,
    qrTimeout: 0,
  }
}

async function start(client) {
	console.log("__client__started")
  const handleMessage = async (message) => {
    console.log(message.body)
  }
	console.log("__set__onMessage")

  await client.onMessage(handleMessage);
	console.log("__onMessage_set")
}

const wa = require('@open-wa/wa-automate');

(async () => {

  const client = await wa.create(config.waConfig);

  await start(client);
})()
```

**Comment by smashah** [comment]
I just tested with the above code on a normal session and was not able to replicate the error
