### ISSUE TITLE
Cannot read properties of undefined

### ISSUE THREAD

**Issue by w0LFzk1nD** [open-wa/wa-automate-nodejs#2204]
I dont know exactly what throws up this error.
But i guess it is the get Info Via Invite

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'id')
    at Object.window.<computed>.<computed> [as reply] (__puppeteer_evaluation_script__:1:200982)
    at ExecutionContext._evaluateInternal (C:\Users\chris\Desktop\Pr0j3ct_ZombY_v2\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\Users\chris\Desktop\Pr0j3ct_ZombY_v2\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)

[Yes i use the newest Version]

**Comment by smashah** [comment]
@w0LFzk1nD I just tested inviteInfo and it is working as expected

You'll need to be more specific. Feel free to discuss this in the discord
