### ISSUE TITLE
Error on send first text message with paid account MD

### ISSUE THREAD

**Issue by daopapp** [open-wa/wa-automate-nodejs#2228]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

When i send a text message to a new number with paid license, occurs this error:

```javascript
{"success":false,"error":{"name":"Error","message":"Evaluation failed: Error: update chat table failed\n    at https://web.whatsapp.com/bootstrap_qr.ffb6038a09060468cde3.js:56:671745\n    at V (https://web.whatsapp.com/bootstrap_qr.ffb6038a09060468cde3.js:2:382173)\n    at MutationObserver.K (https://web.whatsapp.com/bootstrap_qr.ffb6038a09060468cde3.js:2:381752)"}}
```

not happen all time, but sometimes.

and when i tried to resend, occurs this error:

```javascript
{"success":false,"error":{"name":"Error","message":"Evaluation failed: TypeError: Cannot read property 'status' of null\n    at Object.window.<computed>.<computed> [as sendMessage] (eval at <anonymous> (:1:10), <anonymous>:1:25607)"}}
```

seems like this error happens when you send message to a customer that use a older version of whatsApp

### Expected Behavior

send the message successfully 

### Steps To Reproduce

```bash
curl -X 'POST' \
  'http://216.245.217.78:9505/sendText' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "args": {
    "to": "@c.us",
    "content": "Olá Valdir"
  }
}'
```

error: 
```javascript
{
  "success": false,
  "error": {
    "name": "Error",
    "message": "Evaluation failed: Error: update chat table failed\n    at https://web.whatsapp.com/bootstrap_qr.ffb6038a09060468cde3.js:56:671745\n    at V (https://web.whatsapp.com/bootstrap_qr.ffb6038a09060468cde3.js:2:382173)\n    at MutationObserver.K (https://web.whatsapp.com/bootstrap_qr.ffb6038a09060468cde3.js:2:381752)"
  }
}
```

### Mode

EASY API/CLI

### DEBUG INFO

```javascript
{
  "WA_VERSION": "2.2140.7",
  "WA_AUTOMATE_VERSION": "4.23.2",
  "BROWSER_VERSION": "HeadlessChrome/79.0.3945.88",
  "START_TS": 1634304690727
}
```

### Environment

```markdown
- OS: Linux 4.15
- Node: 16.2.0
- npm:
```

**Comment by tmsbrasil** [comment]
I´m having the same problem here. What was the solution? May you help me? I´m usign the 4.55.2 version.

**Comment by smashah** [comment]
@tmsbrasil full the issue template

**Comment by tmsbrasil** [comment]
> @tmsbrasil full the issue template

hello, i just put the full issue here: https://github.com/open-wa/wa-automate-nodejs/issues/3042
