### ISSUE TITLE
missing media request

### ISSUE THREAD

**Issue by aymenitc** [open-wa/wa-automate-nodejs#2231]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

I'm having this error several times a day. It's happening for few days now. I haven't changed anything in the code.
It occur with different type of messages.
for example when someone request image sticker, it sends the sticker then immediately throw this error. 
Media is missing from this request
```
/home/aymenitc/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/api/Client.js:2818
                throw new errors_1.CustomError(errors_1.ERROR_NAME.MEDIA_MISSING, "Media is missing from this request");
                      ^

MEDIA_MISSING: Media is missing from this request
    at Client.<anonymous> (/home/aymenitc/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/api/Client.js:2818:23)
    at Generator.next (<anonymous>)
    at /home/aymenitc/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/api/Client.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/home/aymenitc/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/api/Client.js:23:12)
    at Client.stickerServerRequest (/home/aymenitc/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/api/Client.js:2770:16)
    at Client.<anonymous> (/home/aymenitc/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/api/Client.js:2930:37)
    at Generator.next (<anonymous>)
    at /home/aymenitc/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/api/Client.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/home/aymenitc/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/api/Client.js:23:12)
    at Client.sendEmoji (/home/aymenitc/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/api/Client.js:2929:16)
    at Client.<anonymous> (/home/aymenitc/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/api/Client.js:269:43)
    at Generator.next (<anonymous>)
    at /home/aymenitc/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/api/Client.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/home/aymenitc/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/api/Client.js:23:12)
    at /home/aymenitc/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/api/Client.js:267:45
    at Client.<anonymous> (/home/aymenitc/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/api/Client.js:590:92)
    at Generator.next (<anonymous>)
    at fulfilled (/home/aymenitc/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/api/Client.js:24:58)
    at runMicrotasks (<anonymous>)
```

### Expected Behavior

before, it sends stickers or media without throwing this error

### Mode

My own code

### create() code

```markdown
options 

headless: headless,
        qrTimeout: 0,
        authTimeout: 0,
        restartOnCrash: start,
        cacheEnabled: false,
        cachedPatch: true,
        useChrome: true,
        killProcessOnBrowserClose: true,
        throwErrorOnTosBlock: false,
        chromiumArgs: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--aggressive-cache-discard',
            '--disable-cache',
            '--disable-application-cache',
            '--disable-offline-load-stale-cache',
            '--disk-cache-size=0'
        ]
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2140.7",
  "WA_AUTOMATE_VERSION": "4.23.3",
  "BROWSER_VERSION": "HeadlessChrome/92.0.4515.131",
  "START_TS": 1634462441907
}
```

### Environment

```markdown
- OS: Linux 5.11
- Node: 15.10.0
- npm:
```

**Comment by aymenitc** [comment]
I think it is solved, by just updating npm. 
The Bot is running now for 25 hours with no errors.
