### ISSUE TITLE
App crash when using sendTextWithMentions

### ISSUE THREAD

**Issue by snowfluke** [open-wa/wa-automate-nodejs#2267]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

I'm using a cronjob inside the client and using the sendTextWithMentions method without realizing there's not any @ symbol inside it. Then the app crashed, failed to catch the exception.

Error msg:
```
/home/snowfluke/Videos/Programs/apps/snowWA/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of null (reading 'filter')
    at Object.window.<computed>.<computed> [as sendMessageWithMentions] (__puppeteer_evaluation_script__:1:264641)
    at __puppeteer_evaluation_script__:3:29
    at ExecutionContext._evaluateInternal (/home/snowfluke/Videos/Programs/apps/snowWA/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/home/snowfluke/Videos/Programs/apps/snowWA/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)

Node.js v17.0.1
```

### Expected Behavior

The error catched and the app won't crashed.

### Steps To Reproduce

1. Use client.sendTextWithMentions method
2. Don't insert any @ symbol at the second parameter

### Mode

My own code

### create() code

```markdown
const { create, Client } = require("@open-wa/wa-automate");
const commandHandler = require("./commandHandler");
const config = require("./config");
const crons = require("./crons");

const start = async (bot = new Client()) => {
	bot.onStateChanged((state) => {
		console.log(state);
		if (state === "CONFLICT" || state === "UNLAUNCHED") bot.forceRefocus();
	});

	bot.onIncomingCall(async (callData) => {
		await bot.sendText(
			callData.peerJid,
			"Maaf sedang tidak bisa menerima panggilan.\n\n-ini adalah pesan otomatis (bot)"
		);
	});

	bot.onMessage(async (message) => {
		bot.getAmountOfLoadedMessages().then((msg) => {
			if (msg >= 3000) {
				console.log("Clear cache messages");
				bot.cutMsgCache();
			}
		});
		commandHandler(bot, message);
	});

	crons(bot);
};

create(config(start))
	.then((bot) => start(bot))
	.catch((err) => console.log(err));
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2142.12",
  "WA_AUTOMATE_VERSION": "4.23.7",
  "BROWSER_VERSION": "HeadlessChrome/93.0.4577.0",
  "START_TS": 1636118331233
}
```

### Environment

```markdown
- OS: Linux 5.11
- Node: 17.0.1
- npm: 8.1.0
```

**Comment by smashah** [comment]
This should be fixed
