### ISSUE TITLE
All methods to send files stopped working

### ISSUE THREAD

**Issue by aymenitc** [open-wa/wa-automate-nodejs#2321]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Are you using Multi-device?

- [ ] I am using a multi-device session and I have set multiDevice to true in my config OR am using the --multi-device flag

### Current Behavior

When calling:
sendFile or sendFileFromUrl or sendAudio or even sendPtt

I get error:
``` 
UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default')
 ```

### Expected Behavior

sending files was working yesterday. I changed nothing in the code

### Steps To Reproduce

for example:
``` 
client.sendPtt(from, './media/tts.mp3', id) 
```

### Mode

My own code

### create() code

```markdown
nothing changed
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2146.9",
  "WA_AUTOMATE_VERSION": "4.24.2",
  "BROWSER_VERSION": "HeadlessChrome/95.0.4638.69",
  "START_TS": 1637765021206
}
```

### Environment

```markdown
- OS: Linux 5.11
- Node: 14.18.1
- npm:
```

### Anything else?

I'm not using multi-device.
and I did not set the flag for multi-device

**Comment by Bautista-Baiocchi-lora** [comment]
I am also getting the same error. I've reported it in the discord server. 

code snippet to reproduce:
```
const sendFileMessage = async (
  client: Client,
  to: ChatId,
  response: WappFileResponse
) => {
  const { url, title, filename } = response;

  await client.sendFile(to, url, title, filename).catch((err) => {
    console.error(err);
    throw new WAPPResponseException("File", false);
  });
};
```

error stacktrace in console:

```
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default')
    at _0x2799ae (eval at <anonymous> (:1:10), <anonymous>:1:65722)
    at Object.window.<computed>.mfs (eval at <anonymous> (:1:10), <anonymous>:1:65755)
    at Object.window.<computed>.<computed> [as sendImage] (__puppeteer_evaluation_script__:1:104141)
    at ExecutionContext._evaluateInternal (/usr/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/usr/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
```
