### ISSUE TITLE
forwardMessages failed to forward text message 

### ISSUE THREAD

**Issue by syafiqfaiz** [open-wa/wa-automate-nodejs#2381]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Are you using Multi-device?

- [ ] I am using a multi-device session and I have set multiDevice to true in my config OR am using the --multi-device flag

### Current Behavior

I am implementing `forwardMessages` feature.
I discovered two bugs.
1) if I am forward text message(no media) it will fail

here is the error log

```
forwardMessagesErr:  Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'asMms')
    at g._isMediaMsg (https://web.whatsapp.com/bootstrap_qr.fa9b5ba408af1a3623ab.js:57:275527)
    at https://web.whatsapp.com/bootstrap_qr.fa9b5ba408af1a3623ab.js:57:276823
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~bootstrap_qr.0a79e3d2f87b3c2c6883.js:2:63784)
    at s (https://web.whatsapp.com/vendor1~bootstrap_qr.0a79e3d2f87b3c2c6883.js:2:63995)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.0a79e3d2f87b3c2c6883.js:2:64054
    at K (https://web.whatsapp.com/bootstrap_qr.fa9b5ba408af1a3623ab.js:2:418226)
    at new m (https://web.whatsapp.com/bootstrap_qr.fa9b5ba408af1a3623ab.js:2:413194)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.0a79e3d2f87b3c2c6883.js:2:63935
    at g.forwardMessages (https://web.whatsapp.com/bootstrap_qr.fa9b5ba408af1a3623ab.js:57:276860)
    at ExecutionContext._evaluateInternal (/home/faiz/borak/borak-whatsapp-server/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (/home/faiz/borak/borak-whatsapp-server/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    ```
    
2) sometimes the `msgId` returned doesnt match the message Id provided by `onAnyMessage`

### Expected Behavior

I am expecting `forwardMessages` to work with forward text message
and for it to consistently returning the right message Id

### Steps To Reproduce

in ubuntu
run this code

```
	_whatsapp.forwardMessages(to, [message.id], false).then((msgId) => {
			console.log('forwardMessages', msgId);
		}).catch((err)=>{
			console.log('forwardMessagesErr: ', err)
		});;
		```

### Mode

My own code

### create() code

```markdown
var _waConfig = {
	sessionId: _config.phone,
	licenseKey: _config.license,
	cacheEnabled: true,
	qrTimeout: 0,
	// authTimeout: 0,
	// killProcessOnTimeout: true,
	// logConsoleErrors: true,
};
```
```
wa.create(_waConfig)
  .then(client => _whatsappStart(client))
  .then(()=>checkConnectionStatus())
  .catch(e => {
    console.log('CREATE ERROR', e.message);
  });
```
```


### DEBUG INFO

```markdown
┌─────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│       (index)       │                                                                    Values                                                                    │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│     WA_VERSION      │                                                                 '2.2147.16'                                                                  │
│       PAGE_UA       │ 'WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                   '4.27.9'                                                                   │
│   BROWSER_VERSION   │                                                         'HeadlessChrome/97.0.4691.0'                                                         │
│         OS          │                                                                 'Linux 5.11'                                                                 │
│      START_TS       │                                                                1640660528504                                                                 │
└─────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

### Environment

```markdown
- OS: ubuntu 20.04
- Node: v14.15.5
- npm: 7.12.1
```

### Anything else?

I am not using multidevice, but it require me to check the checkbox

**Comment by smashah** [comment]
@syafiqfaiz I just tested forwarding 50+ messages of different types from chat A to chat B without encountering this error. As far as I can tell, the forwardmessages function in the session checks if the message is an mms. That check happens on the message object itself. Essentially the message you are trying to forward is `undefined`.

The only way I can instigate the error you are getting is by asking it to forward a message ID of a message that does not exist.

What is the source of `message` in this code? What is encapsulating this code? `onAnyMessage` callback? If so then the issue is that `onAnyMessage` is emitting bogus message IDs.

```js
_whatsapp.forwardMessages(to, [message.id], false).then((msgId) => {
		console.log('forwardMessages', msgId);
	}).catch((err)=>{
		console.log('forwardMessagesErr: ', err)
	});
```

I suggest checking the message actually exists before trying to send it by using [getMessageById](https://docs.openwa.dev/classes/api_Client.Client.html#getMessageById).

If my suspicions are correct and the message does not actually exist then we need to figure out why.

It could be that the message does not exist in the session cache anymore (i.e the message is really old and hence not loaded on boot). 

I need more context about `message`

thanks.

**Comment by syafiqfaiz** [comment]
that make sense, I save the message locally. So the message might not exist in the session when I forward it.

tested forwarding recent messages and found no problem
and if I try to forward older messages, then the problem arises
`forwardMessages ERROR: Message does not exist true_6014915xxxx@c.us_3EB0DF4C8DD7863CF17A_out`

here is the  message object
```
{
    "borakId": "2fa0d288-66d2-45ab-bd82-6d76a5aff02d",
    "id": "true_6013250xxxx@c.us_3EB03C9FFA3619E3CCB1",
    "chatId": "6013250xxxx",
    "isGroupMsg": false,
    "from": "6014915xxxx@c.us",
    "to": "6013250xxxx@c.us",
    "author": "6014915xxxx@c.us",
    "name": "6014915xxxx@c.us",
    "type": "sent",
    "sentAt": 1641185344,
    "message": "test",
    "isImage": false,
    "isFile": false,
    "isAudio": false,
    "isVideo": false,
    "isSticker": false,
    "isMedia": false,
    "isLink": false,
    "mimeType": null,
    "fileCaption": null,
    "replyBy": {
        "id": "bdadda30-c9e8-4f9f-8522-c9eaba572ca1",
        "name": "faiz syafiq",
        "email": "email@gmail.com"
    },
    "quotedMsg": null,
    "isForwarded": null,
    "original": {
        "id": "true_6013250xxxx@c.us_3EB03C9FFA3619E3CCB1",
        "body": "test",
        "type": "chat",
        "subtype": null,
        "t": 1641185344,
        "from": "6014915xxxx@c.us",
        "to": "6013250xxxx@c.us",
        "self": "out",
        "ack": 0,
        "isNewMsg": true,
        "star": false,
        "isFromTemplate": false,
        "quotedMsg": null,
        "mentionedJidList": [],
        "isVcardOverMmsDocument": false,
        "isForwarded": false,
        "labels": [],
        "productHeaderImageRejected": false,
        "isDynamicReplyButtonsMsg": false,
        "isMdHistoryMsg": false,
        "requiresDirectConnection": null,
        "fromMe": true,
        "sender": {
            "id": "6014915xxxx@c.us",
            "type": "in",
            "isBusiness": true,
            "forcedBusinessUpdateFromServer": true,
            "formattedName": "You",
            "isMe": true,
            "isMyContact": false,
            "isPSA": false,
            "isUser": true,
            "isWAContact": true,
            "profilePicThumbObj": {
                "eurl": null,
                "id": "6014915xxxx@c.us",
                "tag": null
            },
            "msgs": null
        },
        "timestamp": 1641185344,
        "content": "test",
        "isGroupMsg": false,
        "isMedia": false,
        "isNotification": false,
        "isPSA": false,
        "chat": {
            "id": "6013250xxxx@c.us",
            "pendingMsgs": false,
            "lastReceivedKey": {
                "fromMe": true,
                "remote": "6013250xxxx@c.us",
                "id": "3EB0FE2FC5B25AA4FF4D",
                "_serialized": "true_6013250xxxx@c.us_3EB0FE2FC5B25AA4FF4D"
            },
            "t": 1641175183,
            "unreadCount": 0,
            "archive": false,
            "isReadOnly": false,
            "modifyTag": 940930,
            "muteExpiration": 0,
            "name": "Syafiq Faiz",
            "notSpam": true,
            "pin": 0,
            "ephemeralDuration": 0,
            "ephemeralSettingTimestamp": 0,
            "hasUnreadMention": false,
            "archiveAtMentionViewedInDrawer": false,
            "hasChatBeenOpened": false,
            "msgs": null,
            "kind": "chat",
            "canSend": true,
            "isGroup": false,
            "formattedTitle": "Syafiq Faiz",
            "contact": {
                "id": "6013250xxxx@c.us",
                "name": "Syafiq Faiz",
                "shortName": "Syafiq",
                "pushname": "Syafiq Faiz",
                "type": "in",
                "isBusiness": false,
                "isEnterprise": false,
                "statusMute": false,
                "labels": [],
                "disappearingModeDuration": 0,
                "disappearingModeSettingTimestamp": 0,
                "formattedName": "Syafiq Faiz",
                "isMe": false,
                "isMyContact": true,
                "isPSA": false,
                "isUser": true,
                "isWAContact": true,
                "profilePicThumbObj": {
                    "eurl": "https://pps.whatsapp.net/v/t61.24694-24/225392435_1906501589688204_7588473270856323226_n.jpg?ccb=11-4&oh=823525718be0fee0c7322bf635972f95&oe=61D754DA",
                    "id": "6013250xxxx@c.us",
                    "img": "https://web.whatsapp.com/pp?e=https%3A%2F%2Fpps.whatsapp.net%2Fv%2Ft61.24694-24%2F225392435_1906501589688204_7588473270856323226_n.jpg%3Fccb%3D11-4%26oh%3D823525718be0fee0c7322bf635972f95%26oe%3D61D754DA&t=s&u=6013250xxxx%40c.us&i=1640321496&n=1sWh4K1JSZezqOTL3IiL3cVUEHfO7x6nWkFUYt8jZoY%3D",
                    "imgFull": "https://web.whatsapp.com/pp?e=https%3A%2F%2Fpps.whatsapp.net%2Fv%2Ft61.24694-24%2F225392435_1906501589688204_7588473270856323226_n.jpg%3Fccb%3D11-4%26oh%3D823525718be0fee0c7322bf635972f95%26oe%3D61D754DA&t=l&u=6013250xxxx%40c.us&i=1640321496&n=1sWh4K1JSZezqOTL3IiL3cVUEHfO7x6nWkFUYt8jZoY%3D",
                    "raw": null,
                    "tag": "1640321496"
                },
                "msgs": null
            },
            "groupMetadata": null,
            "presence": {
                "id": "6013250xxxx@c.us",
                "chatstates": []
            },
            "isOnline": false,
            "participantsCount": 1
        },
        "isOnline": false,
        "chatId": "6013250xxxx@c.us",
        "quotedMsgObj": null,
        "mediaData": {},
        "text": "test"
    },
    "thumb": null
}
```

**Comment by smashah** [comment]
@syafiqfaiz this is the new error I implemented in the patches.

Its actually a good thing that you save the message locally, can you try to send the whole message object (instead of just the ID) and try again please

**Comment by syafiqfaiz** [comment]
How can I send the whole message object? Tts currently only accepting [mesageId] right

**Comment by syafiqfaiz** [comment]
hi @smashah 

I've tried again with sending the whole message, but it return with `Message does not exist`


```	
_whatsapp.forwardMessages(to, [message.original], false).then((msgId) => {
			debugger
			console.log('forwardMessages', msgId);`
```

**Comment by smashah** [comment]
@syafiqfaiz ok I'm going to try to figure this out

**Comment by syafiqfaiz** [comment]
hi @smashah, I hope I dont sound pushy, but is this issue fixable?
I will need to start implementing workaround if this can't be fixed

thank you

**Comment by smashah** [comment]
@syafiqfaiz I've created some updates to the patches that should address this by manually loading old messages in the relevant chat in order to find the original message object. It's an Insider's feature for now so it should work on your licensed account. If it works for you let me know and I'll make it GA.

Thanks

**Comment by smashah** [comment]
Basically, if [getMessageById](https://docs.openwa.dev/classes/api_Client.Client.html#getMessageById) returns nothing, you have to run [loadEarlierMessages](https://docs.openwa.dev/classes/api_Client.Client.html#loadEarlierMessages) until you hit that message id. Once that happens, then forward the message.

If that's unfeasible then I'll try to figure out a way to mock the message as you already have the whole object.

**Comment by smashah** [comment]
@syafiqfaiz working?

**Comment by syafiqfaiz** [comment]
I haven't found any issue. I can forward older messages now. Thank you shah
