### ISSUE TITLE
 No session data file found for session : session

### ISSUE THREAD

**Issue by setyo719** [open-wa/wa-automate-nodejs#2395]
✓ Version: 4.24.2
✓ No session data file found for session : session
✖ Navigating to WA
D:\wa-bot\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:116
                    ? new Error(`${response.errorText} at ${url}`)
                      ^

Error: net::ERR_NAME_NOT_RESOLVED at https://web.whatsapp.com
    at navigate (D:\wa-bot\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:116:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async FrameManager.navigateFrame (D:\wa-bot\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:91:21)
    at async Frame.goto (D:\wa-bot\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:417:16)
    at async Page.goto (D:\wa-bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:1156:16)

Node.js v17.1.0

i accidentally deleted the session, how do i get the session back?

**Comment by smashah** [comment]
`ERR_NAME_NOT_RESOLVED` is an error from the browser and is a DNS resolution error.

Please check your internet connection.

You cannot get a deleted session back.

If you want to back up your session data files then add this to your config:

https://docs.openwa.dev/interfaces/api_model_config.ConfigObject.html#sessionDataBucketAuth


thanks

**Comment by smashah** [comment]
Please also see this discussion:

https://github.com/open-wa/wa-automate-nodejs/discussions/2401
