### ISSUE TITLE
failed with net::ERR_ABORTED error

### ISSUE THREAD

**Issue by c0nf1ck** [open-wa/wa-automate-nodejs#2398]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Are you using Multi-device?

No

### Current Behavior

Tried to run the demo on this library, however I'm keep getting this error:

```
- Starting
- Version: 4.28.5
- Initializing WA
- Launching Browser
- Setting Up Page
- Loading session data
- No session data file found for session : SESSION_1
- Navigating to WA
- Navigating to WA
Error: net::ERR_ABORTED at https://web.whatsapp.com
    at navigate (/home/usr1/apps/whatsapp-test/node_modules/@open-wa/wa-automate/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:155:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async FrameManager.navigateFrame (/home/usr1/apps/whatsapp-test/node_modules/@open-wa/wa-automate/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:130:21)
    at async Frame.goto (/home/usr1/apps/whatsapp-test/node_modules/@open-wa/wa-automate/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:500:16)
    at async Page.goto (/home/usr1/apps/whatsapp-test/node_modules/@open-wa/wa-automate/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:16)
```

### Expected Behavior

Run the simple demo

### Steps To Reproduce

```
uname -a
Linux vultr.guest 4.15.0-163-generic #171-Ubuntu SMP Fri Nov 5 11:55:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

```
lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
```

### Mode

My own code

### create() code

```markdown
wa.create({
  sessionId: "SESSION_1",
  multiDevice: false,
  authTimeout: 60,
  blockCrashLogs: true,
  disableSpins: true,
  headless: true,
  hostNotificationLang: 'PT_BR',
  logConsole: false,
  qrTimeout: 0, //0 means it will wait forever for you to scan the qr code
}).then(client => start(client)).catch((err) => console.error(err));

function start(client) {
  client.onMessage(async message => {
    if (message.body === 'Hi') {
      await client.sendText(message.from, '👋 Hello!');
    }
  });
}
```
```


### DEBUG INFO

_No response_

### Environment

```markdown
- OS: 
- Node: 
- npm:
```

**Comment by smashah** [comment]
@c0nf1ck please paste all of the logs from the start of the process until you reach this error

**Comment by smashah** [comment]
This error seems to be a networking issue? I'm not able to replicate.

related:
https://github.com/puppeteer/puppeteer/issues/2794

Will re-open when you have more detail

**Comment by smashah** [comment]
@c0nf1ck 

Please see: https://github.com/puppeteer/puppeteer/issues/8246#issuecomment-1356463832
