### ISSUE TITLE
API stucks and give error on "Checking session integrity"

### ISSUE THREAD

**Issue by lascimmia** [open-wa/wa-automate-nodejs#2498]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

Launching as npx @open-wa/wa-automate, stucks on "Checking session integrity" and gives an error:

```
TimeoutError: waiting for function failed: timeout 30000ms exceeded
    at new WaitTask (c:\node\node_modules\@open-wa\wa-automate\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:526:34)
    at DOMWorld.waitForFunction (c:\node\node_modules\@open-wa\wa-automate\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:477:26)
    at Frame.waitForFunction (c:\node\node_modules\@open-wa\wa-automate\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:993:32)
    at Page.waitForFunction (c:\node\node_modules\@open-wa\wa-automate\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:2479:33)
    at c:\node\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:193:26
    at Generator.next (<anonymous>)
    at fulfilled (c:\node\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at CDPSession.send (c:\node\node_modules\@open-wa\wa-automate\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:218:35)
    at ExecutionContext._evaluateInternal (c:\node\node_modules\@open-wa\wa-automate\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:204:50)
    at ExecutionContext.evaluateHandle (c:\node\node_modules\@open-wa\wa-automate\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:155:21)
    at DOMWorld.addScriptTag (c:\node\node_modules\@open-wa\wa-automate\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:186:35)
```

### Expected Behavior

Just to start, as it used to do since few days ago

### Steps To Reproduce

Launch on Win10, with node -v v14.17.6 and npx -v 6.14.15.
Same error with or without these files:
- open-wa-session.postman_collection.json
- open-wa-session.sw_col.json
- session.data.json
- wa-automate
- wa-automate.cmd
- wa-automate.ps1

### DEBUG INFO

```markdown
TimeoutError: waiting for function failed: timeout 30000ms exceeded
    at new WaitTask (c:\node\node_modules\@open-wa\wa-automate\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:526:34)
    at DOMWorld.waitForFunction (c:\node\node_modules\@open-wa\wa-automate\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:477:26)
    at Frame.waitForFunction (c:\node\node_modules\@open-wa\wa-automate\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:993:32)
    at Page.waitForFunction (c:\node\node_modules\@open-wa\wa-automate\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:2479:33)
    at c:\node\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:193:26
    at Generator.next (<anonymous>)
    at fulfilled (c:\node\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at CDPSession.send (c:\node\node_modules\@open-wa\wa-automate\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:218:35)
    at ExecutionContext._evaluateInternal (c:\node\node_modules\@open-wa\wa-automate\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:204:50)
    at ExecutionContext.evaluateHandle (c:\node\node_modules\@open-wa\wa-automate\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:155:21)
    at DOMWorld.addScriptTag (c:\node\node_modules\@open-wa\wa-automate\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:186:35)
```

### Environment

```markdown
- OS: Windows 10
- Node: 4.17.6
- npm: 6.14.15
```

**Comment by lascimmia** [comment]
Seems that a workaround is to delete the folder "_IGNORE_session", but this force to new authentication

**Comment by smashah** [comment]
Please try https://github.com/open-wa/wa-automate-nodejs/releases/tag/4.31.0 and report back if this is still happening so i can reopen this issue.

thanks
