### ISSUE TITLE
ß

### ISSUE THREAD

**Issue by HNParda** [open-wa/wa-automate-nodejs#2499]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

When i start a new session with a new ID it works at the first start but when close it and try to start the session again it fails until i delete the _IGNORE_ARDA folder.

### Steps To Reproduce

const options = {
  sessionId: 'ARDA',
  multiDevice: true,
  licenseKey: "0C8F0FB3-88284FF2-AB37FE54-B989E2A9",
  headless: true,
  qrTimeout: 0,
  authTimeout: 0,
  restartOnCrash: start,
  cacheEnabled: false,
  useChrome: true,
  killProcessOnBrowserClose: true,
  throwErrorOnTosBlock: false,
  disableSpins: true,
  logging: [
  {
    type: "file"
  }
  ]
}

just changed multiDevice to true

### create() code

```markdown
create(options)
  .then((client) => start(client))
  .catch((err) => new Error(err))
```

### DEBUG INFO

```markdown
There is no debug info
```

### Environment

```markdown
- OS: Windows 11
- Node: 17.4.0
- npm: 8.4.0
```

### Screenshots/Logs

- Starting
- Version: 4.30.12
- Initializing WA
- Launching Browser
- MD Enabled, turning off incognito mode.
- Data dir: ARDA/_IGNORE_ARDA
- Browser launched: 654ms
- Setting Up Page
- Loading session data
- No session data file found for session : ARDA
- No session data detected. Opting in for MD.
- Make sure to keep the session alive for at least 5 minutes after scanning the QR code before trying to restart a session!!
- Pre page launch setup complete: 14ms
- Navigating to WA
- Page loaded but something may have gone wrong: 2838ms
- Page loaded
- Base inject: 350ms
- WAPI inject: 20ms
- Checking session integrity
- Session integrity check failed, trying again... 2
- WAPI inject: 15ms
- Checking session integrity
- Session integrity check failed, trying again... 3
- WAPI inject: 17ms
- Checking session integrity
- Session integrity check failed, trying again... 4
- WAPI inject: 19ms
- Checking session integrity
- Session integrity check failed, trying again... 5
- WAPI inject: 12ms
- Checking session integrity
- Session integrity check failed, trying again... 6
- WAPI inject: 17ms
- Checking session integrity
- Session integrity check failed, trying again... 7
- WAPI inject: 16ms
- Checking session integrity
- Session integrity check failed, trying again... 8
- WAPI inject: 17ms
- Checking session integrity
- Session integrity check failed, trying again... 9
- WAPI inject: 11ms
- Checking session integrity
- Session integrity check failed, trying again... 10
- WAPI inject: 16ms
- Checking session integrity
TimeoutError: waiting for function failed: timeout 30000ms exceeded
    at new WaitTask (C:\Users\ArdaM\Desktop\bot\node_modules\puppeteer-core\lib\cjs\puppeteer\common\DOMWorld.js:526:34)
    at DOMWorld.waitForFunction (C:\Users\ArdaM\Desktop\bot\node_modules\puppeteer-core\lib\cjs\puppeteer\common\DOMWorld.js:477:26)
    at Frame.waitForFunction (C:\Users\ArdaM\Desktop\bot\node_modules\puppeteer-core\lib\cjs\puppeteer\common\FrameManager.js:993:32)
    at Page.waitForFunction (C:\Users\ArdaM\Desktop\bot\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Page.js:2479:33)
    at C:\Users\ArdaM\Desktop\bot\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:193:26
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\ArdaM\Desktop\bot\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
- Session integrity check failed, trying again... 11
C:\Users\ArdaM\Desktop\bot\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:218
            return Promise.reject(new Error(`Protocol error (${method}): Session closed. Most likely the ${this._targetType} has been closed.`));
                                  ^

Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at CDPSession.send (C:\Users\ArdaM\Desktop\bot\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:218:35)
    at ExecutionContext._evaluateInternal (C:\Users\ArdaM\Desktop\bot\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:204:50)
    at ExecutionContext.evaluateHandle (C:\Users\ArdaM\Desktop\bot\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:155:21)
    at DOMWorld.addScriptTag (C:\Users\ArdaM\Desktop\bot\node_modules\puppeteer-core\lib\cjs\puppeteer\common\DOMWorld.js:186:35)

Node.js v17.4.0

**Comment by smashah** [comment]
Please try https://github.com/open-wa/wa-automate-nodejs/releases/tag/4.31.0 and report back if this is still happening so i can reopen this issue.

thanks
