### ISSUE TITLE
Problem when call healthCheck

### ISSUE THREAD

**Issue by fukumori** [open-wa/wa-automate-nodejs#2538]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Legacy (Normal)

### What type of host account are you experiencing this issue on?

Tested and experienced on both

### Mode

EASY API/CLI

### Current Behavior

middleware -> error Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at __puppeteer_evaluation_script__:1:216144
    at Array.find (<anonymous>)
    at Object.window.<computed>.<computed> [as healthCheck] (__puppeteer_evaluation_script__:1:215939)
    at ExecutionContext._evaluateInternal (/root/.npm/_npx/6d534a70e4144d63/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/root/.npm/_npx/6d534a70e4144d63/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)

### Expected Behavior

healthCheck response.

### Steps To Reproduce

curl --request POST 'localhost:8080/healthCheck'

### create() code

```markdown
"sessionId":"session","useChrome":true,"ignoreScripts":true,"debug":true,"keepAlive":true,"port":8080,"webhook":"http://localhost:8888/webhook/wp","key":"...","noApi":false,"host":"localhost","verbose":false,"ef":["qr","STARTUP","MD_DETECT"],"allowSessionDataWh":false,"generateApiDocs":true,"sessionDataOnly":false,"skipSavePostmanCollection":false,"headful":false,"preAuthDocs":false,"stats":false,"noKillOnLogout":false,"cors":false,"socket":false,"emitUnread":false,"popup":false
```

### DEBUG INFO

```markdown
WA_VERSION          '2.2206.9'
PAGE_UA             'WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36'
WA_AUTOMATE_VERSION '4.31.7'
BROWSER_VERSION.    'HeadlessChrome/98.0.4758.102'
OS.                 'Linux 5.4'
START_TS            1646253545133
```

### Environment

```markdown
- OS: Ubuntu 20.04.4 LTS
- Node: v16.14.0
- npm: 8.3.1
```

### Screenshots/Logs

When call healthCheck throws this error:

middleware -> error Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at __puppeteer_evaluation_script__:1:216144
    at Array.find (<anonymous>)
    at Object.window.<computed>.<computed> [as healthCheck] (__puppeteer_evaluation_script__:1:215939)
    at ExecutionContext._evaluateInternal (/root/.npm/_npx/6d534a70e4144d63/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/root/.npm/_npx/6d534a70e4144d63/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)

### Anything else?

google-chrome-stable/stable,now 98.0.4758.102-1 amd64 [installed]

**Comment by smashah** [comment]
@fukumori should be fixed now
