### ISSUE TITLE
Add a new participant to a group generates ADD_PARTICIPANTS_ERROR: INSUFFICIENT_PERMISSIONS error

### ISSUE THREAD

**Issue by guijob** [open-wa/wa-automate-nodejs#2567]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

I'm getting this error:

```
ADD_PARTICIPANTS_ERROR: INSUFFICIENT_PERMISSIONS
    at Client.<anonymous> (C:\whatsapp-core\node_modules\@open-wa\wa-automate\dist\api\Client.js:2645:23)
    at Generator.next (<anonymous>)
    at fulfilled (C:\whatsapp-core\node_modules\@open-wa\wa-automate\dist\api\Client.js:24:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
{
    "name": "ADD_PARTICIPANTS_ERROR",
    "message": "INSUFFICIENT_PERMISSIONS"
}

```

### Expected Behavior

Add a participant to a group

### Steps To Reproduce

```
async function main() {
  try {
    const client = await wa.create({
        multiDevice: true,
        useChrome: true,
        disableSpins: true,
        headless: true,
        hostNotificationLang: 'PT_BR',
        logConsole: false,
        callTimeout: 10 * 1000,
        killProcessOnTimeout: true,
    });

    const me = await client.getMe();
    const { wid: groupWid } = await client.createGroup('test group', [me.me._serialized]);
    const groupId = groupWid._serialized;

    await client.addParticipant(groupId, `someHiddenNumber@c.us`);
  } catch(error) {
    console.error(error);
  }
}

main();
```

### create() code

```markdown
const client = await wa.create({
        multiDevice: true,
        useChrome: true,
        disableSpins: true,
        headless: true,
        hostNotificationLang: 'PT_BR',
        logConsole: false,
        callTimeout: 10 * 1000,
        killProcessOnTimeout: true,
    });
```

### DEBUG INFO

```markdown
- Debug info: {
  "WA_VERSION": "2.2208.7",
  "PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
  "WA_AUTOMATE_VERSION": "4.32.7",
  "BROWSER_VERSION": "HeadlessChrome/99.0.4844.51",
  "OS": "Windows 10",
  "START_TS": 1647356116814
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 14.17.0
- npm: 6.14.13
```

**Comment by guijob** [comment]
@smashah, the same number who creates the group is the one who tries to add a participant. Nevermind, rescanning QR code did work! closing this issue
