### ISSUE TITLE
SendAudio/sendFile is crashing for some links/files

### ISSUE THREAD

**Issue by shifoc** [open-wa/wa-automate-nodejs#2598]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

My own code

### Current Behavior

sending Files/audios is crashing the program

PS: although I am using a business account, the library seems to think I am using a normal account
" Client loaded for normal account [MD] with 456 contacts, 76 chats & 95 messages in 30.012s"

### Steps To Reproduce

await client.sendFile(message.from, link, message.id);

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2208.14",
  "WA_AUTOMATE_VERSION": "4.32.17",
  "BROWSER_VERSION": "HeadlessChrome/100.0.4889.0",
  "START_TS": 1648331934043,
  "LATEST_VERSION": true,
  "CLI": false
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 16.13.1
- npm: 8.3.0
```

### Screenshots/Logs

C:\Users\User\project\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: Error: InvalidMediaFileType
    at m.sendToChat (https://web.whatsapp.com/bootstrap_qr.7472073f4355d08a7723.js:65:262053)
    at __puppeteer_evaluation_script__:1:193251
    at async Object.window.<computed>.<computed> [as sendImage] (__puppeteer_evaluation_script__:1:189687)
    at ExecutionContext._evaluateInternal (C:\Users\USER\Desktop\Depot\wa bot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\Users\user\project\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)

**Comment by smashah** [comment]
@shifoc please share the files which is resulting in this error.

Most likely you need to set useChrome: true in your config

**Comment by shifoc** [comment]
thank you, it worked!
