### ISSUE TITLE
`leaveGroup` is not working.

### ISSUE THREAD

**Issue by BbayuGt** [open-wa/wa-automate-nodejs#2664]
```
0|. | Error: Evaluation failed: q
0|. |     at ExecutionContext._evaluateInternal (/root/bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
0|. |     at runMicrotasks (<anonymous>)
0|. |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|. |     at async ExecutionContext.evaluate (/root/bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
```

Code
```js
client.leaveGroup(message.chat.groupMetadata.id)
```

**Comment by smashah** [comment]
patched
