### ISSUE TITLE
 Error: Evaluation failed: Error: update chat table failed

### ISSUE THREAD

**Issue by rizwan92** [open-wa/wa-automate-nodejs#2672]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

I wanted to send a message to one of my old friends using a chat id but the message could not get delivered. I am facing an error 
```

Error: Evaluation failed: Error: update chat table failed
59|samwad  |     at https://web.whatsapp.com/bootstrap_qr.b037bf792031d950b323.js:69:841011
59|samwad  |     at W (https://web.whatsapp.com/bootstrap_qr.b037bf792031d950b323.js:5:274524)
59|samwad  |     at MutationObserver.x (https://web.whatsapp.com/bootstrap_qr.b037bf792031d950b323.js:5:271101)
59|samwad  | Error: Evaluation failed: Error: update chat table failed
59|samwad  |     at https://web.whatsapp.com/bootstrap_qr.b037bf792031d950b323.js:69:841011
59|samwad  |     at W (https://web.whatsapp.com/bootstrap_qr.b037bf792031d950b323.js:5:274524)
59|samwad  |     at MutationObserver.x (https://web.whatsapp.com/bootstrap_qr.b037bf792031d950b323.js:5:271101)
59|samwad  |     at ExecutionContext._evaluateInternal (/root/backends/samwad-limelight/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
59|samwad  |     at runMicrotasks (<anonymous>)
59|samwad  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
59|samwad  |     at async ExecutionContext.evaluate (/root/backends/samwad-limelight/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)


```

### Expected Behavior

Message should deliver to my contact (chatId)

### Steps To Reproduce

1. node js v16.13.0
2. config ` const client = await create({
        sessionId,
        debug: true,
        logging: [{ type: "console" }],
        multiDevice: true,
      });`
3. I wanted to send a message to multiple people with one click. I ran a loop with a 300 ms delay. I send messages one by one after 300 ms. to accomplish this i am using the Aigle library 
this is how loop works in Aigle 

```
 Aigle.resolve(chatIds) // where chatIds is array of string
      .concatLimit(1, iterator) // where where iterator is function defined below and concat limit is it send mesage to one people at one time
      .then((array) => {
        console.log("all messages sent at ", new Date());
      });
```

```
// this funcation iterate individual chatid
    const iterator = (chatId, index, collection) => { // chatid is string, index is 0 , and collection is all array of string
      return Aigle.delay(300).then(async () => { //  Aigle.delay(3000) is responsible for delay in 300 ms
        const wacontact = await _client.getContact(chatId); // we extract the wacontact using chat id
        await GlobalController.sendMessage(_client, wacontact, _message); // my personal send function to send message described below
        console.log(
          `message sent to ${index + 1}/${collection.length} at `,
          new Date()
        );
        return null;
      });
    };
```

```
// my personal function to send message
 sendMessage: async (client, wacontact, message) => {
    const {id: chatId,name} = wacontact;
      return client.sendText(chatId, message);
  },
```

### create() code OR full CLI command + CONFIG

```markdown
const client = await create({
        sessionId,
        debug: true,
        logging: [{ type: "console" }],
        multiDevice: true,
      });
```

### DEBUG INFO

```markdown
Debug Info {
  WA_VERSION: ...,
  PAGE_UA: ...,
  WA_AUTOMATE_VERSION: ...,
  BROWSER_VERSION: ...
}
```

### Environment

```markdown
- OS: Ubuntu 20.04
- Node: 16.13.0
- npm: 5
```

**Comment by smashah** [comment]
Debug info is missing. Paste all of your logs please. till then closing.
