### ISSUE TITLE
 Sending PTT on certain number cause error : middleware -> error Error: Evaluation failed: TypeError: r._find is not a function

### ISSUE THREAD

**Issue by ahmeaqas** [open-wa/wa-automate-nodejs#2691]
Hello Shah Mohammad,

First of all thanks for such a beautiful piece of code.

We have just observed an error while sending a ptt message via EasyAPI. Sending the same payload works on one number and it throws an error on other. Error log is as follows;

`0|start  | middleware -> error Error: Evaluation failed: TypeError: r._find is not a function
0|start  |     at https://web.whatsapp.com/bootstrap_qr.15b07f37ecbe5a626367.js:69:531761
0|start  |     at Generator.next (<anonymous>)
0|start  |     at t (https://web.whatsapp.com/vendor1~bootstrap_qr.6ce3b7f48ca2444bd7bf.js:2:65356)
0|start  |     at s (https://web.whatsapp.com/vendor1~bootstrap_qr.6ce3b7f48ca2444bd7bf.js:2:65567)
0|start  |     at https://web.whatsapp.com/vendor1~bootstrap_qr.6ce3b7f48ca2444bd7bf.js:2:65626
0|start  |     at Y (https://web.whatsapp.com/bootstrap_qr.15b07f37ecbe5a626367.js:5:274376)
0|start  |     at new y (https://web.whatsapp.com/bootstrap_qr.15b07f37ecbe5a626367.js:5:266943)
0|start  |     at https://web.whatsapp.com/vendor1~bootstrap_qr.6ce3b7f48ca2444bd7bf.js:2:65507
0|start  |     at W._serverQuery (https://web.whatsapp.com/bootstrap_qr.15b07f37ecbe5a626367.js:69:532127)
0|start  |     at W._query (https://web.whatsapp.com/bootstrap_qr.15b07f37ecbe5a626367.js:69:531253)
0|start  |     at ExecutionContext._evaluateInternal (/home/pi/docker/data/wa-automate/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
0|start  |     at runMicrotasks (<anonymous>)
0|start  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|start  |     at async ExecutionContext.evaluate (/home/pi/docker/data/wa-automate/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)`

We are using HTTP POST via Nodered. msg.payload data is as follows, (phone number is hidden off course).

`{"args":{"to":"92XXXXXXXX41@c.us","file":"data:audio/mpeg;base64,//NIxAAVKI4BdAjMECQAkKFTAnOIX1zRNAALTaIgxA8AIZBBR6YerPkIPxBkD7onwccIJQHwfD/WoMbIjD8QO9EoGIYL4Jv4IBj+GJR0Tn8/D8oXfIFDnwQOeUd9YfggcJoO27JF0GHkD2xLimsY2FR5WChXKtQob4oPuNgQJDB8+x1A3vwoykAMsS+eSrSm//NIxC4WKIYYLDDGSIdYgXeLAZU22utrC2AFlQXeYe4GlMMn1bah5tpxyaWLTdSL02xKpTg0EkUyngImKxBa0HTICwMYBk0IC6IQ3DqjyfDY2bvS7SSa7JUXghhnrAn9WghAzCAZkkXj2qcOENVE0oOz84VDgWKFwsGap25w3dtpl9o+RRuNOJHG6X9tfGvF//NIxFgwW5IQAVlgAAHg4BR1V5LRnjjDkmbTid6rN6QwVvX8bYpe/Hfu3Oy5Ck2lLN5frdX6Nr3/YrnXim7G5fm451/83MvM2WO/MsVyafOQQ/Tp7GYrv50FJmm/SlKr/pe1M6m5M78zem+xIEFnmFRPekyNuUoAggBEBn9ejxvQDWxi0vBggKa/jO3U0XEO//NIxBkjEvZUs5hoADompsomjsJd3p3TWPYrJhSVsya0zREgGxOHGtBqlsikxQRTEHBJAARwbYLSHpvdzdJnZ0iIX0zAmloy9u3ordV4lAWslyMN43E8kC3+r313sy3c4dOlxM8bF06QSOS2r////mZgkTE7GqJf//6gbBEKwxoq6FEpyoX7uFS4lkkcTuJK//NIxA8gclJYJcxIAXOQXbYL5v4THlFI4XJ0knLvpNHc0JOcjusQqF7acGP5wtdNe1cJKYzVSc4KGW2kbSy9kZrCMuvsUd7DYK1NHL1aRhGUcq6k0eQmox5yzahTHv+d7/C9/urbSOu92sH/2Pt/l5P+5lfOrOVCwhnNJUAb+3Kcyl2tK9E7GT80vc7QhIWg//NIxBAfak58AGGHw..."}}`

**Comment by smashah** [comment]
I cannot replicate the problem. this is what im trying:

```js
{
  "args": {
    "to": "1234511111111@c.us",
    "file": "https://file-examples.com/storage/fe86b4dded62757649745df/2017/11/file_example_MP3_700KB.mp3"
  }
}
```

**Comment by smashah** [comment]
@ahmeaqas closing due to inactivity.

Please provide the exact file this is occurring on to reopen.

Also, join the discord by clicking the discord badge in the readme
