### ISSUE TITLE
emitUnreadMessages stopped working

### ISSUE THREAD

**Issue by GladistonXD** [open-wa/wa-automate-nodejs#2723]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

emitUnreadMessages() stopped working today

### Expected Behavior

Worked

### Steps To Reproduce

client.emitUnreadMessages()

### create() code OR full CLI command + CONFIG

```markdown
{       
        sessionId: 'client',
        headless: true,
        multiDevice: true,
        qrTimeout: 0,
        authTimeout: 0,
        restartOnCrash: start,
        cacheEnabled: true,
        useChrome: true,
        killProcessOnBrowserClose: true,
	logConsoleErrors: true,
        throwErrorOnTosBlock: false
};
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2218.8",
  "WA_AUTOMATE_VERSION": "4.36.6",
  "BROWSER_VERSION": "HeadlessChrome/102.0.5005.61",
  "START_TS": 1653724508645
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 14.17.6
- npm: 6.14.15
```

**Comment by smashah** [comment]
@GladistonXD what error message do you get?

**Comment by GladistonXD** [comment]
> @GladistonXDqual mensagem de erro você recebe?

```
Promise { <pending> }
...\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^
Error: Evaluation failed: TypeError: Cannot read properties of null (reading 'arrayBuffer')
    at window.<computed>.<computed> (__puppeteer_evaluation_script__:1:176674)
    at ExecutionContext._evaluateInternal (...\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (...\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
```

**Comment by GladistonXD** [comment]
I opened all the messages manually and then I ran it and it worked, I believe it was some bug generating this error

**Comment by GladistonXD** [comment]
Now I'm getting this new error message, I've updated all repositories

```
info: IN 822d7  {"_args":{},"_method":"emitUnreadMessages","timestamp":"2022-06-05T21:55:50.837Z"}
...\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: ReferenceError: unread is not defined
    at __puppeteer_evaluation_script__:1:269623
    at Array.map (<anonymous>)
    at window.<computed>.<computed> [as getAllUnreadMessages] (__puppeteer_evaluation_script__:1:269455)
    at window.<computed>.<computed> [as emitUnreadMessages] (__puppeteer_evaluation_script__:1:174596)
    at __puppeteer_evaluation_script__:1:13
    at ExecutionContext._evaluateInternal (...\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (...\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
```

**Comment by smashah** [comment]
@GladistonXD that's due to new version of wa web

**Comment by smashah** [comment]
@GladistonXD patched

**Comment by GladistonXD** [comment]
Ok thanks for the update :)
