### ISSUE TITLE
Cannot read properties of null (reading 'arrayBuffer')

### ISSUE THREAD

**Issue by DaruinHerrera** [open-wa/wa-automate-nodejs#2732]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

When trying to get the chats with messages I get this problem

Error: Evaluation failed: TypeError: Cannot read properties of null (reading 'arrayBuffer')
    at window.<computed>.<computed> (__puppeteer_evaluation_script__:1:184876)
    at ExecutionContext._evaluateInternal (C:\Proyectos\apiWhatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\Proyectos\apiWhatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)

### Expected Behavior

Get all chats with messages

### Steps To Reproduce

1. start client and then call the function
2. client.getAllChatsWithMessages(false)
    .then(response => {
        console.log(response)
    })
    .catch(error => {
        console.log(error)
    })

### create() code OR full CLI command + CONFIG

```markdown
client.getAllChatsWithMessages(false)
    .then(response => {
        console.log(response)
    })
    .catch(error => {
        console.log(error)
    })
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2218.8",
  "WA_AUTOMATE_VERSION": "4.37.2 UPDATE AVAILABLE: 4.37.5",
  "BROWSER_VERSION": "HeadlessChrome/101.0.4950.0",
  "START_TS": 1654522880060,
  "RAM_INFO": "Total: 17.05 GB | Free: 9.63 GB",
  "PPTR_VERSION": "UNKNOWN",
  "LATEST_VERSION": false,
  "CLI": false,
  "PATCH_HASH": "84227",
  "LAUNCH_TIME_MS": 17219,
  "ACC_TYPE": "PERSONAL",
  "chats": 75,
  "messages": 250,
  "contacts": 585,
  "isMd": true,
  "INSTANCE_ID": "f63e7aa6-b025-4cca-8529-685fbe5abb2e"
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 16.15.1
- npm: 8.11.0
```

### Screenshots/Logs

Error: Evaluation failed: TypeError: Cannot read properties of null (reading 'arrayBuffer')
    at window.<computed>.<computed> (__puppeteer_evaluation_script__:1:184876)
    at ExecutionContext._evaluateInternal (C:\Proyectos\apiWhatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)    at async ExecutionContext.evaluate (C:\Proyectos\apiWhatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)

**Comment by smashah** [comment]
@DaruinHerrera error should be bypassed via a patched. please restart and try again.

**Comment by DaruinHerrera** [comment]
Thanks, the problem is because the function is already obsolete, I made and use the one suggested in the manual and it worked, thanks
