### ISSUE TITLE
Error Lauch easyApi on AWS EC2 running ubuntu 22.04

### ISSUE THREAD

**Issue by scropion86** [open-wa/wa-automate-nodejs#2753]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Tested and experienced on both

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

i run `npx @open-wa/wa-automate -p 8080`

Server is not starting and show below error

```
✓ Version: 4.41.1
Error: Failed to launch the browser process!
/home/ubuntu/node_modules/puppeteer/.local-chromium/linux-1002410/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/ubuntu/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:286:20)
    at Interface.<anonymous> (/home/ubuntu/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:274:24)
    at Interface.emit (node:events:549:35)
    at Interface.close (node:internal/readline/interface:536:10)
    at Socket.onend (node:internal/readline/interface:262:10)
    at Socket.emit (node:events:549:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
✖ Error Failed to launch the browser process!
/home/ubuntu/node_modules/puppeteer/.local-chromium/linux-1002410/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
 Error: Failed to launch the browser process!
/home/ubuntu/node_modules/puppeteer/.local-chromium/linux-1002410/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

```

### Expected Behavior

should work fine and listen to port 8080

### Steps To Reproduce

run `npx @open-wa/wa-automate -p 8080`

### DEBUG INFO

```markdown
N/A
```

### Environment

```markdown
- OS: Ubuntu 22.04
- Node: v18.4.0
- npm: 8.12.2
```

### Screenshots/Logs

ubuntu@ip-172-31-46-197:~$ npx @open-wa/wa-automate -p 8080
✓ Postman collection generated: open-wa-session.postman_collection.json
✓ API collections (swagger + postman) generated successfully

        ____/\\\\\\\\\\__________/\\\\\_______/\\\\\\\\\\\\\___
         __/\\\////////\\\______/\\\///\\\____\/\\\/////////\\\_
          _\/\\\__/\\\\\\\\\___/\\\/__\///\\\__\/\\\_______\/\\\_
           _\/\\\_\/\\\///\\\__/\\\______\//\\\_\/\\\\\\\\\\\\\/__
            _\/\\\_\/\\\\\\\\__\/\\\_______\/\\\_\/\\\/////////____
             _\/\\\_\////////___\//\\\______/\\\__\/\\\_____________
              _\//\\\_____________\///\\\__/\\\____\/\\\_____________
               __\///\\\\\\\\\\\\____\///\\\\\/_____\/\\\_____________
                ____\////////////_______\/////_______\///______________

           __/\\\\\\\\\\\\\\\__/\\\\\_____/\\\_______________
            _\/\\\///////////__\/\\\\\\___\/\\\_______________
             _\/\\\_____________\/\\\/\\\__\/\\\_______________
              _\/\\\\\\\\\\\_____\/\\\//\\\_\/\\\__/\\\\\\\\\\\_
               _\/\\\///////______\/\\\\//\\\\/\\\_\///////////__
                _\/\\\_____________\/\\\_\//\\\/\\\_______________
                 _\/\\\_____________\/\\\__\//\\\\\\_______________
                  _\/\\\\\\\\\\\\\\\_\/\\\___\//\\\\\_______________
                   _\///////////////__\///_____\/////________________

              __/\\\______________/\\\_____/\\\\\\\\\____
               _\/\\\_____________\/\\\___/\\\\\\\\\\\\\__
                _\/\\\_____________\/\\\__/\\\/////////\\\_
                 _\//\\\____/\\\____/\\\__\/\\\_______\/\\\_
                  __\//\\\__/\\\\\__/\\\___\/\\\\\\\\\\\\\\\_
                   ___\//\\\/\\\/\\\/\\\____\/\\\/////////\\\_
                    ____\//\\\\\\//\\\\\_____\/\\\_______\/\\\_
                     _____\//\\\__\//\\\______\/\\\_______\/\\\_
                      ______\///____\///_______\///________\///__

     __/\\\______________/\\\__/\\\________/\\\_____/\\\\\\\\\____
      _\/\\\_____________\/\\\_\/\\\_______\/\\\___/\\\\\\\\\\\\\__
       _\/\\\_____________\/\\\_\/\\\_______\/\\\__/\\\/////////\\\_
        _\//\\\____/\\\____/\\\__\/\\\\\\\\\\\\\\\_\/\\\_______\/\\\_
         __\//\\\__/\\\\\__/\\\___\/\\\/////////\\\_\/\\\\\\\\\\\\\\\_
          ___\//\\\/\\\/\\\/\\\____\/\\\_______\/\\\_\/\\\/////////\\\_
           ____\//\\\\\\//\\\\\_____\/\\\_______\/\\\_\/\\\_______\/\\\_
            _____\//\\\__\//\\\______\/\\\_______\/\\\_\/\\\_______\/\\\_
             ______\///____\///_______\///________\///__\///________\///__

        __/\\\\\\\\\\\\\\\_____/\\\\\\\\\\\_______/\\\\\\\\\____
         _\///////\\\/////____/\\\/////////\\\___/\\\\\\\\\\\\\__
          _______\/\\\________\//\\\______\///___/\\\/////////\\\_
           _______\/\\\_________\////\\\_________\/\\\_______\/\\\_
            _______\/\\\____________\////\\\______\/\\\\\\\\\\\\\\\_
             _______\/\\\_______________\////\\\___\/\\\/////////\\\_
              _______\/\\\________/\\\______\//\\\__\/\\\_______\/\\\_
               _______\/\\\_______\///\\\\\\\\\\\/___\/\\\_______\/\\\_
                _______\///__________\///////////_____\///________\///__

                 __/\\\\\\\\\\\\\____/\\\\\\\\\\\\\___
                  _\/\\\/////////\\\_\/\\\/////////\\\_
                   _\/\\\_______\/\\\_\/\\\_______\/\\\_
                    _\/\\\\\\\\\\\\\/__\/\\\\\\\\\\\\\/__
                     _\/\\\/////////____\/\\\/////////____
                      _\/\\\_____________\/\\\_____________
                       _\/\\\_____________\/\\\_____________
                        _\/\\\_____________\/\\\_____________
                         _\///______________\///______________

        _____/\\\\\\\\\_____/\\\________/\\\__/\\\\\\\\\\\\\\\_
         ___/\\\\\\\\\\\\\__\/\\\_______\/\\\_\///////\\\/////__
          __/\\\/////////\\\_\/\\\_______\/\\\_______\/\\\_______
           _\/\\\_______\/\\\_\/\\\_______\/\\\_______\/\\\_______
            _\/\\\\\\\\\\\\\\\_\/\\\_______\/\\\_______\/\\\_______
             _\/\\\/////////\\\_\/\\\_______\/\\\_______\/\\\_______
              _\/\\\_______\/\\\_\//\\\______/\\\________\/\\\_______
               _\/\\\_______\/\\\__\///\\\\\\\\\/_________\/\\\_______
                _\///________\///_____\/////////___________\///________

     _______/\\\\\_______/\\\\____________/\\\\_____/\\\\\\\\\____
      _____/\\\///\\\____\/\\\\\\________/\\\\\\___/\\\\\\\\\\\\\__
       ___/\\\/__\///\\\__\/\\\//\\\____/\\\//\\\__/\\\/////////\\\_
        __/\\\______\//\\\_\/\\\\///\\\/\\\/_\/\\\_\/\\\_______\/\\\_
         _\/\\\_______\/\\\_\/\\\__\///\\\/___\/\\\_\/\\\\\\\\\\\\\\\_
          _\//\\\______/\\\__\/\\\____\///_____\/\\\_\/\\\/////////\\\_
           __\///\\\__/\\\____\/\\\_____________\/\\\_\/\\\_______\/\\\_
            ____\///\\\\\/_____\/\\\_____________\/\\\_\/\\\_______\/\\\_
             ______\/////_______\///______________\///__\///________\///__

        __/\\\\\\\\\\\\\\\_______/\\\\\_________/\\\\\\\\\_____
         _\///////\\\/////______/\\\///\\\_____/\\\///////\\\___
          _______\/\\\_________/\\\/__\///\\\__\/\\\_____\/\\\___
           _______\/\\\________/\\\______\//\\\_\/\\\\\\\\\\\/____
            _______\/\\\_______\/\\\_______\/\\\_\/\\\//////\\\____
             _______\/\\\_______\//\\\______/\\\__\/\\\____\//\\\___
              _______\/\\\________\///\\\__/\\\____\/\\\_____\//\\\__
               _______\/\\\__________\///\\\\\/_____\/\\\______\//\\\_
                _______\///_____________\/////_______\///________\///__

✓ Version: 4.41.1
Error: Failed to launch the browser process!
/home/ubuntu/node_modules/puppeteer/.local-chromium/linux-1002410/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/ubuntu/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:286:20)
    at Interface.<anonymous> (/home/ubuntu/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:274:24)
    at Interface.emit (node:events:549:35)
    at Interface.close (node:internal/readline/interface:536:10)
    at Socket.onend (node:internal/readline/interface:262:10)
    at Socket.emit (node:events:549:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
✖ Error Failed to launch the browser process!
/home/ubuntu/node_modules/puppeteer/.local-chromium/linux-1002410/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
 Error: Failed to launch the browser process!
/home/ubuntu/node_modules/puppeteer/.local-chromium/linux-1002410/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

**Comment by scropion86** [comment]
i have found that puppeteer failing to load chrom for some of missing dependencies as per the [Docs in puppeteer repo](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix)

you need to make sure that your Ubuntu/Debian have all below installed


```
ca-certificates
fonts-liberation
libappindicator3-1
libasound2
libatk-bridge2.0-0
libatk1.0-0
libc6
libcairo2
libcups2
libdbus-1-3
libexpat1
libfontconfig1
libgbm1
libgcc1
libglib2.0-0
libgtk-3-0
libnspr4
libnss3
libpango-1.0-0
libpangocairo-1.0-0
libstdc++6
libx11-6
libx11-xcb1
libxcb1
libxcomposite1
libxcursor1
libxdamage1
libxext6
libxfixes3
libxi6
libxrandr2
libxrender1
libxss1
libxtst6
lsb-release
wget
xdg-utils
```
