### ISSUE TITLE
throwing the error instead of showing error

### ISSUE THREAD

**Issue by dharmendrasha** [open-wa/wa-automate-nodejs#2772]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Legacy (Normal)

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

Capturing the qr code in console.

### Expected Behavior

Should give me the sesson data and allow me to use whats app client

### Steps To Reproduce

Running in to the Docker
Using headless browser
Creating session

### create() code OR full CLI command + CONFIG

```markdown
sessionCreate({
        sessionId,
        multiDevice: false,
        devtools: true,
        safeMode: true,
        disableSpins: true,
        qrTimeout: 0,
        authTimeout: 60,
        popup: parseInt(getEnv('PORT')),
        browserWSEndpoint: getEnv('WA_BROWSER_WS_ENDPOINT'),
        sessionDataPath: '/wa_' + getEnv('WA_SESSION_DATA_PATH', 'session'),
        logConsole: false,
        cacheEnabled: true,
        logDebugInfoAsObject: currentStageIs('DEVELOPMENT')
      }).then(this.client).catch(console.error)
```

### DEBUG INFO

```markdown
{
"WA_VERSION": "2.2222.11",
  "PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
  "WA_AUTOMATE_VERSION": "4.42.2",
  "BROWSER_VERSION": "HeadlessChrome/104.0.5112.20",
  "OS": "Linux 5.10",
  "START_TS": 1656842429598,
  "RAM_INFO": "Total: 8.34 GB | Free: 6.40 GB",
  "PPTR_VERSION": "UNKNOWN"
}
```

### Environment

```markdown
- OS: Alpine
- Node: 18.4.0
- npm: 8.12.1
```

### Anything else?

Follow the logs
```

[03-07-2022 10:00:24.179 +0000] INFO: request completed {"req":{"id":1,"method":"GET","url":"/wa/create?session_id=917597365803","query":{"session_id":"917597365803"},"params":{},"headers":{"user-agent":"PostmanRuntime/7.29.0","accept":"*/*","cache-control":"no-cache","postman-token":"4ac9e2ea-b8bb-47c1-ba9e-40b4d553e07a","host":"0.0.0.0:4000","accept-encoding":"gzip, deflate, br","connection":"keep-alive"},"remoteAddress":"::ffff:172.20.0.1","remotePort":63862},"res":{"statusCode":200,"headers":{"x-powered-by":"Express","access-control-allow-origin":"*","content-type":"text/html; charset=utf-8","content-length":"12","etag":"W/\"c-HRxM4Zyi5e2CZVgCpi/5aGg9WTM\""}},"responseTime":229}
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓┃                                                                              ┃┃   @open-wa/wa-automate                                                       ┃┃   💬 🤖 The most reliable NodeJS whatsapp library for chatbots with          ┃┃   advanced features.                                                         ┃┃   Version: 4.42.2                                                            ┃┃   Check out the latest changes:                                              ┃┃   https://github.com/open-wa/wa-automate-nodejs#latest-changes               ┃┃                                                                              ┃┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
You can also authenticate the session at: http://localhost:7000
- Starting
[03-07-2022 10:00:24.825 +0000] INFO: Session 917597365803 Starting successfully
- Version: 4.42.2
- Initializing WA
[03-07-2022 10:00:24.837 +0000] INFO: Session 917597365803 Version: 4.42.2 successfully
[03-07-2022 10:00:24.845 +0000] INFO: Session 917597365803 Initializing WA successfully
- Launching Browser
[03-07-2022 10:00:24.889 +0000] INFO: Session 917597365803 Launching Browser successfully
-
devtools URL: {
  "user": "dev",
  "pass": "ZRXAY62-JHC46XS-NNQ31CT-97CD6J0",
  "tunnel": "https://devtools-tunnel-pc75yrub9m.loca.lt"
}
[03-07-2022 10:00:27.610 +0000] INFO: Session 917597365803
devtools URL: {
  "user": "dev",
  "pass": "ZRXAY62-JHC46XS-NNQ31CT-97CD6J0",
  "tunnel": "https://devtools-tunnel-pc75yrub9m.loca.lt"
} successfully
- Browser launched: 2732ms
[03-07-2022 10:00:27.625 +0000] INFO: Session 917597365803 Browser launched: 2732ms successfully
- Setting Up Page
[03-07-2022 10:00:27.706 +0000] INFO: Session 917597365803 Setting Up Page successfully
- Loading session data
- Found session data file: /wa_session/917597365803.data.json
- Existing session data detected. Injecting...
[03-07-2022 10:00:27.727 +0000] INFO: Session 917597365803 Loading session data successfully
[03-07-2022 10:00:27.743 +0000] INFO: Session 917597365803 Found session data file: /wa_session/917597365803.data.json successfully
[03-07-2022 10:00:27.751 +0000] INFO: Session 917597365803 Existing session data detected. Injecting... successfully
- Existing session data injected
- Pre page launch setup complete: 68ms
- Navigating to WA
[03-07-2022 10:00:27.766 +0000] INFO: Session 917597365803 Existing session data injected successfully
[03-07-2022 10:00:27.774 +0000] INFO: Session 917597365803 Pre page launch setup complete: 68ms successfully
[03-07-2022 10:00:27.780 +0000] INFO: Session 917597365803 Navigating to WA successfully
- Page loaded in 1651ms: 200
[03-07-2022 10:00:29.441 +0000] INFO: Session 917597365803 Page loaded in 1651ms: 200 successfully
- Page loaded
[03-07-2022 10:00:29.501 +0000] INFO: Session 917597365803 Page loaded successfully
- Debug info: {
  "WA_VERSION": "2.2222.11",
  "PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
  "WA_AUTOMATE_VERSION": "4.42.2",
  "BROWSER_VERSION": "HeadlessChrome/104.0.5112.20",
  "OS": "Linux 5.10",
  "START_TS": 1656842429598,
  "RAM_INFO": "Total: 8.34 GB | Free: 6.40 GB",
  "PPTR_VERSION": "UNKNOWN"
}
[03-07-2022 10:00:29.668 +0000] INFO: Session 917597365803 Debug info: {
  "WA_VERSION": "2.2222.11",
  "PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
  "WA_AUTOMATE_VERSION": "4.42.2",
  "BROWSER_VERSION": "HeadlessChrome/104.0.5112.20",
  "OS": "Linux 5.10",
  "START_TS": 1656842429598,
  "RAM_INFO": "Total: 8.34 GB | Free: 6.40 GB",
  "PPTR_VERSION": "UNKNOWN"
} successfully
- Use this easy pre-filled link to report an issue: https://github.com/open-wa/wa-automate-nodejs/issues/new?template=bug_report.yaml&d_info=%7B%0A%20%20%22WA_VERSION%22:%20%222.2222.11%22,%0A%20%20%22WA_AUTOMATE_VERSION%22:%20%224.42.2%22,%0A%20%20%22BROWSER_VERSION%22:%20%22HeadlessChrome/104.0.5112.20%22,%0A%20%20%22START_TS%22:%201656842429598,%0A%20%20%22RAM_INFO%22:%20%22Total:%208.34%20GB%20%7C%20Free:%206.40%20GB%22,%0A%20%20%22PPTR_VERSION%22:%20%22UNKNOWN%22,%0A%20%20%22LATEST_VERSION%22:%20true,%0A%20%20%22CLI%22:%20false%0A%7D&enviro=-%20OS:%20Linux%205.10%0A-%20Node:%2018.4.0%0A-%20npm:%208.12.1&labels=Legacy
- Time to injection: 2501ms
- Injecting api
- Injecting scripts
[03-07-2022 10:00:32.000 +0000] INFO: Session 917597365803 Use this easy pre-filled link to report an issue: https://github.com/open-wa/wa-automate-nodejs/issues/new?template=bug_report.yaml&d_info=%7B%0A%20%20%22WA_VERSION%22:%20%222.2222.11%22,%0A%20%20%22WA_AUTOMATE_VERSION%22:%20%224.42.2%22,%0A%20%20%22BROWSER_VERSION%22:%20%22HeadlessChrome/104.0.5112.20%22,%0A%20%20%22START_TS%22:%201656842429598,%0A%20%20%22RAM_INFO%22:%20%22Total:%208.34%20GB%20%7C%20Free:%206.40%20GB%22,%0A%20%20%22PPTR_VERSION%22:%20%22UNKNOWN%22,%0A%20%20%22LATEST_VERSION%22:%20true,%0A%20%20%22CLI%22:%20false%0A%7D&enviro=-%20OS:%20Linux%205.10%0A-%20Node:%2018.4.0%0A-%20npm:%208.12.1&labels=Legacy successfully
[03-07-2022 10:00:32.006 +0000] INFO: Session 917597365803 Time to injection: 2501ms successfully
[03-07-2022 10:00:32.012 +0000] INFO: Session 917597365803 Injecting api successfully
[03-07-2022 10:00:32.020 +0000] INFO: Session 917597365803 Injecting scripts successfully
- Base inject: 43ms
[03-07-2022 10:00:32.086 +0000] INFO: Session 917597365803 Base inject: 43ms successfully
- WAPI inject: 106ms
[03-07-2022 10:00:32.226 +0000] INFO: Session 917597365803 WAPI inject: 106ms successfully
- Checking session integrity
[03-07-2022 10:00:32.230 +0000] INFO: Session 917597365803 Checking session integrity successfully
- Session integrity check passed
[03-07-2022 10:00:32.253 +0000] INFO: Session 917597365803 Session integrity check passed successfully
- Launch inject: 193ms
[03-07-2022 10:00:32.450 +0000] INFO: Session 917597365803 Launch inject: 193ms successfully
- WAPI injected
- Authenticating
[03-07-2022 10:00:32.458 +0000] INFO: Session 917597365803 WAPI injected successfully
[03-07-2022 10:00:32.462 +0000] INFO: Session 917597365803 Authenticating successfully
- Authenticate to continue
[03-07-2022 10:00:32.537 +0000] INFO: Session 917597365803 Authenticate to continue successfully
- First QR: 7464 ms
[03-07-2022 10:00:32.650 +0000] INFO: Session 917597365803 First QR: 7464 ms successfully
┌─────────────────────── 917597365803 ────────────────────────┐
│                                                             │
│   ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄   │
│   █ ▄▄▄▄▄ █▄▄▄▄ ▄█ █ ▄▄█▄█▄ ▄▀▀█▀ ▄███▀▀▄██▀  ▀██ ▄▄▄▄▄ █   │
│   █ █   █ █ ▀ ██ ▄█▄ ▀████▄█▀█▀  █▀▄█ ▀ ▀█ █▀▀▄▀█ █   █ █   │
│   █ █▄▄▄█ █▄ ██ █ ▄█▀▄ ▄▀▀█ ▄▄▄ ▀██▄▀█▄█▄▄ ▀▄ ███ █▄▄▄█ █   │
│   █▄▄▄▄▄▄▄█▄▀ ▀ █▄█ █ █ ▀▄▀ █▄█ ▀ ▀▄█▄█▄█▄▀ ▀▄█ █▄▄▄▄▄▄▄█   │
│   █  ▄▄▀▀▄█▄▄█ ▄█▄█ ▄▀▀█▄ ▀▄ ▄ ▄▄ ▀▀▄▄ █▀▄█ ▀  ▄▄██ ▄▄█▄█   │
│   █▄ ▄▄ ▄▄██▄▀▄▄█▀▀▄▀▀▄█▀▀▀█▀█ ▀▀▄█▀█▄▀▄▀  ██▀▄█   █▄▄▄██   │
│   █▀▄ ▀█▄▄▄ ▀▄   █ █ ▄ ▀▀█ █    ▄▄▄▀ █  ▀  █▄▄  ▀█▄▄▀   █   │
│   █ ▀█▀█▄▄ ▀▀▄█▄ █▀ ▄▄ ██ █ █▄▀ ▀ ▄ ▀ ██▄▄▀▀█▄▀███▀ █▄█ █   │
│   █▄█▄█ ▄▄███▀█▀█▄▄▀▀▀██ ▀▀▀ █ █▀██  ▀▀█▄▄▄█ █ █  █▀ █ ▀█   │
│   ██▄▄ ██▄▄██▀▄ █ ██  ▄▄ ▄█▄▄▀▄▀▄▄▄ ▄▄  ▄█▀▀▀ ▄▀██▀▄ ▀▀██   │
│   █▀█   █▄▄██▀▀▄█▀▄█▄██▄▄ █ █▄▀▄▀▀▀▀██ █ █ ▄▀▀█▄██▄▀▄▄█▀█   │
│   █ █ ▀▄▄▄▀▀ ▀▄▀ ▀█▄ ▀█▀ ██▄▄▄ ██   █▄█▄ ▄▀▀ ▀██▀ ▀ █▄▀██   │
│   █▄▄▀▀ ▄▄▄  ▄ █▄  ▀█ ▀▀█▀  ▄▄▄ ▄▄▄██▄▄▄▀ ▀▀▄▄▀ ▄▄▄ ▀ ▄▀█   │
│   ███▀  █▄█ ▄  ██ █▀█ ▀▄▄   █▄█ ▄▀  ▄██▄█ █▀▄▀█ █▄█ ▀▄ ▄█   │
│   █ ▄▄▀  ▄ ▄▄▄█▀ ▄  ▀███ █▀     ▀▄ ▄▀ ▀▀▀▄ ▀██▀ ▄ ▄▄█▀▀██   │
│   █▄ ▀███▄   ▀ ▄▀▀▀  ▄▄▀████▄▀█▄  ▀ ▄█▄ █▄█▀ █ ▄▀█▀ ▀ ▄▀█   │
│   ██▄ ▀██▄▀█▄▀▄▀ █ ▄▀██▄ ▄▀  ▀█▄ ▀▀█▄▄▀█▄▄▀ ▀▀ ▀▄▄█ █▀▀██   │
│   █▀██ █▄▄▀▄  ▀█▄ ▄▀▀███▄▀▄▄██▀ ▄ ▀█▀█▀▀▄▀ █▄▄█ ▀█▀▀▀█▄██   │
│   █   ▀▄▄▄█▀▀ █▄ █ ▄  ▄ █▀██ █ ▄▄▄▄▀ █▀    ▀█▄▀█▀▀█▄▄▄ ██   │
│   █ ▀█▀▄█▄█ ▄▀▄ █ ▄      █▀▀█▀ ██▀▀ █▀ ▄▄ █ ▀▄ ▄  ▀  ▄ ▄█   │
│   █▄▄▀█▄▄▄▄█  ▄▀ █▀█▄█▄▄▀█▄▀▄▄█ ▄▄▀  ▀▄█ ▄▄█ █▀ █ █▄▀▀ ██   │
│   █▄ ▀▄▄▄▄▄ ▄▀▄▀▄▀   ▀▄██▀█ ▀█ ▄▄▀█▄█▀▀▀▄▄▄ █▄▀ ██▄▄▀▀ ██   │
│   ████▄██▄█▀▀▄█▀▀██▄▄█ █    ▄▄▄ ▀▀ ███ ▀▀▄ ▄    ▄▄▄  ▄█▀█   │
│   █ ▄▄▄▄▄ ██▄▄█▄ ▀▄ █ █▀▀█  █▄█  ▄▄▀  █   ▄██   █▄█ ▀▄███   │
│   █ █   █ █▀ ▀ ▄▄███ █  ███▄▄ ▄▄▄▄ ▀ ▄   ▀██▀▄▀▄  ▄▄▄▄ ▄█   │
│   █ █▄▄▄█ █ ▀█ ▀▀█ ▄▀██▀▀▀███▄▀ ▄▄ ▀███▀▀▄█ ▄  ▀▄▄▄▀ █ ██   │
│   █▄▄▄▄▄▄▄█▄█▄▄▄▄▄▄█████▄█████▄████▄▄▄███▄██▄████▄██▄▄▄██   │
│                                                             │
│                                                             │
└─────────────────────────────────────────────────────────────┘
- Multi device support for this project is EXPERIMENTAL. Some things may not work....
[03-07-2022 10:01:29.775 +0000] INFO: Session 917597365803 Multi device support for this project is EXPERIMENTAL. Some things may not work.... successfully
- Injecting scripts
[03-07-2022 10:01:30.020 +0000] INFO: Session 917597365803 Injecting scripts successfully
- Injecting scripts
- Reinjecting api
- Injecting scripts
- Base inject: 34ms
- Base inject: 29ms
[03-07-2022 10:01:30.085 +0000] INFO: Session 917597365803 successfulScan successfully
[03-07-2022 10:01:30.092 +0000] INFO: Session 917597365803 SUCCESS successfully
[03-07-2022 10:01:30.095 +0000] INFO: 917597365803 started!
[03-07-2022 10:01:30.100 +0000] INFO: Session 917597365803 Reinjecting api successfully
[03-07-2022 10:01:30.103 +0000] INFO: Session 917597365803 Injecting scripts successfully
[03-07-2022 10:01:30.168 +0000] INFO: Session 917597365803 Base inject: 34ms successfully
[03-07-2022 10:01:30.171 +0000] INFO: Session 917597365803 Base inject: 29ms successfully
- Launch inject: 216ms
[03-07-2022 10:01:30.419 +0000] INFO: Session 917597365803 Launch inject: 216ms successfully
- Launch inject: 325ms
[03-07-2022 10:01:30.540 +0000] INFO: Session 917597365803 Launch inject: 325ms successfully
- WAPI Reinjected
- Checking if session is valid
[03-07-2022 10:01:30.543 +0000] INFO: Session 917597365803 WAPI Reinjected successfully
[03-07-2022 10:01:30.546 +0000] INFO: Session 917597365803 Checking if session is valid successfully
- Downloading patches from https://cdn.openwa.dev/patches.json
[03-07-2022 10:01:35.647 +0000] INFO: Session 917597365803 Downloading patches from https://cdn.openwa.dev/patches.json successfully
- Client is ready
[03-07-2022 10:01:35.762 +0000] INFO: Session 917597365803 Client is ready successfully
[03-07-2022 10:01:35.780 +0000] INFO: sessionData
[03-07-2022 10:01:35.782 +0000] INFO: sessionData
- Downloaded patches in 0.943s
[03-07-2022 10:01:36.620 +0000] INFO: Session 917597365803 Downloaded patches in 0.943s successfully
- Installing patches
[03-07-2022 10:01:37.515 +0000] INFO: Session 917597365803 Installing patches successfully
- Patches Installed: 8b2fa
[03-07-2022 10:01:37.705 +0000] INFO: Session 917597365803 Patches Installed: 8b2fa successfully
- !!!Please set multiDevice: true in the config or use the --mutli-Device flag!!!
[03-07-2022 10:01:37.851 +0000] INFO: Session 917597365803 !!!Please set multiDevice: true in the config or use the --mutli-Device flag!!! successfully
- Client loaded for normal account [MD] with 2748 contacts, 332 chats & 429 messages in 73.833s
[03-07-2022 10:01:37.853 +0000] INFO: Session 917597365803 Client loaded for normal account [MD] with 2748 contacts, 332 chats & 429 messages in 73.833s successfully
- Finalizing web session...
[03-07-2022 10:01:38.183 +0000] INFO: Session 917597365803 Finalizing web session... successfully
- Finalizing client...
[03-07-2022 10:01:38.308 +0000] INFO: Session 917597365803 Finalizing client... successfully
[03-07-2022 10:01:43.413 +0000] INFO: Session 917597365803 state: TIMEOUT successfully
STATE_ERROR: state: TIMEOUT
    at Client.<anonymous> (/app/node_modules/@open-wa/wa-automate/dist/api/Client.js:457:27)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/@open-wa/wa-automate/dist/api/Client.js:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
STATE_ERROR: state: TIMEOUT
    at Client.<anonymous> (/app/node_modules/@open-wa/wa-automate/dist/api/Client.js:457:27)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/@open-wa/wa-automate/dist/api/Client.js:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by smashah** [comment]
@dharmendrasha please scrub your logs of personal and sensitive information!

Also, your account is now forced into MD mode so please remove `multiDevice: false` from your config.

When accounts are forced onto MD, you can't undo it by setting `multiDevice: false`, it's true by default now. Also, in MD, authentication takes long depending on the number of chats,etc. so please set your `authTimeout` to 120 or more.

You should also delete all your legacy `.data.json` files as they will corrupt your new MD sessions.

The reason this error is being thrown is because your session is in safeMode. set `safeMode: false` or remove the line entirely to prevent this error from being thrown then destroying your session.

The client code should be surrounded by a `try/catch` to handle that error.

I think safeMode is redundant and has bad side effects with MD. I might deprecate it.
