### ISSUE TITLE
Possible crashing after Launch Inject

### ISSUE THREAD

**Issue by christiancuri** [open-wa/wa-automate-nodejs#2786]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Tested and experienced on both

### Mode

My own code

### Steps To Reproduce

1 - Running inside docker
2 - Config
```ts
  let options: wa.ConfigObject = {
    licenseKey: "...",
    throwErrorOnTosBlock: true,
    multiDevice: true | false,
    logConsole: false,

    blockCrashLogs: false,
    useChrome: true,
    disableSpins: true,
    autoRefresh: true,
    killProcessOnBrowserClose: true,
    restartOnCrash: postCreate,
  };
```

### create() code OR full CLI command + CONFIG

```markdown
let options: wa.ConfigObject = {
    licenseKey: "...",
    throwErrorOnTosBlock: true,
    multiDevice: true | false,
    logConsole: false,

    blockCrashLogs: false,
    useChrome: true,
    disableSpins: true,
    autoRefresh: true,
    killProcessOnBrowserClose: true,
    restartOnCrash: postCreate,
  };
```

### DEBUG INFO

```markdown
app_1      | - Injecting scripts
app_1      | - Base inject: 39ms
app_1      | - Launch inject: 44ms
app_1      | - Injecting scripts
app_1      | - Injecting scripts
app_1      | - Injecting scripts
app_1      | - Base inject: 14ms
app_1      | - Base inject: 17ms
app_1      | - Base inject: 16ms
app_1      | - Launch inject: 32ms
app_1      | - Launch inject: 27ms
app_1      | - Launch inject: 35ms
app_1      | - Injecting scripts
app_1      | - Base inject: 6ms
app_1      | - Launch inject: 11ms
app_1      | - QR scan took too long. Session Timed Out. Shutting down. Consider increasing qrTimeout config variable: https://open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#qrtimeout
app_1      | Error: QR Timeout
app_1      |     at Object.<anonymous> (/usr/src/app/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:300:27)
app_1      |     at Generator.next (<anonymous>)
app_1      |     at fulfilled (/usr/src/app/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:24:58)
app_1      | Error: QR Timeout
app_1      |     at Object.<anonymous> (/usr/src/app/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:300:27)
app_1      |     at Generator.next (<anonymous>)
app_1      |     at fulfilled (/usr/src/app/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:24:58)
```

### Environment

```markdown
- OS: Docker node:current-stretch
- Node: v16.15.0
- npm: 8.5.5
```

### Screenshots/Logs

![image](https://user-images.githubusercontent.com/52043761/177618020-8d483a58-1dc9-4436-82c4-af7ef888d2e9.png)

**Comment by smashah** [comment]
The error shows that the qr scan took too long. Set `qrTimeout: 0` in your config to make the session wait forever for a scan. Default is 60.

**Comment by christiancuri** [comment]
I already set, but i scan the qrcode and still throw error
