### ISSUE TITLE
No fount  getAllLabels

### ISSUE THREAD

**Issue by DaruinHerrera** [open-wa/wa-automate-nodejs#2892]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

My own code

### Current Behavior

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'map')
    at window.<computed>.<computed> (__puppeteer_evaluation_script__:1:412503)
    at Array.map (<anonymous>)
    at Object.window.<computed>.<computed> [as getAllLabels] (__puppeteer_evaluation_script__:1:413076)
    at __puppeteer_evaluation_script__:1:13
    at ExecutionContext._evaluateInternal (/www/wwwroot/apiemo.positivo.co/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/www/wwwroot/apiemo.positivo.co/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
GET /api/shops/getAllLabels 200 21.986 ms - 78

### Expected Behavior

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'map')
    at window.<computed>.<computed> (__puppeteer_evaluation_script__:1:412503)
    at Array.map (<anonymous>)
    at Object.window.<computed>.<computed> [as getAllLabels] (__puppeteer_evaluation_script__:1:413076)
    at __puppeteer_evaluation_script__:1:13
    at ExecutionContext._evaluateInternal (/www/wwwroot/apiemo.positivo.co/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/www/wwwroot/apiemo.positivo.co/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
GET /api/shops/getAllLabels 200 14.179 ms - 78

### Steps To Reproduce

const getAllLabels = (whastappPhone) => {
    return new Promise((resolve, reject) => {
        console.log('Buscando label para '+ whastappPhone)
        const client = clientSessionRegistry[whastappPhone+'_sesion'];
        client.getAllLabels('')
        // client.getChatsByLabel('Igniweb')
        .then(res => {
            resolve(res);
        })
        .catch(err => {
            console.log(err);
            reject(err);
        })
    })
}

### DEBUG INFO

```markdown
- Debug info: {⠂⠂⠂⠂) ⠦ : timing config:load:flatten Completed in 3ms
  "WA_VERSION": "2.2234.13",
  "PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
  "WA_AUTOMATE_VERSION": "4.47.0",
  "BROWSER_VERSION": "HeadlessChrome/100.0.4896.75",
  "OS": "Linux 5.4",
  "START_TS": 1663623451820,
  "RAM_INFO": "Total: 1.02 GB | Free: 0.44 GB",
  "PPTR_VERSION": "15.0.0"
}
```

### Environment

```markdown
OS: Ubuntu
npm: 8.11.0
node: v16.15.1
```

### Screenshots/Logs

![1](https://user-images.githubusercontent.com/42453024/191126090-a35b7ed4-95a2-4798-ac44-3f1b40f1813d.png)

**Comment by DaruinHerrera** [comment]
const getAllLabels = (whastappPhone) => {
    return new Promise((resolve, reject) => {
        console.log('Buscando label para '+ whastappPhone)
        const client = clientSessionRegistry[whastappPhone+'_sesion'];
        client.getAllLabels()
        .then(res => {
            console.log(res);
            resolve(res);
        })
        .catch(err => {
            console.log(err);
            reject(err);
        })
    })
}

**Comment by DaruinHerrera** [comment]
solved, thanks
