### ISSUE TITLE
Error: Evaluation failed: Error: wap : addOrRemoveLabels : unsupported

### ISSUE THREAD

**Issue by iGuihP** [open-wa/wa-automate-nodejs#2896]
I'm trying to use addLabel("label", message.from), but the wa-automate returns this:
**(Notes: I am using WhatsApp Business)**

```
Error: Evaluation failed: Error: wap:addOrRemoveLabels:unsupported at Object.addOrRemoveLabels (https://web.whatsapp.com/bootstrap_qr.ff6e73954c8d5881bcf4.js:50:67737)
at window.<computed>.<computed> [as addOrRemoveLabels] (pptr://__puppeteer_evaluation_script__:1:423379)
at pptr://__puppeteer_evaluation_script__:1:30
at ExecutionContext._ExecutionContext_evaluate (/root/api-whatsappautomated/node_modules/puppeteer/src/common/ExecutionContext.ts:279:13)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at ExecutionContext.evaluate (/root/api-whatsapp-automated/node_modules/puppeteer/src/common/ExecutionContext.ts:145:12)
```

**Comment by smashah** [comment]
fixed. please restart and try again
