### ISSUE TITLE
ERROR GET QR

### ISSUE THREAD

**Issue by DaruinHerrera** [open-wa/wa-automate-nodejs#2909]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Legacy (Normal)

### What type of host account are you experiencing this issue on?

Business account

### Mode

My own code

### Current Behavior

TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r901912 is guaranteed to work.
    at Timeout.onTimeout (/www/wwwroot/apiemo.positivo.co/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:208:20)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
- Please delete the ./_IGNORE_573174796864_sesion folder and any related data.json files and try again. It is highly suggested to set useChrome: true also.

### Expected Behavior

TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r901912 is guaranteed to work.
    at Timeout.onTimeout (/www/wwwroot/apiemo.positivo.co/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:208:20)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
- Please delete the ./_IGNORE_573174796864_sesion folder and any related data.json files and try again. It is highly suggested to set useChrome: true also.

### Steps To Reproduce

1. qr request is sent
2. Generate the error

### create() code OR full CLI command + CONFIG

```markdown
GEt qr

TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r901912 is guaranteed to work.
    at Timeout.onTimeout (/www/wwwroot/apiemo.positivo.co/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:208:20)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
- Please delete the ./_IGNORE_573174796864_sesion folder and any related data.json files and try again. It is highly suggested to set useChrome: true also.
```

### DEBUG INFO

```markdown
Version: 4.47.1
```

### Environment

```markdown
- OS: Ubuntu 20.04.3 LTS(Py3.7.9)
- Node: v16.17.1
- npm: 8.19.2
```

### Screenshots/Logs

TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r901912 is guaranteed to work.
    at Timeout.onTimeout (/www/wwwroot/apiemo.positivo.co/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:208:20)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
- Please delete the ./_IGNORE_573174796864_sesion folder and any related data.json files and try again. It is highly suggested to set useChrome: true also.

### Anything else?

TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r901912 is guaranteed to work.
    at Timeout.onTimeout (/www/wwwroot/apiemo.positivo.co/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:208:20)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
- Please delete the ./_IGNORE_573174796864_sesion folder and any related data.json files and try again. It is highly suggested to set useChrome: true also.

**Comment by smashah** [comment]
@DaruinHerrera you need to update chrome

```
> sudo apt update -y && sudo apt upgrade -y
```

**Comment by DaruinHerrera** [comment]
Error: Failed to launch the browser process!flatten Completed in 4ms
mkdir: cannot create directory ‘/root’: Permission denied
touch: cannot touch '/root/.local/share/applications/mimeapps.list': Permission denied
[1013/123251.455549:ERROR:filesystem_posix.cc(63)] mkdir /tmp/Crashpad/new: Permission denied (13)
[1013/123251.455926:ERROR:socket.cc(120)] recvmsg: Connection reset by peer (104)


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/www/wwwroot/apiemo.positivo.co/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:197:20)
    at ChildProcess.<anonymous> (/www/wwwroot/apiemo.positivo.co/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:188:79)
    at ChildProcess.emit (node:events:525:35)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
----------------------Error en la función wa.create------------------------
Error: Failed to launch the browser process!
mkdir: cannot create directory ‘/root’: Permission denied
touch: cannot touch '/root/.local/share/applications/mimeapps.list': Permission denied
[1013/123251.455549:ERROR:filesystem_posix.cc(63)] mkdir /tmp/Crashpad/new: Permission denied (13)
[1013/123251.455926:ERROR:socket.cc(120)] recvmsg: Connection reset by peer (104)


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/www/wwwroot/apiemo.positivo.co/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:197:20)
    at ChildProcess.<anonymous> (/www/wwwroot/apiemo.positivo.co/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:188:79)
    at ChildProcess.emit (node:events:525:35)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)

**Comment by DaruinHerrera** [comment]
It generates this error for me

[apiemo] [2022-10-18 14:37:58] Error
[apiemo] [2022-10-18 14:37:58]     at new LauncherError (/workspace/node_modules/chrome-launcher/dist/utils.js:26:22)
[apiemo] [2022-10-18 14:37:58]     at new ChromePathNotSetError (/workspace/node_modules/chrome-launcher/dist/utils.js:33:9)
[apiemo] [2022-10-18 14:37:58]     at Object.linux (/workspace/node_modules/chrome-launcher/dist/chrome-finder.js:128:15)
[apiemo] [2022-10-18 14:37:58]     at Function.getInstallations (/workspace/node_modules/chrome-launcher/dist/chrome-launcher.js:130:51)
[apiemo] [2022-10-18 14:37:58]     at /workspace/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:416:65
[apiemo] [2022-10-18 14:37:58]     at Generator.next (<anonymous>)
[apiemo] [2022-10-18 14:37:58]     at fulfilled (/workspace/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:24:58)
[apiemo] [2022-10-18 14:37:58]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[apiemo] [2022-10-18 14:37:58] ----------------------Error en la función wa.create------------------------
[apiemo] [2022-10-18 14:37:58] ChromePathNotSetError
[apiemo] [2022-10-18 14:37:58]     at new LauncherError (/workspace/node_modules/chrome-launcher/dist/utils.js:26:22)
[apiemo] [2022-10-18 14:37:58]     at new ChromePathNotSetError (/workspace/node_modules/chrome-launcher/dist/utils.js:33:9)
[apiemo] [2022-10-18 14:37:58]     at Object.linux (/workspace/node_modules/chrome-launcher/dist/chrome-finder.js:128:15)
[apiemo] [2022-10-18 14:37:58]     at Function.getInstallations (/workspace/node_modules/chrome-launcher/dist/chrome-launcher.js:130:51)
[apiemo] [2022-10-18 14:37:58]     at /workspace/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:416:65
[apiemo] [2022-10-18 14:37:58]     at Generator.next (<anonymous>)
[apiemo] [2022-10-18 14:37:58]     at fulfilled (/workspace/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:24:58)
[apiemo] [2022-10-18 14:37:58]     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[apiemo] [2022-10-18 14:37:58]   message: 'The CHROME_PATH environment variable must be set to a Chrome/Chromium executable no older than Chrome stable.',
[apiemo] [2022-10-18 14:37:58]   code: 'ERR_LAUNCHER_PATH_NOT_SET'
[apiemo] [2022-10-18 14:37:58] }

**Comment by DaruinHerrera** [comment]
Error
    at new LauncherError (/home/187120.cloudwaysapps.com/awweujewsj/public_html/node_modules/chrome-launcher/dist/utils.js:26:22)
    at new ChromePathNotSetError (/home/187120.cloudwaysapps.com/awweujewsj/public_html/node_modules/chrome-launcher/dist/utils.js:33:9)
    at Object.linux (/home/187120.cloudwaysapps.com/awweujewsj/public_html/node_modules/chrome-launcher/dist/chrome-finder.js:128:15)
    at Function.getInstallations (/home/187120.cloudwaysapps.com/awweujewsj/public_html/node_modules/chrome-launcher/dist/chrome-launcher.js:130:51)
    at /home/187120.cloudwaysapps.com/awweujewsj/public_html/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:416:65
    at Generator.next (<anonymous>)
    at fulfilled (/home/187120.cloudwaysapps.com/awweujewsj/public_html/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by smashah** [comment]
@DaruinHerrera this is a Ubuntu permission error. Make sure your node user has access to chrome directory path

**Comment by thoriqazzikraa** [comment]
> Error at new LauncherError (/home/187120.cloudwaysapps.com/awweujewsj/public_html/node_modules/chrome-launcher/dist/utils.js:26:22) at new ChromePathNotSetError (/home/187120.cloudwaysapps.com/awweujewsj/public_html/node_modules/chrome-launcher/dist/utils.js:33:9) at Object.linux (/home/187120.cloudwaysapps.com/awweujewsj/public_html/node_modules/chrome-launcher/dist/chrome-finder.js:128:15) at Function.getInstallations (/home/187120.cloudwaysapps.com/awweujewsj/public_html/node_modules/chrome-launcher/dist/chrome-launcher.js:130:51) at /home/187120.cloudwaysapps.com/awweujewsj/public_html/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:416:65 at Generator.next () at fulfilled (/home/187120.cloudwaysapps.com/awweujewsj/public_html/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:24:58) at processTicksAndRejections (node:internal/process/task_queues:96:5)

```
> wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
> sudo apt install ./google-chrome-stable_current_amd64.deb
```
