### ISSUE TITLE
HealthCheck fail after some time

### ISSUE THREAD

**Issue by fukumori** [open-wa/wa-automate-nodejs#2922]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

After some time running EASY API this behavior happens:

Oct 21 10:41:44 [1389]: info: reviving page from dumb cache {"timestamp":"2022-10-21T13:41:44.580Z"}
Oct 21 10:41:44 [1389]: info: FRAME NAV, https://web.whatsapp.com/, false {"timestamp":"2022-10-21T13:41:44.663Z"}
Oct 21 10:41:44 [1389]: info: MDLWR - healthCheck : [] {"timestamp":"2022-10-21T13:41:44.744Z"}
Oct 21 10:41:44 [1389]: middleware -> error Error: Evaluation failed: ReferenceError: WAPI is not defined
Oct 21 10:41:44 [1389]:     at pptr://__puppeteer_evaluation_script__:1:13
Oct 21 10:41:44 [1389]:     at ExecutionContext._ExecutionContext_evaluate (/root/wa-automate/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:286:15)
Oct 21 10:41:44 [1389]:     at runMicrotasks (<anonymous>)
Oct 21 10:41:44 [1389]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Oct 21 10:41:44 [1389]:     at async ExecutionContext.evaluate (/root/wa-automate/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:117:16)
Oct 21 10:41:56 [1389]: info: FRAME NAV, https://web.whatsapp.com/, webpackChunkwhatsapp_web_client {"timestamp":"2022-10-21T13:41:56.715Z"}
Oct 21 10:41:56 [1389]: - Injecting scripts
Oct 21 10:41:56 [1389]: info: Injecting scripts  {"data":"Injecting scripts","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-10-21T13:41:56.718Z"}
Oct 21 10:41:56 [1389]: info: GET SCRIPT: jsSha.min.js 8982 {"timestamp":"2022-10-21T13:41:56.766Z"}
Oct 21 10:41:56 [1389]: info: GET SCRIPT: qr.min.js 18603 {"timestamp":"2022-10-21T13:41:56.766Z"}
Oct 21 10:41:56 [1389]: info: GET SCRIPT: base64.js 4173 {"timestamp":"2022-10-21T13:41:56.766Z"}
Oct 21 10:41:56 [1389]: info: GET SCRIPT: hash.js 34983 {"timestamp":"2022-10-21T13:41:56.766Z"}
Oct 21 10:41:56 [1389]: - Base inject: 17ms
Oct 21 10:41:56 [1389]: info: Base inject: 17ms  {"data":"Base inject: 17ms","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-10-21T13:41:56.784Z"}
Oct 21 10:41:56 [1389]: info: WAPI CHECK: false {"timestamp":"2022-10-21T13:41:56.810Z"}
Oct 21 10:41:56 [1389]: info: GET SCRIPT: wapi.js 79911 {"timestamp":"2022-10-21T13:41:56.810Z"}
Oct 21 10:41:56 [1389]: - WAPI inject: 125ms
Oct 21 10:41:56 [1389]: info: WAPI inject: 125ms  {"data":"WAPI inject: 125ms","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-10-21T13:41:56.936Z"}
Oct 21 10:41:56 [1389]: - Checking session integrity
Oct 21 10:41:56 [1389]: info: Checking session integrity  {"data":"Checking session integrity","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-10-21T13:41:56.937Z"}
Oct 21 10:41:57 [1389]: - Session integrity check passed
...
Oct 21 10:43:26 [1389]: info: MDLWR - healthCheck : {} {"timestamp":"2022-10-21T13:43:26.277Z"}
Oct 21 10:43:26 [1389]: middleware -> error Error: Evaluation failed: TypeError: WAPI.healthCheck is not a function
Oct 21 10:43:26 [1389]:     at pptr://__puppeteer_evaluation_script__:1:13
Oct 21 10:43:26 [1389]:     at ExecutionContext._ExecutionContext_evaluate (/root/wa-automate/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:286:15)
Oct 21 10:43:26 [1389]:     at runMicrotasks (<anonymous>)
Oct 21 10:43:26 [1389]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Oct 21 10:43:26 [1389]:     at async ExecutionContext.evaluate (/root/wa-automate/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:117:16)

### Expected Behavior

Session works after load some scripts.

### Steps To Reproduce

start EASYAPI, Run healthcheck every 3min, sometimes fail with this log above.

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2240.7",
  "WA_AUTOMATE_VERSION": "4.47.4",
  "BROWSER_VERSION": "HeadlessChrome/106.0.5249.119",
  "START_TS": 1666359818558,
  "RAM_INFO": "Total: 4.11 GB | Free: 3.59 GB",
  "PPTR_VERSION": "15.0.0",
  "LATEST_VERSION": true,
  "CLI": true,
  "PATCH_HASH": "cac08",
  "LAUNCH_TIME_MS": 23187,
  "ACC_TYPE": "PERSONAL",
  "chats": 93,
  "messages": 344,
  "contacts": 9760,
  "isMd": true,
  "INSTANCE_ID": "4e7578a5-f0b2-42e4-ac5f-9f9e651d900c"
}
```

### Environment

```markdown
- OS: Linux 5.15
- Node: 16.18.0
- npm: 8.19.2
```

**Comment by smashah** [comment]
patched thanks

**Comment by fukumori** [comment]
Hey @smashah , getting error again on healthCheck. WAVersion: 4.52.0  | Patch: c26a7
Return {"error":"unauthorised"}
Client without license.

**Comment by smashah** [comment]
@fukumori are u using the API?
