### ISSUE TITLE
startup error latetst update

### ISSUE THREAD

**Issue by aymenitc** [open-wa/wa-automate-nodejs#2936]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

when starting the session I get this error after patches installed

```
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'mdOptedIn')
    at window.<computed> (pptr://__puppeteer_evaluation_script__:1:96687)
    at window.<computed>.<computed> [as launchMetrics] (pptr://__puppeteer_evaluation_script__:1:352012)
    at pptr://__puppeteer_evaluation_script__:1:23
    at ExecutionContext._ExecutionContext_evaluate (/home/aymenitc/whatsapp-bot/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:228:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/home/aymenitc/whatsapp-bot/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
Error while terminating browser PID. You can just ignore this, as the process has most likely been terminated successfully already: kill ESRCH
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'mdOptedIn')
    at window.<computed> (pptr://__puppeteer_evaluation_script__:1:96687)
    at window.<computed>.<computed> [as launchMetrics] (pptr://__puppeteer_evaluation_script__:1:352012)
    at pptr://__puppeteer_evaluation_script__:1:23
    at ExecutionContext._ExecutionContext_evaluate (/home/aymenitc/whatsapp-bot/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:228:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/home/aymenitc/whatsapp-bot/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
```

### Steps To Reproduce

npm start

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2242.5",
  "WA_AUTOMATE_VERSION": "4.49.1",
  "BROWSER_VERSION": "HeadlessChrome/106.0.5249.119",
  "START_TS": 1667390142125,
  "RAM_INFO": "Total: 4.08 GB | Free: 2.48 GB",
  "PPTR_VERSION": "15.0.0",
  "LATEST_VERSION": true,
  "CLI": false
}
```

### Environment

```markdown
- OS: Linux 5.15
- Node: 16.17.0
- npm: 8.1.0
```

**Comment by aymenitc** [comment]
it is starting normally now, after I deleted session and IGNORE files.
