### ISSUE TITLE
Crashing randomly at start: Cannot read property 'removeParticipants' of undefined

### ISSUE THREAD

**Issue by feliperaul** [open-wa/wa-automate-nodejs#299]
**Describe the bug**
Whatsapp Web crashes as soon as it starts, randomly.
I don't even use the `removeParticipants` in my Application, so I'm pretty sure it's not my code causing this.

Here's the log that gets echoed in node:

```
✔ Initializing whatsapp
┌─────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│       (index)       │                                                                   Values                                                                    │
├─────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│     WA_VERSION      │                                                                 '2.2013.7'                                                                  │
│       PAGE_UA       │ 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                  '1.8.48'                                                                   │
│   BROWSER_VERSION   │                                                           'Chrome/80.0.3987.163'                                                            │
└─────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
✔ Authenticated
✔ WAPI Reinjected
✔ Whatsapp is ready
(node:73323) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'removeParticipants' of undefined
    at eval (eval at <anonymous> (:3:40), <anonymous>:1:20)
    at __puppeteer_evaluation_script__:3:40
    at Array.filter (<anonymous>)
    at __puppeteer_evaluation_script__:2:46
    at ExecutionContext._evaluateInternal (project_folder/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (project_folder/node_modules/puppeteer/lib/ExecutionContext.js:48:12)
  -- ASYNC --
    at ExecutionContext.<anonymous> (project_folder/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.evaluate (project_folder/node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at Frame.<anonymous> (project_folder/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.evaluate (project_folder/node_modules/puppeteer/lib/Page.js:860:43)
    at Page.<anonymous> (project_folder/node_modules/puppeteer/lib/helper.js:112:23)
    at Object.<anonymous> (project_folder/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:230:39)
    at step (project_folder/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:44:23)
    at Object.next (project_folder/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:25:53)
    at fulfilled (project_folder/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:73323) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:73323) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**create() code**
```javascript
const client = await wa.create(
    `session_123`,
{
    headless: false,
    defaultViewport: false,
    args: ['--start-maximized', '--window-size=1920,1080' ]
  },
  );
```

**Expected behavior**
It shouldn't crash.

**DEBUG INFO**

```
┌─────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│       (index)       │                                                                   Values                                                                    │
├─────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│     WA_VERSION      │                                                                 '2.2013.7'                                                                  │
│       PAGE_UA       │ 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                  '1.8.48'                                                                   │
│   BROWSER_VERSION   │                                                           'Chrome/80.0.3987.163'                                                            │
└─────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Host (please complete the following information):**
MacOs / iPhone

**Comment by ozkcs** [comment]
for me too bro, and btw the sendTextWithMentions for me is broken

**Comment by smashah** [comment]
That's a weird problem.

So this is happening because it can't find the Participants tools. This is happening during the broken methods check (where it checks if anything is broken so you can report back here to make an issue). I have the same version of Whatsapp web but it's working fine.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.49](https://github.com/open-wa/wa-automate-nodejs/compare/1.8.48...1.8.49) (2020-04-11)

- removed old create style from readme resolves #212 [`#212`](https://github.com/open-wa/wa-automate-nodejs/issues/212)
- Release 1.8.49 [`ed3d77a`](https://github.com/open-wa/wa-automate-nodejs/commit/ed3d77ae30bfb2e65e2c8c959f511abb3efcb3a5)
- more advanced method checker and implemented `skipBrokenMethodsCheck` #299 [`ac5f815`](https://github.com/open-wa/wa-automate-nodejs/commit/ac5f815a92f4106771594eae0288e5ba92917bf5)
- typo fix [`1ba7e60`](https://github.com/open-wa/wa-automate-nodejs/commit/1ba7e607741f6b80ba5f79bd70817546678de1d9)

**Comment by smashah** [comment]
@feliperaul Try the new version and if it still shows an error you can now add the following flag to skip the health check.

```javascript
create({
...
skipBrokenMethodsCheck: true,
...
})
```

Let me know if that worked for you.

Thanks

**Comment by feliperaul** [comment]
Couldn't reproduce any crash since I upgraded to 1.8.49. Will report back if it happens again. Thanks!
