### ISSUE TITLE
(Evaluation failed) setGroupToAdminsOnly

### ISSUE THREAD

**Issue by t0g3pii** [open-wa/wa-automate-nodejs#3022]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Tested and experienced on both

### Mode

EASY API/CLI

### Current Behavior

```
/home/ookami/OOKAMI/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229
        throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));
              ^

Error: Evaluation failed: TypeError: mmrrf(...) is not a function
    at window.<computed>.<computed> [as setGroupToAdminsOnly] (eval at <anonymous> (:1:10), <anonymous>:1:19478)
    at pptr://__puppeteer_evaluation_script__:1:36
    at ExecutionContext._ExecutionContext_evaluate (/home/ookami/OOKAMI/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/home/ookami/OOKAMI/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)
```

Node.js v18.7.0

### Steps To Reproduce

await client.setGroupToAdminsOnly(from, true)

### create() code OR full CLI command + CONFIG

```markdown
create({
        "licenseKey": lic,
        "headless": true,
        "cacheEnabled": true,
        "useChrome": true,
        "restartOnCrash": startServer,
        "qrTimeout": 0,
        "authTimeout": 120,
        "sessionId": hosts[i], // sessionId from args
        "sessionDataPath": '../Sessions',
        "multiDevice": true,
        "cachedPatch": false,
        "skipBrokenMethodsCheck": false,
        "blockAssets": false,
        "skipUpdateCheck": false,
        "discord": "907573119433187329",
        //     "debug": true,
        //     "disableSpins":true,
        //     "logging": [{
        //       "type": "console"
        //     }],
        "logConsoleErrors": true
    })
```

### DEBUG INFO

```markdown
│     WA_VERSION      │                                                                 '2.2301.6'                                                                 │
│       PAGE_UA       │ 'WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                  '4.55.0'                                                                  │
│   BROWSER_VERSION   │                                                       'HeadlessChrome/109.0.5414.74'                                                       │
│         OS          │                                                                'Linux 5.19'                                                                │
│      START_TS       │                                                               1674184789826                                                                │
│      RAM_INFO       │                                                     'Total: 33.66 GB | Free: 28.80 GB'                                                     │
│    PPTR_VERSION     │                                                                  '19.5.2'
```

### Environment

```markdown
- OS: Ubuntu Server 22.10
- Node:  v18.7.0
```

**Comment by smashah** [comment]
only an issue with license. should be working now
