### ISSUE TITLE
[Bug] cannot read deprecatedMms3Url using deleteMessage

### ISSUE THREAD

**Issue by t0g3pii** [open-wa/wa-automate-nodejs#3029]
Code: 
```Javascript
var msgsInGroup = await client.getAllMessagesInChat(from, true, false)
    if(mentionedJidList.length >= 1) {
        var counter = 0;
        for(var i = 0; i < msgsInGroup.length; i++) {
            if(msgsInGroup[i].sender.id == mentionedJidList[0]) {
                try {
                    // Error occuring here with some stickers, idk why
                    client.deleteMessage(from, msgsInGroup[i].id, false)
                    counter++;
                } catch(err) {
                    // Konnte ID nicht bekommen
                }
            }
        }
        client.sendTextWithMentions(from, `Es wurden ${counter} Nachrichten von @${mentionedJidList[0]} gelöscht.\nInsgesamt wurden ${msgsInGroup.length} Nachrichten gefunden in der Gruppe.`)
} 
```
Error:
```
0|index  | Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'deprecatedMms3Url')
0|index  |     at pptr://__puppeteer_evaluation_script__:1:451262
0|index  |     at Array.find (<anonymous>)
0|index  |     at window.<computed>.<computed> [as getStickerDecryptable] (pptr://__puppeteer_evaluation_script__:1:451236)
0|index  |     at window.<computed>.<computed> (pptr://__puppeteer_evaluation_script__:1:210946)
0|index  |     at ExecutionContext._ExecutionContext_evaluate (/home/ookami/OOKAMI/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229:15)
0|index  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0|index  |     at async ExecutionContext.evaluate (/home/ookami/OOKAMI/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)
```

![image](https://user-images.githubusercontent.com/49153387/214596919-fae2ce9e-015f-4ee0-a5dd-aa24f303006d.png)

**Comment by t0g3pii** [comment]
//edit: not sure if the error occurs only on stickers...
used the purge command now on someone else who didnt send any Stickers, got the same issue (maybe its in the getAllMessagesInChat?)

**Comment by smashah** [comment]
should be patched
