### ISSUE TITLE
Error: Evaluation failed: Error: update chat table failed

### ISSUE THREAD

**Issue by tmsbrasil** [open-wa/wa-automate-nodejs#3042]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

My own code

### Current Behavior

When I send a message in sequence to more than one contact, the error appears:

Erro ao enviar mensagem para: 556499990474@c.us erro: Error: Evaluation failed: Error: update chat table failed
    at https://web.whatsapp.com/app.ef9c57efcabd52e9f4d3.js:72:934580
    at W (https://web.whatsapp.com/app.ef9c57efcabd52e9f4d3.js:5:140550)
    at MutationObserver.B (https://web.whatsapp.com/app.ef9c57efcabd52e9f4d3.js:5:137127)

### Expected Behavior

send the message successfully

### Steps To Reproduce

`                        await client.sendText(chat.id, message)
                        .then(async(MessageId) => {
                          //SAVE LOG OF MESSAGE SENT
                          const log = {
                              broadcastMessageId: broadMessage.id,
                              leadId: leadId,
                              waChatId: chat.id,
                              waMessageId: MessageId,
                              logType: "SENT"
                          }
                    
                          const logSaved = await saveLog(log, chat, sess, sessionWPPName);
                          
                        })
                        .catch(err => console.log('Erro ao enviar mensagem para: ' + chat.id + ' erro: ' + err))`

### create() code OR full CLI command + CONFIG

```markdown
info: Waiting for internal QR renderer to load {"timestamp":"2023-02-09T17:00:50.591Z"}
info: Internal QR renderer loaded in 12 ms {"timestamp":"2023-02-09T17:00:50.603Z"}
info: AUTH.session  {"data":true,"eventName":"AUTH.session","eventNamespace":"AUTH","sessionId":"session","timestamp":"2023-02-09T17:01:22.527Z"}
info: AUTH.session  {"data":true,"eventName":"AUTH.session","eventNamespace":"AUTH","sessionId":"session","timestamp":"2023-02-09T17:01:22.530Z"}
info: AUTH.session  {"data":true,"eventName":"AUTH.session","eventNamespace":"AUTH","sessionId":"session","timestamp":"2023-02-09T17:01:22.531Z"}
info: AUTH.session  {"data":true,"eventName":"AUTH.session","eventNamespace":"AUTH","sessionId":"session","timestamp":"2023-02-09T17:01:22.534Z"}
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2305.7",
  "WA_AUTOMATE_VERSION": "4.55.2",
  "BROWSER_VERSION": "HeadlessChrome/109.0.5414.74",
  "START_TS": 1675961268115,
  "RAM_INFO": "Total: 4.14 GB | Free: 2.30 GB",
  "PPTR_VERSION": "19.6.2",
  "LATEST_VERSION": true,
  "CLI": false,
  "PATCH_HASH": "1c74d",
  "LAUNCH_TIME_MS": 78587,
  "ACC_TYPE": "BUSINESS",
  "chats": 1013,
  "messages": 1175,
  "contacts": 21963,
  "isBiz": true,
  "isMd": true,
  "INSTANCE_ID": "9e349711-3f30-42ae-9661-b1be02c87468"
}
```

### Environment

```markdown
- OS: Linux 4.15
- Node: 16.18.1
- npm: 8.19.2
```

**Comment by CarlosAurelioMRF** [comment]
I have faced the same error

**Comment by smashah** [comment]
@CarlosAurelioMRF do you have any more context on how to reproduce this?

**Comment by CarlosAurelioMRF** [comment]
> @CarlosAurelioMRF do you have any more context on how to reproduce this?

I dont have more info just that my app has been running for 4 days now, I usually see this error after 2 days without stop. 
I send/receive huge number of messages and some numbers work as expected, this error happens for new chats (less than 24 hours). If I stop my app and run again I can send messages normally without errors.

**Comment by smashah** [comment]
@CarlosAurelioMRF if you have high throughput you will get the odd internal wa web error and that's what this is. Something is going wrong internally and it cannot update the internal db chat table. It's actually not got anything to do with open-wa.

What I can suggest is:
- Restart your session at least once a day.
- If you get this error with a chat then delete the chat and send a text to it again.
- Queue your messages to avoid race conditions that can possibly lead to errors.
