### ISSUE TITLE
Promote/Demote Participant on community

### ISSUE THREAD

**Issue by fukumori** [open-wa/wa-automate-nodejs#3089]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

Mar 31 13:04:28[72523]: info: MDLWR - promoteParticipant : {"args":{"groupId":"xxxx@g.us","participantId":"zzzz@c.us"}} {"timestamp":"2023-03-31T16:04:28.175Z"}
Mar 31 13:04:28[72523]: info: methodArgs: groupId,participantId {"timestamp":"2023-03-31T16:04:28.176Z"}
Mar 31 13:04:28[72523]: info: IN d06d8  {"_args":{"groupId":"xxxx@g.us","participantId":"zzzz@c.us"},"_method":"promoteParticipant","timestamp":"2023-03-31T16:04:28.176Z"}
Mar 31 13:04:28[72523]: middleware -> error Error: Evaluation failed: i
Mar 31 13:04:28[72523]:     at ExecutionContext._ExecutionContext_evaluate (node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:252:15)
Mar 31 13:04:28[72523]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Mar 31 13:04:28[72523]:     at async ExecutionContext.evaluate (node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:140:16)

Mar 31 13:03:05[72523]: info: MDLWR - demoteParticipant : {"args":{"groupId":"xxxx@g.us","participantId":"yyyy@c.us"}} {"timestamp":"2023-03-31T16:03:05.677Z"}
Mar 31 13:03:05[72523]: info: methodArgs: groupId,participantId {"timestamp":"2023-03-31T16:03:05.682Z"}
Mar 31 13:03:05[72523]: info: IN 73a86  {"_args":{"groupId":"xxxx@g.us","participantId":"yyyy@c.us"},"_method":"demoteParticipant","timestamp":"2023-03-31T16:03:05.684Z"}
Mar 31 13:03:06[72523]: middleware -> error Error: Evaluation failed: i
Mar 31 13:03:06[72523]:     at ExecutionContext._ExecutionContext_evaluate (node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:252:15)
Mar 31 13:03:06[72523]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Mar 31 13:03:06[72523]:     at async ExecutionContext.evaluate (node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:140:16)

### Steps To Reproduce

promote/demote participants on community group

### DEBUG INFO

```markdown
"WA_VERSION": "2.2314.7",
"PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
"WA_AUTOMATE_VERSION": "4.62.2",
"BROWSER_VERSION": "HeadlessChrome/111.0.5563.146",
"OS": "Linux 5.15",
"START_TS": 1680279332064,
"RAM_INFO": "Total: 4.11 GB | Free: 3.43 GB",
"PPTR_VERSION": "19.8.2"
```

### Environment

```markdown
- OS: 
- Node: 
- npm:
```

**Comment by smashah** [comment]
strange, same wa version, same lib version, working here fine. can you restart and try again please. Also, i thought the problem was that the promotion and demotion events weren't firing? Please confirm if that's a problem also?

**Comment by fukumori** [comment]
Confirm still not working:

Apr  5 08:52:40 [220013]: info: MDLWR - promoteParticipant : {"args":{"groupId":"xxxx@g.us","participantId":"yyyy@c.us"}} {"timestamp":"2023-04-05T11:52:40.855Z"}
Apr  5 08:52:40 [220013]: info: methodArgs: groupId,participantId {"timestamp":"2023-04-05T11:52:40.855Z"}
Apr  5 08:52:40 [220013]: info: IN 16503  {"_args":{"groupId":"xxxx@g.us","participantId":"yyyy@c.us"},"_method":"promoteParticipant","timestamp":"2023-04-05T11:52:40.855Z"}
Apr  5 08:52:42 [220013]: middleware -> error Error: Evaluation failed: i
Apr  5 08:52:42 [220013]:     at ExecutionContext._ExecutionContext_evaluate (node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:252:15)
Apr  5 08:52:42 [220013]:     at runMicrotasks (<anonymous>)
Apr  5 08:52:42 [220013]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Apr  5 08:52:42 [220013]:     at async ExecutionContext.evaluate (node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:140:16)


I'm trying to do this:

https://faq.whatsapp.com/441425088132574

Promote and demote on normal groups works.

Apr  5 08:59:15 [240679]: info: MDLWR - approveGroupJoinRequest : {"args":{"groupChatId":"aaaa@g.us","contactId":"zzzzz@c.us"}} {"timestamp":"2023-04-05T11:59:15.759Z"}
Apr  5 08:59:15 [240679]: info: methodArgs: groupChatId,contactId {"timestamp":"2023-04-05T11:59:15.761Z"}
Apr  5 08:59:15 [240679]: info: IN 068f2  {"_args":{"contactId":"zzzzz@c.us","groupChatId":"aaaa@g.us"},"_method":"approveGroupJoinRequest","timestamp":"2023-04-05T11:59:15.762Z"}
Apr  5 08:59:16 [240679]: info: OUT 068f2: 547ms  {"res":true,"timestamp":"2023-04-05T11:59:16.309Z"}
Apr  5 09:00:34 [240679]: info: MDLWR - promoteParticipant : {"args":{"groupId":"aaaa@g.us","participantId":"zzzzz@c.us"}} {"timestamp":"2023-04-05T12:00:34.179Z"}
Apr  5 09:00:34 [240679]: info: methodArgs: groupId,participantId {"timestamp":"2023-04-05T12:00:34.180Z"}
Apr  5 09:00:34 [240679]: info: IN 28e91  {"_args":{"groupId":"aaaa@g.us","participantId":"zzzzz@c.us"},"_method":"promoteParticipant","timestamp":"2023-04-05T12:00:34.181Z"}
Apr  5 09:00:34 [240679]: info: OUT 28e91: 688ms  {"res":true,"timestamp":"2023-04-05T12:00:34.869Z"}
