### ISSUE TITLE
Client crashes after making request to chatwoot

### ISSUE THREAD

**Issue by WEBudoGT** [open-wa/wa-automate-nodejs#3109]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

Suddenly, the docker instance restarts with no other logs than the following:

2023-04-18T16:36:33.483481299Z • Listening on port 8002!
**2023-04-18T18:15:19.018663178Z TypeError: Cannot read properties of undefined (reading 'id')**
2023-04-18T18:15:19.018710951Z     at ChatwootClient.<anonymous> (/usr/src/app/node_modules/@open-wa/wa-automate/dist/cli/integrations/chatwoot.js:492:93)
2023-04-18T18:15:19.018717543Z     at Generator.next (<anonymous>)
2023-04-18T18:15:19.018721609Z     at fulfilled (/usr/src/app/node_modules/@open-wa/wa-automate/dist/cli/integrations/chatwoot.js:5:58)
2023-04-18T18:15:19.018725450Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-04-18T18:15:20.063099660Z Starting the application
2023-04-18T18:15:20.063145417Z Using version: latest

### Steps To Reproduce

No specific tasks to reproduce

### DEBUG INFO

```markdown
DEBUG - flags: {"sessionId":"session","executablePath":"/usr/bin/google-chrome","popup":true,"disableSpins":true,"cliConfig":"/config","keepAlive":true,"useChrome":true,"chatwootUrl":"https://chatwoot-url.tld/api/v1/accounts/1/inboxes/11","chatwootApiAccessToken":"XXXXXXXX","licenseKey":"XXXXXXX","popupQrOnly":true,"skipSavePostmanCollection":true,"onCall":"Este numero no recibe llamadas.","autoReject":true,"generateApiDocs":false,"noKillOnLogout":true,"multiDevice":true,"inDocker":true,"qrTimeout":0,"debug":true,"forcePort":true,"noApi":false,"forceUpdateCwWebhook":false,"port":8002,"host":"localhost","verbose":false,"ef":["qr","STARTUP","MD_DETECT","qrUrl"],"allowSessionDataWh":false,"sessionDataOnly":false,"headful":false,"preAuthDocs":false,"stats":false,"cors":false,"socket":false,"emitUnread":false,"allowIps":[]}
```

### Environment

```markdown
Docker compose
```

**Comment by WEBudoGT** [comment]
I enabled debug logs to get what's happening before the error on my previous post, and got this which may help a bit:

`2023-04-19T16:27:52.605081859Z info: CW REQUEST: 200 get https://chatwoot.tld/api/v1/accounts/1/contacts/search?q=status@broadcast&sort=phone_number undefined {"timestamp":"2023-04-19T16:27:52.604Z"}
2023-04-19T16:27:52.628629634Z error: Request failed with status code 422 {"config":{"data":"{\"identifier\":\"XXXXXXXXXX@c.us\",\"name\":\"Josue Jacobo\",\"phone_number\":\"+XXXXXXXXXX\",\"custom_attributes\":{\"wa:number\":\"XXXXXXXXXX\",\"id\":\"XXXXXXXXXX@c.us\",\"name\":\"John Doe\",\"shortName\":\"John\",\"...[TRUNCATED]...","headers":{"Accept":"application/json, text/plain, */*","Content-Length":476,"Content-Type":"application/json","User-Agent":"axios/0.25.0","api_access_token":"[REDACTED]"},"maxBodyLength":-1,"maxContentLength":-1,"method":"post","timeout":0,"transformRequest":[null],"transformResponse":[null],"transitional":{"clarifyTimeoutError":false,"forcedJSONParsing":true,"silentJSONParsing":true},"url":"https://chatwoot.tld/api/v1/accounts/1/contacts","xsrfCookieName":"[REDACTED]","xsrfHeaderName":"X-XSRF-TOKEN"},"name":"Error","stack":"Error: Request failed with status code 422\n    at createError (/usr/src/app/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/usr/src/app/node_modules/axios/lib/core/settle.js:17:12)\n...[TRUNCATED]...","status":422,"timestamp":"2023-04-19T16:27:52.627Z"}
2023-04-19T16:27:52.629366104Z TypeError: Cannot read properties of undefined (reading 'id')
2023-04-19T16:27:52.629397045Z     at ChatwootClient.<anonymous> (/usr/src/app/node_modules/@open-wa/wa-automate/dist/cli/integrations/chatwoot.js:492:93)
2023-04-19T16:27:52.629403264Z     at Generator.next (<anonymous>)
2023-04-19T16:27:52.629407028Z     at fulfilled (/usr/src/app/node_modules/@open-wa/wa-automate/dist/cli/integrations/chatwoot.js:5:58)
2023-04-19T16:27:52.629410750Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
try {
	execSync(cmd, {stdio: 'inherit'})
}  catch (error) {
    console.log(`Status Code: ${error.status} with '${error.message}'`);
 }
}
//set the version type
process.env.VERS = "patch"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN && npm run types:publish `);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.64.5](https://github.com/open-wa/wa-automate-nodejs/compare/4.64.4...4.64.5) (2023-04-19)

- 🥅 catch chatwoot message errors - don't crash the process #3109 [`33c8c7c`](https://github.com/open-wa/wa-automate-nodejs/commit/33c8c7c2b28fbdcf029ded2d659d33b705ff9a69)
- Release 4.64.5 [`e3652e2`](https://github.com/open-wa/wa-automate-nodejs/commit/e3652e216d4a3f8723c07d6ba083487b233cc51d)
- 🔧 chatwoot message handler should ignore stories #3109 [`ff3d269`](https://github.com/open-wa/wa-automate-nodejs/commit/ff3d269ee63fd5708e90610b2ea2e6e12e4bbb60)
- 🥚 patches update [`fdea81b`](https://github.com/open-wa/wa-automate-nodejs/commit/fdea81bebbd19bcf672cdfa86ae4a5dcc88c40fc)
- 🥚 patches update [`4497d25`](https://github.com/open-wa/wa-automate-nodejs/commit/4497d2524ceb180a8bc99d108bda8e3fb9cb4ef5)
- 🥚 patches update [`c0904e2`](https://github.com/open-wa/wa-automate-nodejs/commit/c0904e2829dd0833d97320d302c06060ec26f59b)
- 🥚 patches update [`cd87809`](https://github.com/open-wa/wa-automate-nodejs/commit/cd878091f5999ae258b1b72e6329f62fb3d7f9a7)
- updated types-only package [`7f6a8e6`](https://github.com/open-wa/wa-automate-nodejs/commit/7f6a8e6c8ad23ce25cc0b06e5f3ef90e2a865838)
