### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ghlnv** [open-wa/wa-automate-nodejs#3140]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

EASY API/CLI

### Current Behavior

When I send a message, the message is not sent and the API returns an error:

[success] => 
    [error] => Array
        (
            [name] => RangeError
            [message] => Maximum call stack size exceeded
        )

This is the exception that appears on the server:

• Listening on port 3000!
middleware -> error RangeError: Maximum call stack size exceeded
    at klona (/home/ubuntu/wa-easyapi/node_modules/klona/full/index.js:8:15)
    at set (/home/ubuntu/wa-easyapi/node_modules/klona/full/index.js:2:49)
    at klona (/home/ubuntu/wa-easyapi/node_modules/klona/full/index.js:43:4)
    at set (/home/ubuntu/wa-easyapi/node_modules/klona/full/index.js:2:49)
    at klona (/home/ubuntu/wa-easyapi/node_modules/klona/full/index.js:43:4)
    at set (/home/ubuntu/wa-easyapi/node_modules/klona/full/index.js:2:49)
    at klona (/home/ubuntu/wa-easyapi/node_modules/klona/full/index.js:43:4)
    at set (/home/ubuntu/wa-easyapi/node_modules/klona/full/index.js:2:49)
    at klona (/home/ubuntu/wa-easyapi/node_modules/klona/full/index.js:43:4)
    at set (/home/ubuntu/wa-easyapi/node_modules/klona/full/index.js:2:49)

### Expected Behavior

I expected the message to be sent and return a message without errors.

### Steps To Reproduce

1. Ubuntu 22.04
2. Node v18.2.1
3. Npm 9.8.0
4. Wa-automate 4.66.3

### create() code OR full CLI command + CONFIG

```markdown
npx @open-wa/wa-automate -p 3000 -k 'MQzEWlDezx' --license-key='...' --popup --keep-alive --multi-device --skip-save-postman-collection --no-api -v --debug --config "{qrTimeout: 120, authTimeout: 30, restartOnCrash: start, killProcessOnBrowserClose: true, waitForRipeSession: true}" >> /home/ubuntu/wa-easyapi/logs/wa-easyapi.log
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2329.9",
  "WA_AUTOMATE_VERSION": "4.66.3",
  "BROWSER_VERSION": "HeadlessChrome/112.0.5614.0",
  "START_TS": 1689197018146,
  "RAM_INFO": "Total: 0.97 GB | Free: 0.44 GB",
  "PPTR_VERSION": "19.11.1",
  "LATEST_VERSION": true,
  "CLI": true,
  "PATCH_HASH": "9f38b",
  "LAUNCH_TIME_MS": 23602,
  "ACC_TYPE": "BUSINESS",
  "chats": 451,
  "messages": 50,
  "contacts": 913,
  "isBiz": true,
  "isMd": true,
  "INSTANCE_ID": "41ca8885-7360-4dcb-8920-b75ea5c17ef3"
}
```

### Environment

```markdown
- OS: Linux 5.19
- Node: 18.12.1
- npm: 9.8.0
```

**Comment by edertoad** [comment]
Did you fix it? Same Problem here
