### ISSUE TITLE
Not able to send message using .sendText method. | PS: have not purchased any license or anything.

### ISSUE THREAD

**Issue by sagarTc125** [open-wa/wa-automate-nodejs#3200]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Legacy (Normal)

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

whiile using .sendText() method to send the message getting this error:

Error sending message: Error: Evaluation failed: TypeError: Cannot read properties of null (reading 'id')
    at window.<computed>.<computed> [as sendMessage] (pptr://__puppeteer_evaluation_script__:1:482720)
    at ExecutionContext._ExecutionContext_evaluate (/home/sagar/wa-demo-project/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:258:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/home/sagar/wa-demo-project/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:146:16)

ALSO in the client getting something like this:

"onOrder": "ERROR: This feature requires an Insiders license. Use this link to get the correct license => https://get.openwa.dev/l/**********&f=onOrder",
    "onNewProduct": "ERROR: This feature requires an Insiders license. Use this link to get the correct license => https://get.openwa.dev/l/**********?v=i&f=onNewProduct",
    "onReaction": "ERROR: This feature requires an Insiders license. Use this link to get the correct license => https://get.openwa.dev/l/**********?v=i&f=onReaction",
    "onGroupChange": "ERROR: This feature requires an Insiders license. Use this link to get the correct license => https://get.openwa.dev/l/**********?v=i&f=onGroupChange"
  }
  
  
  I'm not sure if this is a bug or do i need to purchase a license to use features such as sending text messages.

### Expected Behavior

whiile using .sendText() method to send the message getting this error:

Error sending message: Error: Evaluation failed: TypeError: Cannot read properties of null (reading 'id')
    at window.<computed>.<computed> [as sendMessage] (pptr://__puppeteer_evaluation_script__:1:482720)
    at ExecutionContext._ExecutionContext_evaluate (/home/sagar/wa-demo-project/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:258:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/home/sagar/wa-demo-project/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:146:16)

ALSO in the client getting something like this:

"onOrder": "ERROR: This feature requires an Insiders license. Use this link to get the correct license => https://get.openwa.dev/l/**********&f=onOrder",
    "onNewProduct": "ERROR: This feature requires an Insiders license. Use this link to get the correct license => https://get.openwa.dev/l/**********?v=i&f=onNewProduct",
    "onReaction": "ERROR: This feature requires an Insiders license. Use this link to get the correct license => https://get.openwa.dev/l/**********?v=i&f=onReaction",
    "onGroupChange": "ERROR: This feature requires an Insiders license. Use this link to get the correct license => https://get.openwa.dev/l/**********?v=i&f=onGroupChange"
  }
  
  
  I'm not sure if this is a bug or do i need to purchase a license to use features such as sending text messages.

### Steps To Reproduce

whiile using .sendText() method to send the message getting this error:

Error sending message: Error: Evaluation failed: TypeError: Cannot read properties of null (reading 'id')
    at window.<computed>.<computed> [as sendMessage] (pptr://__puppeteer_evaluation_script__:1:482720)
    at ExecutionContext._ExecutionContext_evaluate (/home/sagar/wa-demo-project/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:258:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/home/sagar/wa-demo-project/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:146:16)

ALSO in the client getting something like this:

"onOrder": "ERROR: This feature requires an Insiders license. Use this link to get the correct license => https://get.openwa.dev/l/**********&f=onOrder",
    "onNewProduct": "ERROR: This feature requires an Insiders license. Use this link to get the correct license => https://get.openwa.dev/l/**********?v=i&f=onNewProduct",
    "onReaction": "ERROR: This feature requires an Insiders license. Use this link to get the correct license => https://get.openwa.dev/l/**********?v=i&f=onReaction",
    "onGroupChange": "ERROR: This feature requires an Insiders license. Use this link to get the correct license => https://get.openwa.dev/l/**********?v=i&f=onGroupChange"
  }
  
  
  I'm not sure if this is a bug or do i need to purchase a license to use features such as sending text messages.

### create() code OR full CLI command + CONFIG

```markdown
whiile using .sendText() method to send the message getting this error:

Error sending message: Error: Evaluation failed: TypeError: Cannot read properties of null (reading 'id')
    at window.<computed>.<computed> [as sendMessage] (pptr://__puppeteer_evaluation_script__:1:482720)
    at ExecutionContext._ExecutionContext_evaluate (/home/sagar/wa-demo-project/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:258:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/home/sagar/wa-demo-project/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:146:16)



ALSO in the client getting something like this:

"onOrder": "ERROR: This feature requires an Insiders license. Use this link to get the correct license => https://get.openwa.dev/l/**********&f=onOrder",
    "onNewProduct": "ERROR: This feature requires an Insiders license. Use this link to get the correct license => https://get.openwa.dev/l/**********?v=i&f=onNewProduct",
    "onReaction": "ERROR: This feature requires an Insiders license. Use this link to get the correct license => https://get.openwa.dev/l/**********?v=i&f=onReaction",
    "onGroupChange": "ERROR: This feature requires an Insiders license. Use this link to get the correct license => https://get.openwa.dev/l/**********?v=i&f=onGroupChange"
  }
  
  
  I'm not sure if this is a bug or do i need to purchase a license to use features such as sending text messages.
```

### DEBUG INFO

```markdown
{
    WA_VERSION: '2.3000.1012945199',
    PAGE_UA: 'WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36',
    WA_AUTOMATE_VERSION: '4.71.10',
    BROWSER_VERSION: 'HeadlessChrome/112.0.5614.0',
    OS: 'Linux 6.5',
    START_TS: 1713786603755,
    RAM_INFO: 'Total: 16.48 GB | Free: 4.16 GB',
    PPTR_VERSION: '19.11.1',
    LATEST_VERSION: true,
    CLI: false,
    PATCH_HASH: '792f4',
    OW_KEY: 'a0c74d54e3773b6e4d280d263ba435c148f420bced39e6481431e445918d1524',
    NUM: '0569',
    NUM_HASH: 'e87a60235601dbdebebfc0db5535f543',
    LAUNCH_TIME_MS: 11341,
    ACC_TYPE: 'PERSONAL',
    chats: 510,
    messages: 134,
    contacts: 4235,
    purged: {},
    isMd: true,
    INSTANCE_ID: '3c75f7cc-7c1c-4b78-b816-6fee867b021a',
    PHONE_VERSION: undefined
  }
```

### Environment

```markdown
- OS: Ubuntu 22.04.4 LTS
- Node: 16.19.0
- npm: 8.19.3
```

### Screenshots/Logs

whiile using .sendText() method to send the message getting this error:

Error sending message: Error: Evaluation failed: TypeError: Cannot read properties of null (reading 'id')
    at window.<computed>.<computed> [as sendMessage] (pptr://__puppeteer_evaluation_script__:1:482720)
    at ExecutionContext._ExecutionContext_evaluate (/home/sagar/wa-demo-project/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:258:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/home/sagar/wa-demo-project/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:146:16)

ALSO in the client getting something like this:

"onOrder": "ERROR: This feature requires an Insiders license. Use this link to get the correct license => https://get.openwa.dev/l/**********&f=onOrder",
    "onNewProduct": "ERROR: This feature requires an Insiders license. Use this link to get the correct license => https://get.openwa.dev/l/**********?v=i&f=onNewProduct",
    "onReaction": "ERROR: This feature requires an Insiders license. Use this link to get the correct license => https://get.openwa.dev/l/**********?v=i&f=onReaction",
    "onGroupChange": "ERROR: This feature requires an Insiders license. Use this link to get the correct license => https://get.openwa.dev/l/**********?v=i&f=onGroupChange"
  }
  
  
  I'm not sure if this is a bug or do i need to purchase a license to use features such as sending text messages.

### Anything else?

whiile using .sendText() method to send the message getting this error:

Error sending message: Error: Evaluation failed: TypeError: Cannot read properties of null (reading 'id')
    at window.<computed>.<computed> [as sendMessage] (pptr://__puppeteer_evaluation_script__:1:482720)
    at ExecutionContext._ExecutionContext_evaluate (/home/sagar/wa-demo-project/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:258:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/home/sagar/wa-demo-project/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:146:16)

ALSO in the client getting something like this:

"onOrder": "ERROR: This feature requires an Insiders license. Use this link to get the correct license => https://get.openwa.dev/l/**********&f=onOrder",
    "onNewProduct": "ERROR: This feature requires an Insiders license. Use this link to get the correct license => https://get.openwa.dev/l/**********?v=i&f=onNewProduct",
    "onReaction": "ERROR: This feature requires an Insiders license. Use this link to get the correct license => https://get.openwa.dev/l/**********?v=i&f=onReaction",
    "onGroupChange": "ERROR: This feature requires an Insiders license. Use this link to get the correct license => https://get.openwa.dev/l/**********?v=i&f=onGroupChange"
  }
  
  
  I'm not sure if this is a bug or do i need to purchase a license to use features such as sending text messages.

**Comment by smashah** [comment]
You dont need to purchase a license to send messages to your existing chats/contacts. Very strange error which is hard to debug without your `sendText` code. Can you share exactly what you're trying to send (redact part of the phone number)
