### ISSUE TITLE
`decryptMedia` returns an error

### ISSUE THREAD

**Issue by BbayuGt** [open-wa/wa-automate-nodejs#3236]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

decryptMedia returns 
```json
{
  error: {
    message: "Cannot read properties of undefined (reading 'mimetype')",
    stack: "TypeError: Cannot read properties of undefined (reading 'mimetype')\n    at Client.<anonymous> (/usr/src/app/node_modules/@open-wa/wa-automate/dist/api/Client.js:1773:20)\n    at Generator.next (<anonymous>)\n    at /usr/src/app/node_modules/@open-wa/wa-automate/dist/api/Client.js:31:71\n    at new Promise (<anonymous>)\n    at __awaiter (/usr/src/app/node_modules/@open-wa/wa-automate/dist/api/Client.js:27:12)\n    at Client.decryptMedia (/usr/src/app/node_modules/@open-wa/wa-automate/dist/api/Client.js:1766:16)\n    at /usr/src/app/node_modules/@open-wa/wa-automate/dist/cli/server.js:525:53\n    at Generator.next (<anonymous>)\n    at /usr/src/app/node_modules/@open-wa/wa-automate/dist/cli/server.js:31:71\n    at new Promise (<anonymous>)",
  },
}
```

### Expected Behavior

media decrypted

### Steps To Reproduce

use decryptmedia(message)

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.3000.1015491093",
  "WA_AUTOMATE_VERSION": "4.72.0",
  "BROWSER_VERSION": "HeadlessChrome/127.0.6533.99",
  "START_TS": 1723079158858,
  "RAM_INFO": "Total: 14.38 GB | Free: 10.73 GB",
  "PPTR_VERSION": "19.11.1",
  "LATEST_VERSION": true,
  "CLI": true,
  "PATCH_HASH": "08b09",
  "LAUNCH_TIME_MS": 31344,
  "ACC_TYPE": "PERSONAL",
  "chats": 121,
  "messages": 372,
  "contacts": 3249,
  "isBiz": false,
  "isMd": true,
  "INSTANCE_ID": "e01c6bef-ccb6-4eb8-b5db-026cfc88f7a0"
}
```

### Environment

```markdown
- OS: Linux 6.10
- Node: 22.6.0
- npm: 10.8.2
```

**Comment by BbayuGt** [comment]
One more, editMessage also seems to be fail silently
