### ISSUE TITLE
Possible group permissions flags are getting mixed up?

### ISSUE THREAD

**Issue by jdmis-alaz** [open-wa/wa-automate-nodejs#3239]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

EASY API/CLI

### Current Behavior

createGroup created groups with easyAPI
default approval mode: Require admin approval.
-- URL: http://xxxx:8085/setGroupApprovalMode
-- Data: {"args":{"groupId":"xxxxx@g.us","requireApproval":false}}
Set group approval mode response: {"success":true}

BUT 
This does NOT change the admin approval mode. Instead it changes  'EDIT GROUP SETTINGS' permission (retureApproval=True sets editSettings to False and vice versa)

### Expected Behavior

GroupApprovalMode permission should be set correctly

### Steps To Reproduce

1. in docker container
2. using licenced version
3. -- URL: http://xxx/setGroupApprovalMode
-- Data: {"args":{"groupId":"xxxxxx@g.us","requireApproval":true}}
-- Response: {"success":true}

but as described above, a different permission flag is toggled

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.3000.1016015341",
  "WA_AUTOMATE_VERSION": "4.72.1",
  "BROWSER_VERSION": "HeadlessChrome/125.0.6422.141",
  "START_TS": 1724828627164,
  "RAM_INFO": "Total: 3.88 GB | Free: 2.81 GB",
  "PPTR_VERSION": "19.11.1",
  "LATEST_VERSION": true,
  "CLI": true
}
```

### Environment

```markdown
- OS: Linux 5.13
- Node: 22.2.0
- npm: 10.8.1
```

### Screenshots/Logs

Not sure if this console error is related

middleware -> error ProtocolError: Protocol error (Runtime.callFunctionOn): Promise was collected
    at Callback (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:61:35)
    at CallbackRegistry.create (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:106:26)
    at Connection._rawSend (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:216:26)
    at CDPSessionImpl.send (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:425:78)
    at ExecutionContext._ExecutionContext_evaluate (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:240:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:146:16)

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
try {
	execSync(cmd, {stdio: 'inherit'})
}  catch (error) {
    console.log(`Status Code: ${error.status} with '${error.message}'`);
 }
}
//set the version type
process.env.VERS = "patch"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN && npm run types:publish `);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.72.2](https://github.com/open-wa/wa-automate-nodejs/compare/4.72.1...4.72.2) (2024-08-29)

- 🚑 fix #3239 [`#3239`](https://github.com/open-wa/wa-automate-nodejs/issues/3239)
- Release 4.72.2 [`306ab11`](https://github.com/open-wa/wa-automate-nodejs/commit/306ab11e899922a8a0b3bf37130b6b8d1b3d27c0)
- updated types-only package [`8ec43a3`](https://github.com/open-wa/wa-automate-nodejs/commit/8ec43a308d26b77cd3e71074ff5222f3b931a3a7)
