### ISSUE TITLE
Docker - send message sends message, but reports middleware error

### ISSUE THREAD

**Issue by jdmis-alaz** [open-wa/wa-automate-nodejs#3260]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

EASY API/CLI

### Current Behavior

/sendText     { "to": "myrealnumber@c.us",    "content": "Hello World!"  }

*I receive the text
but.... the response is this:

{  "success": false,  "error": {    "name": "ProtocolError",    "message": "Please set arguments in request json body, not in params. Protocol error (Runtime.callFunctionOn): Promise was collected"  } }

And I see this in the logs
middleware -> error ProtocolError: Protocol error (Runtime.callFunctionOn): Promise was collected
    at <instance_members_initializer> (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:94:14)
    at new Callback (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:98:16)
    at CallbackRegistry.create (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:23:26)
    at Connection._rawSend (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:90:26)
    at CdpCDPSession.send (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:66:33)
    at #evaluate (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:360:50)
    at ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:275:36)
    at IsolatedWorld.evaluate (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:100 :30)
    at CdpFrame.evaluate (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:341:43)
    at CdpFrame.<anonymous> (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/decorators.js:104:27)

Although the text is going out (good) it is breaking because it returns an error and no reference to the sent message.

### Expected Behavior

Send actually works, but ALSO reports that it works so as not to break any downstream use of the wa-automate. Currently completely unusable.

### Steps To Reproduce

Compose file

version: "3"
services:
  owa:
    image: openwa/wa-automate:latest
    hostname: owa
    init: true
    restart: on-failure
    tty: true
    stdin_open: true
    volumes:
      - "sessions:/sessions"
    ports:
      - "8085:8085"
      - "8002:8002"
      - "7000:7000"
    environment:
      WA_DISABLE_SPINS: 'true'
      WA_LICENSE_KEY: 'my licence'
      WA_WEBHOOK: 'http://mywebhook.com' 
      WA_PORT: 8085

    command: >
      -x 
      -w 'http://mywebhook.com'
      --ready-webhook http://mywebhook.com
      --ev http://mywebhook.com
      -l my-licene
      --qr-max 3
      --auto-reject
      --disable-spins
        
volumes:
  sessions:

Run it, send as above. 

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.3000.1018908912",
  "WA_AUTOMATE_VERSION": "4.74.2",
  "BROWSER_VERSION": "Chrome/131.0.6778.85",
  "START_TS": 1734395795738,
  "RAM_INFO": "Total: 3.88 GB | Free: 1.68 GB",
  "PPTR_VERSION": "23.9.0",
  "LATEST_VERSION": true,
  "CLI": true,
  "PATCH_HASH": "58bbb",
  "LAUNCH_TIME_MS": 19957,
  "ACC_TYPE": "BUSINESS",
  "chats": 78,
  "messages": 80,
  "contacts": 749,
  "isBiz": true,
  "isMd": true,
  "INSTANCE_ID": "803ec83b-8f5f-4c57-b746-813636aeb45f"
}
```

### Environment

```markdown
- OS: Linux 5.13
- Node: 23.2.0
- npm: 10.9.0
```

**Comment by peterson-umoke** [comment]
any update on this, mine does not even send the text message ?
