### ISSUE TITLE
Error on get QR after close session in phone

### ISSUE THREAD

**Issue by devalexanderdaza** [open-wa/wa-automate-nodejs#339]
**Describe the bug**
This error show after close session on phone. In this moment, get new QR code from socket.io and show this error. (Sometimes it happens but not always)

**Steps to Reproduce**
1. Star session reading QR Code
2. After "whatsapp ready" close session on WhatsApp APP
3. Request new QR Code
4. See error sometimes

**create() code**
This is the code you use to create the client. e.g
```javascript
// Creación del nuevo cliente de navegador para whatsapp web con Puppeteer
                        wa.create(sessionId, {
                            executablePath: chromeApp,
                            headless: true,
                            throwErrorOnTosBlock: true,
                            killTimer: 3600,
                            autoRefresh: true,
                            qrRefreshS: 15,
                            cacheEnabled: false
                        }).then((client: Whatsapp) => startWhatsappListener(client, sessionId, io, socketId));

                        // Cuando se genere un nuevo código QR de inicio de sesión, se lo enviamos al cliente a través del Socket
                        ev.on('qr.**', async (qrcode: string, whatsappSessionId: any) => {
                            io.to(socketId).emit('whatsapp:qrCode', qrcode);
                        });
```

**Expected behavior**

**DEBUG INFO**
```bash
                                                                                    
⠋ Initializing whatsapp(node:3692) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:3692) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added to [process]. Use emitter.setMaxListeners() to increase limit
✔ Initializing whatsapp
┌─────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│       (index)       │                                                                   Values                                                                    │
├─────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│     WA_VERSION      │                                                                 '2.2013.7'                                                                  │
│       PAGE_UA       │ 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                  '1.8.69'                                                                   │
│   BROWSER_VERSION   │                                                       'HeadlessChrome/80.0.3987.163'                                                        │
└─────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ℹ Authenticate to continue
✔ Loading QR
 
(node:3692) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'parentElement' of null
    at __puppeteer_evaluation_script__:1:56
    at ExecutionContext._evaluateInternal (/Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Mis_Datos/Whatsapp_API/node_modules/puppeteer/lib/ExecutionContext.js:73:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async ExecutionContext.evaluate (/Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Mis_Datos/Whatsapp_API/node_modules/puppeteer/lib/ExecutionContext.js:43:16)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Mis_Datos/Whatsapp_API/node_modules/puppeteer/lib/helper.js:105:23)
    at DOMWorld.evaluate (/Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Mis_Datos/Whatsapp_API/node_modules/puppeteer/lib/DOMWorld.js:102:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
  -- ASYNC --
    at Frame.<anonymous> (/Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Mis_Datos/Whatsapp_API/node_modules/puppeteer/lib/helper.js:105:23)
    at Page.evaluate (/Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Mis_Datos/Whatsapp_API/node_modules/puppeteer/lib/Page.js:784:47)
    at Page.<anonymous> (/Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Mis_Datos/Whatsapp_API/node_modules/puppeteer/lib/helper.js:106:31)
    at Object.<anonymous> (/Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Mis_Datos/Whatsapp_API/node_modules/@open-wa/wa-automate/dist/controllers/auth.js:104:43)
    at step (/Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Mis_Datos/Whatsapp_API/node_modules/@open-wa/wa-automate/dist/controllers/auth.js:33:23)
    at Object.next (/Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Mis_Datos/Whatsapp_API/node_modules/@open-wa/wa-automate/dist/controllers/auth.js:14:53)
    at fulfilled (/Users/devalexanderdaza/Documents/Dinamica/Desarrollos/Mis_Datos/Whatsapp_API/node_modules/@open-wa/wa-automate/dist/controllers/auth.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:3692) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
```

```
Debug Info {
  WA_VERSION: ...,
  PAGE_UA: ...,
  WA_AUTOMATE_VERSION: ...,
  BROWSER_VERSION: ...
}
```

**Comment by smashah** [comment]
@devalexanderdaza just to be crystal clear, what do you mean by: 

> After "whatsapp ready" close session on WhatsApp APP

?

**Comment by devalexanderdaza** [comment]
> @devalexanderdaza just to be crystal clear, what do you mean by:
> 
> > After "whatsapp ready" close session on WhatsApp APP
> 
> ?

After closing the whatsapp session on the phone and requesting a new QR code without restarting the server, this error sometimes occurs.

This error is displayed in the console after the following:

✔ Authenticating
✔ WAPI Reinjected
✔ Whatsapp is ready

**Comment by smashah** [comment]
I need to be able to recreate this in headful mode to see what's going on. Will report back when I've found a proper fix.

**Comment by devalexanderdaza** [comment]
Thanks @smashah :)

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.73](https://github.com/open-wa/wa-automate-nodejs/compare/1.8.72...1.8.73) (2020-04-20)

- Release 1.8.73 [`7da313e`](https://github.com/open-wa/wa-automate-nodejs/commit/7da313e9f5228c2b8bb3d0ae19b54cf6f2e2f27d)
- possible fix for #339 [`98cce47`](https://github.com/open-wa/wa-automate-nodejs/commit/98cce47141aafe7cc9eaffaed090cc7c8e6865fc)

**Comment by smashah** [comment]
@devalexanderdaza try v1.8.73 ¯\_(ツ)_/¯

Let me know if that works for you.

**Comment by devalexanderdaza** [comment]
Amazing @smashah. Works fine! Thanks.

Close issue! :)

**Comment by smashah** [comment]
@pselibas @ocracy @ev4ndropc @best-tech @thiagoamarante
