### ISSUE TITLE
getting error loadEarlierMessages

### ISSUE THREAD

**Issue by hasanbasri1993** [open-wa/wa-automate-nodejs#396]
**Describe the bug**
 i got error when more times loadEarlierMessages 

`======= 2020-05-04 23:53:38: Error: Evaluation failed: TypeError: Cannot read property 'map' of undefined
    at Object.window.WAPI.loadEarlierMessages (/Users/hasanbasri1/Downloads/app/whats2api/node_modules/@open-wa/wa-automate/dist/lib/wapi.js:541:52) Error: Evaluation failed: TypeError: Cannot read property 'map' of undefined
    at Object.window.WAPI.loadEarlierMessages (/Users/hasanbasri1/Downloads/app/whats2api/node_modules/@open-wa/wa-automate/dist/lib/wapi.js:541:52)
    at ExecutionContext._evaluateInternal (/Users/hasanbasri1/Downloads/app/whats2api/node_modules/puppeteer/lib/ExecutionContext.js:93:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/hasanbasri1/Downloads/app/whats2api/node_modules/puppeteer/lib/helper.js:82:19)
    at DOMWorld.evaluate (/Users/hasanbasri1/Downloads/app/whats2api/node_modules/puppeteer/lib/DOMWorld.js:111:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/Users/hasanbasri1/Downloads/app/whats2api/node_modules/puppeteer/lib/helper.js:82:19)
    at Page.evaluate (/Users/hasanbasri1/Downloads/app/whats2api/node_modules/puppeteer/lib/Page.js:792:47)
    at Page.<anonymous> (/Users/hasanbasri1/Downloads/app/whats2api/node_modules/puppeteer/lib/helper.js:83:27)
    at Whatsapp.<anonymous> (/Users/hasanbasri1/Downloads/app/whats2api/node_modules/@open-wa/wa-automate/dist/api/whatsapp.js:932:50)
    at step (/Users/hasanbasri1/Downloads/app/whats2api/node_modules/@open-wa/wa-automate/dist/api/whatsapp.js:44:23)
    at Object.next (/Users/hasanbasri1/Downloads/app/whats2api/node_modules/@open-wa/wa-automate/dist/api/whatsapp.js:25:53)
    at /Users/hasanbasri1/Downloads/app/whats2api/node_modules/@open-wa/wa-automate/dist/api/whatsapp.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/hasanbasri1/Downloads/app/whats2api/node_modules/@open-wa/wa-automate/dist/api/whatsapp.js:15:12)
    at Whatsapp.loadEarlierMessages (/Users/hasanbasri1/Downloads/app/whats2api/node_modules/@open-wa/wa-automate/dist/api/whatsapp.js:929:16)
  -- ASYNC --
    at Page.<anonymous> (/Users/hasanbasri1/Downloads/app/whats2api/node_modules/puppeteer/lib/helper.js:82:19)
    at Whatsapp.<anonymous> (/Users/hasanbasri1/Downloads/app/whats2api/node_modules/@open-wa/wa-automate/dist/api/whatsapp.js:932:50)
    at step (/Users/hasanbasri1/Downloads/app/whats2api/node_modules/@open-wa/wa-automate/dist/api/whatsapp.js:44:23)
    at Object.next (/Users/hasanbasri1/Downloads/app/whats2api/node_modules/@open-wa/wa-automate/dist/api/whatsapp.js:25:53)
    at /Users/hasanbasri1/Downloads/app/whats2api/node_modules/@open-wa/wa-automate/dist/api/whatsapp.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/hasanbasri1/Downloads/app/whats2api/node_modules/@open-wa/wa-automate/dist/api/whatsapp.js:15:12)
    at Whatsapp.loadEarlierMessages (/Users/hasanbasri1/Downloads/app/whats2api/node_modules/@open-wa/wa-automate/dist/api/whatsapp.js:929:16)
    at /Users/hasanbasri1/Downloads/app/whats2api/controllers/api.js:713:42
    at process._tickCallback (internal/process/next_tick.js:68:7)
`
**Steps to Reproduce**

**create() code**
This is the code you use to create the client. e.g
```
.create("/whatsSessions/" + F.config['instance'], {
        headless: true,
        autoRefresh: true,
        qrRefreshS: 30,
        killTimer: 6000,
        restartOnCrash: this.SETUP
        // executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
        // executablePath: '/var/www/app/node_modules/puppeteer/.local-chromium/linux-706915'
    }).then(async client => await WA_CLIENT.SETUP(client, F.config['webhook'], F.config['token'])).catch((e => {
        console.log('Error', e.message)
    }))

```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
   WA_VERSION     │  '2.2017.6'    
        PAGE_UA       │ 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36'
  WA_AUTOMATE_VERSION │ '1.9.8'                                                               
   BROWSER_VERSION   │ 'HeadlessChrome/81.0.4044.0'        
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS: MacOS

**Additional context**

thanks

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.9.9](https://github.com/open-wa/wa-automate-nodejs/compare/1.9.8...1.9.9) (2020-05-05)

- Bump release-it from 13.5.7 to 13.5.8 [`#394`](https://github.com/open-wa/wa-automate-nodejs/pull/394)
- Bump ts-node from 8.9.1 to 8.10.1 [`#395`](https://github.com/open-wa/wa-automate-nodejs/pull/395)
- Release 1.9.9 [`7bcf11a`](https://github.com/open-wa/wa-automate-nodejs/commit/7bcf11a34da2d35fa3efca3c94092709d13bd7bc)
- fix: return false if loadEarlierMsgs() == undefined #396 [`d4587be`](https://github.com/open-wa/wa-automate-nodejs/commit/d4587be8f0191bbf7487fb527bf589bf582b87fc)
