### ISSUE TITLE
[Question] UnhandledPromiseRejectionWarning: TypeError: fn is not a function

### ISSUE THREAD

**Issue by willianmaria** [open-wa/wa-automate-nodejs#414]
Hi!

I get this error when start session with queue promisses.

My code is equals to example of queue promisse.

How can I fix this?

```
whatsapp-app | (node:1) UnhandledPromiseRejectionWarning: TypeError: fn is not a function
whatsapp-app |     at run (/home/node/webapp/node_modules/p-queue/dist/index.js:250:104)
whatsapp-app |     at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
whatsapp-app |     at PQueue._processQueue (/home/node/webapp/node_modules/p-queue/dist/index.js:229:21)
whatsapp-app |     at PQueue.start (/home/node/webapp/node_modules/p-queue/dist/index.js:283:14)
whatsapp-app |     at start (/home/node/webapp/src/open-wa.js:114:15)
whatsapp-app |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
whatsapp-app |     at async createSession (/home/node/webapp/src/open-wa.js:58:3)
whatsapp-app | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
whatsapp-app | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️
