### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: fn is not a function

### ISSUE THREAD

**Issue by willianmaria** [open-wa/wa-automate-nodejs#415]
**Describe the bug**
When start queue of my unread messages I get this error/warn:

```

- Initializing whatsapp
--
  | - Initializing whatsapp
  | - Injecting api
  | ┌─────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
  | │       (index)       │                                                                   Values                                                                    │
  | ├─────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
  | │     WA_VERSION      │                                                                 '2.2019.6'                                                                  │
  | │       PAGE_UA       │ 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36' │
  | │ WA_AUTOMATE_VERSION │                                                                  '1.9.14'                                                                   │
  | │   BROWSER_VERSION   │                                                       'HeadlessChrome/81.0.4044.138'                                                        │
  | └─────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
  | - WAPI injected
  | - Authenticating
  | - Authenticated
  | - Reinjecting api
  | - WAPI Reinjected
  | - Checking if session is valid
  | - Whatsapp is ready
  | (node:1) UnhandledPromiseRejectionWarning: TypeError: fn is not a function
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:250:104)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._processQueue (/home/node/webapp/node_modules/p-queue/dist/index.js:229:21)
  | at PQueue.start (/home/node/webapp/node_modules/p-queue/dist/index.js:283:14)
  | at start (/home/node/webapp/src/open-wa.js:113:17)
  | at processTicksAndRejections (internal/process/task_queues.js:97:5)
  | at async createSession (/home/node/webapp/src/open-wa.js:55:3)
  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode ). (rejection id: 1)

  | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  | (node:1) UnhandledPromiseRejectionWarning: TypeError: fn is not a function
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:250:104)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._processQueue (/home/node/webapp/node_modules/p-queue/dist/index.js:229:21)
  | at PQueue.start (/home/node/webapp/node_modules/p-queue/dist/index.js:283:14)
  | at start (/home/node/webapp/src/open-wa.js:113:17)
  | at processTicksAndRejections (internal/process/task_queues.js:97:5)
  | at async createSession (/home/node/webapp/src/open-wa.js:55:3)
  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode ). (rejection id: 2)

  | (node:1) UnhandledPromiseRejectionWarning: TypeError: fn is not a function
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:250:104)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._processQueue (/home/node/webapp/node_modules/p-queue/dist/index.js:229:21)
  | at PQueue.start (/home/node/webapp/node_modules/p-queue/dist/index.js:283:14)
  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode ). (rejection id: 3)

  | (node:1) UnhandledPromiseRejectionWarning: TypeError: fn is not a function
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:250:104)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode ). (rejection id: 4)

  | (node:1) UnhandledPromiseRejectionWarning: TypeError: fn is not a function
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:250:104)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode ). (rejection id: 5)

  | (node:1) UnhandledPromiseRejectionWarning: TypeError: fn is not a function
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:250:104)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode ). (rejection id: 6)

  | (node:1) UnhandledPromiseRejectionWarning: TypeError: fn is not a function
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:250:104)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode ). (rejection id: 7)

  | (node:1) UnhandledPromiseRejectionWarning: TypeError: fn is not a function
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:250:104)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode ). (rejection id: 8)

  | (node:1) UnhandledPromiseRejectionWarning: TypeError: fn is not a function
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:250:104)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode ). (rejection id: 9)

  | (node:1) UnhandledPromiseRejectionWarning: TypeError: fn is not a function
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:250:104)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode ). (rejection id: 10)

  | (node:1) UnhandledPromiseRejectionWarning: TypeError: fn is not a function
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:250:104)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode ). (rejection id: 11)

  | (node:1) UnhandledPromiseRejectionWarning: TypeError: fn is not a function
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:250:104)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode ). (rejection id: 12)

  | (node:1) UnhandledPromiseRejectionWarning: TypeError: fn is not a function
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:250:104)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode ). (rejection id: 13)

  | (node:1) UnhandledPromiseRejectionWarning: TypeError: fn is not a function
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:250:104)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | at PQueue._tryToStartAnother (/home/node/webapp/node_modules/p-queue/dist/index.js:198:38)
  | at PQueue._next (/home/node/webapp/node_modules/p-queue/dist/index.js:146:14)
  | at run (/home/node/webapp/node_modules/p-queue/dist/index.js:261:22)
  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode ). (rejection id: 14)

  | Resposta do bot enviada para number@c.us
  | Resposta do bot enviada para number@c.us
  | Resposta do bot enviada para number@c.us
  | Resposta do bot enviada para number@c.us
  | Resposta do bot enviada para number@c.us
  | Resposta do bot enviada para number@c.us
  | Resposta do bot enviada para number@c.us
  | Resposta do bot enviada para number@c.us
  | Resposta do bot enviada para number@c.us
  | Resposta do bot enviada para number@c.us
  | Resposta do bot enviada para number@c.us
  | Resposta do bot enviada para number@c.us
  | Resposta do bot enviada para number@c.us
  | Resposta do bot enviada para number@c.us
  | Resposta do bot enviada para number@c.us
  | Resposta do bot enviada para number@c.us
  | Resposta do bot enviada para number@c.us
  | Resposta do bot enviada para number@c.us
  | Resposta do bot enviada para number@c.us
  | Resposta do bot enviada para number@c.us
  | Resposta do bot enviada para number@c.us
```

**Steps to Reproduce**
1. Start aplication

**create() code**
This is the code you use to create the client. e.g
```javascript
async function processWPMessage(message) {
  if (message.type != "chat" || message.from.includes("@g.us")) {
    return;
  }

  let payload = {
    userId: message.from,
    message: message.body,
    driver: "web",
  };

  axios
    .post(process.env.BOT_URL, payload)
    .then(function (response) {
      if (response.data.messages && response.data.messages.length) {
        response.data.messages.forEach((m) => {
          globalClient.sendText(message.from, m.text);
          console.log("Resposta do bot enviada para " + message.from);
        });
      }
    })
    .catch(function (e) {
      console.log(e);
      return Promise.reject("Erro ao enviar mensagem!");
    });

  return true;
}

const processMessage = (message) => queue.add(processWPMessage(message));

async function start(client) {
  try {
    globalClient = client;

    const unreadMessages = await client.getAllUnreadMessages();
    unreadMessages.forEach(processMessage);

    await client.onMessage(processMessage);

    await client.onStateChanged((state) => {
      console.log("statechanged", state);
      if (state === "CONFLICT") client.forceRefocus();
    });

    await queue.start();
  } catch (error) {
    console.log("Erro no método start", error);
  }
}

async function initSessions() {
  const sessionsFile = path.join("sessions", SESSION_NAME + ".json");

  if (fs.existsSync(sessionsFile)) {
    let sessionData = JSON.parse(fs.readFileSync(sessionsFile));

    createSession(sessionData).catch((e) => {
      console.log("Erro ao inicializar sessões...", e);
    });
  }
}

initSessions();
```

**Expected behavior**
Dont show error?

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: '2.2019.6' ,
  PAGE_UA: 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
  WA_AUTOMATE_VERSION:  '1.9.14' ,
  BROWSER_VERSION: 'HeadlessChrome/81.0.4044.138'
}
```

**Host (please complete the following information):**
 - OS: Linux

**Additional context**
Tt is also occurring to bring old messages as unread.

**Comment by smashah** [comment]
hmm, @willianmaria  try this:

```javascript
const processWPMessage = async (message) => {
  if (message.type != "chat" || message.from.includes("@g.us")) {
    return;
  }

  let payload = {
    userId: message.from,
    message: message.body,
    driver: "web",
  };

  axios
    .post(process.env.BOT_URL, payload)
    .then(function (response) {
      if (response.data.messages && response.data.messages.length) {
        response.data.messages.forEach((m) => {
          globalClient.sendText(message.from, m.text);
          console.log("Resposta do bot enviada para " + message.from);
        });
      }
    })
    .catch(function (e) {
      console.log(e);
      return Promise.reject("Erro ao enviar mensagem!");
    });

  return true;
}


```

**Comment by willianmaria** [comment]
Same error.
When I comment this block dont get error:
```
const unreadMessages = await client.getAllUnreadMessages();
unreadMessages.forEach(processMessage);
```

**Comment by smashah** [comment]
this is happening because `processMessage` return true, not a function.

This works as it guarantees that an actual function is passed to `queue.add`:

```javascript
const processMessage = (message) => queue.add(()=>processWPMessage(message));
```

also, make sure to await your Axios promise.

This is not an issue with this lib so from now on post questions like these on the discord.

**Comment by willianmaria** [comment]
Hello @smashah !
What is discord link?

**Comment by smashah** [comment]
https://discord.gg/dnpp72a
