### ISSUE TITLE
Problem: After added namespace to tsconfig

### ISSUE THREAD

**Issue by jersonjunior** [open-wa/wa-automate-nodejs#491]
Problem after added namespace to tsconfig:

ts-node demo/index.ts

```
/usr/local/lib/node_modules/ts-node/src/index.ts:434
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
tsconfig.json:89:11 - error TS1005: ',' expected.

89           "namespace"
             ~~~~~~~~~~~

    at createTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:434:12)
    at reportTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:438:19)
    at create (/usr/local/lib/node_modules/ts-node/src/index.ts:449:36)
    at Object.register (/usr/local/lib/node_modules/ts-node/src/index.ts:349:19)
    at main (/usr/local/lib/node_modules/ts-node/src/bin.ts:162:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ts-node/src/bin.ts:513:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

```

**Comment by jersonjunior** [comment]
Lack of comma in "create"

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.9.53](https://github.com/open-wa/wa-automate-nodejs/compare/1.9.52...1.9.53) (2020-05-27)

- Release 1.9.53 [`7a108a4`](https://github.com/open-wa/wa-automate-nodejs/commit/7a108a48b0acd4231553d9b272f19352f0d3d1b2)
- Update tsconfig.json [`24ff607`](https://github.com/open-wa/wa-automate-nodejs/commit/24ff607f73b2ccbc7a9da0ce24a8b47447bea4d6)
- added namespace to tsconfig [`966a62b`](https://github.com/open-wa/wa-automate-nodejs/commit/966a62b97c5d2a9f910ae974ae1ff2acb795d139)
