### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Evaluation failed: SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by razisek** [open-wa/wa-automate-nodejs#498]
**Describe the bug**
(node:2032) UnhandledPromiseRejectionWarning: Error: Evaluation failed: SyntaxError: Unexpected token '<'

**create() code**
This is the code you use to create the client. e.g
```javascript
wa.create('INI_SESSION', {
    useChrome:true,
    headless: false
}).then(client => start(client));
```
**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: '2.2021.4',
  PAGE_UA:  'WhatsApp/2.2019.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36',
  WA_AUTOMATE_VERSION: '1.9.55',
  BROWSER_VERSION: 'HeadlessChrome/81.0.4044.138'
}
```
**Additional context**
getting error like this
```
(node:2032) UnhandledPromiseRejectionWarning: Error: Evaluation failed: SyntaxError: Unexpected token '<'
    at __puppeteer_evaluation_script__:1:32
    at ExecutionContext._evaluateInternal (C:\Users\Administrator\Documents\open-wa\node_modules\puppeteer\lib\ExecutionContext.js:102:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (C:\Users\Administrator\Documents\open-wa\node_modules\puppeteer\lib\ExecutionContext.js:33:16)
  -- ASYNC --
    at ExecutionContext.<anonymous> (C:\Users\Administrator\Documents\open-wa\node_modules\puppeteer\lib\helper.js:94:19)
    at DOMWorld.evaluate (C:\Users\Administrator\Documents\open-wa\node_modules\puppeteer\lib\DOMWorld.js:89:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\Administrator\Documents\open-wa\node_modules\puppeteer\lib\helper.js:94:19)
    at Page.evaluate (C:\Users\Administrator\Documents\open-wa\node_modules\puppeteer\lib\Page.js:591:14)
    at Page.<anonymous> (C:\Users\Administrator\Documents\open-wa\node_modules\puppeteer\lib\helper.js:95:27)
    at Object.<anonymous> (C:\Users\Administrator\Documents\open-wa\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:305:39)
    at step (C:\Users\Administrator\Documents\open-wa\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:63:23)
    at Object.next (C:\Users\Administrator\Documents\open-wa\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:44:53)
    at fulfilled (C:\Users\Administrator\Documents\open-wa\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:35:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2032) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2032) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mrbarnk** [comment]
Same here .

**Comment by smashah** [comment]
Roll back for now I'll look into it

**Comment by smashah** [comment]
This is an issue when evaluating the license key response and I cant recreate with your instructions. Please share your license keys with me on the discord to resolve this in #license
