### ISSUE TITLE
SendImage, sendFile, sendFileAsUrl is no longer working.

### ISSUE THREAD

**Issue by mrbarnk** [open-wa/wa-automate-nodejs#500]
**Describe the bug**
{ status: true, message: 'Message sent.' }
0|index  | Something went wrong Error: Evaluation failed: TypeError: Cannot read property 'includes' of undefined

**Steps to Reproduce**

**create() code**

the normal create function without license.

```javascript
create(...)
```

**Expected behavior**

The file is not going to send but shows this error.
`
 Something went wrong Error: Evaluation failed: TypeError: Cannot read property 'includes' of undefined                      
     at Object.window.WAPI.sendImage (/root/waabot/node_modules/@open-wa/wa-automate/dist/lib/wapi.js:1476:16)               
     at __puppeteer_evaluation_script__:3:41                                                                                 
     at ExecutionContext._evaluateInternal (/root/waabot/node_modules/puppeteer/lib/ExecutionContext.js:102:19)              
     at runMicrotasks (<anonymous>)                                                                                          
     at processTicksAndRejections (internal/process/task_queues.js:97:5)                                                     
     at ExecutionContext.evaluate (/root/waabot/node_modules/puppeteer/lib/ExecutionContext.js:33:16)                        
   -- ASYNC --                                                                                                               
     at ExecutionContext.<anonymous> (/root/waabot/node_modules/puppeteer/lib/helper.js:94:19)                               
     at DOMWorld.evaluate (/root/waabot/node_modules/puppeteer/lib/DOMWorld.js:89:24)                                        
     at runMicrotasks (<anonymous>)                                                                                          
     at processTicksAndRejections (internal/process/task_queues.js:97:5)                                                     
   -- ASYNC --                                                                                                               
     at Frame.<anonymous> (/root/waabot/node_modules/puppeteer/lib/helper.js:94:19)                                          
     at Page.evaluate (/root/waabot/node_modules/puppeteer/lib/Page.js:591:14)                                               
     at Page.<anonymous> (/root/waabot/node_modules/puppeteer/lib/helper.js:95:27)                                           
     at Client.<anonymous> (/root/waabot/node_modules/@open-wa/wa-automate/dist/api/Client.js:508:50)                        
     at step (/root/waabot/node_modules/@open-wa/wa-automate/dist/api/Client.js:44:23)                                       
     at Object.next (/root/waabot/node_modules/@open-wa/wa-automate/dist/api/Client.js:25:53)                                
     at /root/waabot/node_modules/@open-wa/wa-automate/dist/api/Client.js:19:71                                              
     at new Promise (<anonymous>)                                                                                            
     at __awaiter (/root/waabot/node_modules/@open-wa/wa-automate/dist/api/Client.js:15:12)                                  
     at Client.sendImage (/root/waabot/node_modules/@open-wa/wa-automate/dist/api/Client.js:505:16)                          
     at Client.<anonymous> (/root/waabot/node_modules/@open-wa/wa-automate/dist/api/Client.js:559:33)                        
     at step (/root/waabot/node_modules/@open-wa/wa-automate/dist/api/Client.js:44:23)                                       
     at Object.next (/root/waabot/node_modules/@open-wa/wa-automate/dist/api/Client.js:25:53)                                
     at /root/waabot/node_modules/@open-wa/wa-automate/dist/api/Client.js:19:71                                              
     at new Promise (<anonymous>)                                                                                            
     at __awaiter (/root/waabot/node_modules/@open-wa/wa-automate/dist/api/Client.js:15:12)                                  
   -- ASYNC --                                                                                                               
     at Page.<anonymous> (/root/waabot/node_modules/puppeteer/lib/helper.js:94:19)                                           
     at Client.<anonymous> (/root/waabot/node_modules/@open-wa/wa-automate/dist/api/Client.js:508:50)                        
     at step (/root/waabot/node_modules/@open-wa/wa-automate/dist/api/Client.js:44:23)                                       
     at Object.next (/root/waabot/node_modules/@open-wa/wa-automate/dist/api/Client.js:25:53)                                
     at /root/waabot/node_modules/@open-wa/wa-automate/dist/api/Client.js:19:71                                              
     at new Promise (<anonymous>)                                                                                            
     at __awaiter (/root/waabot/node_modules/@open-wa/wa-automate/dist/api/Client.js:15:12)                                  
     at Client.sendImage (/root/waabot/node_modules/@open-wa/wa-automate/dist/api/Client.js:505:16)                          
     at Client.<anonymous> (/root/waabot/node_modules/@open-wa/wa-automate/dist/api/Client.js:559:33)                        
     at step (/root/waabot/node_modules/@open-wa/wa-automate/dist/api/Client.js:44:23)                                       
     at Object.next (/root/waabot/node_modules/@open-wa/wa-automate/dist/api/Client.js:25:53)                                
     at /root/waabot/node_modules/@open-wa/wa-automate/dist/api/Client.js:19:71                                              
     at new Promise (<anonymous>)                                                                                            
     at __awaiter (/root/waabot/node_modules/@open-wa/wa-automate/dist/api/Client.js:15:12)                                  
     at Client.sendFile (/root/waabot/node_modules/@open-wa/wa-automate/dist/api/Client.js:557:16)                           
     at Client.<anonymous> (/root/waabot/node_modules/@open-wa/wa-automate/dist/api/Client.js:620:41)                        
`

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
   WA_VERSION      │                                                                  '2.2021.4'                                                                   │
0|index  | │       PAGE_UA       │ 'WhatsApp/2.2019.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36' │
0|index  | │ WA_AUTOMATE_VERSION │                                                                   '1.9.56'                                                                    │
0|index  | │   BROWSER_VERSION   │                                                         'HeadlessChrome/83.0.4103.0'
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS: Ubuntu 20

**Additional context**

**Comment by smashah** [comment]
@mrbarnk this error is because chat id is undefined. Unable to help as you've provided no code.

**Comment by mrbarnk** [comment]
ok right now, it has been fixed. but images are not sending right now. although no error is showing.

`clientsArray.names[body.session_id].sendFileFromUrl(body.to.replace('+', '') + '@c.us', body.file.fileUrl, fileName, fileNameAsCaption)`

**Comment by mrbarnk** [comment]
Hi @smashah , I await your response on this.
