### ISSUE TITLE
reply method throws an evaluation error

### ISSUE THREAD

**Issue by UnKnoWn-Consortium** [open-wa/wa-automate-nodejs#525]
**Describe the bug**
```reply``` method throws an evaluation error

**Steps to Reproduce**
Try ```reply``` to any incoming message, the error shall be thrown. 

**create() code**
This is the code you use to create the client. e.g
```javascript
create(...)
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: 2302.2,
  PAGE_UA: WhatsApp/0.4.613 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36,
  WA_AUTOMATE_VERSION: 1.9.63,
  BROWSER_VERSION: Chrome 83.0.4103.97
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - Android 10 + Ubuntu 16.04

**Additional context**
Trace stack: 
```
Error: Evaluation failed: Error: MsgKey error: something's not a wid: from:<PHONE_NUMBER>@c.us to:<PHONE_NUMBER>@c.us p:undefined
  at new e (https://web.whatsapp.com/app2.13be54c9099a5680d99c.js:2:777821)
  at Object.t.createQuotedMsg (https://web.whatsapp.com/app2.13be54c9099a5680d99c.js:2:628401)
  at t.value [as _getQuotedMsgObj] (https://web.whatsapp.com/app2.13be54c9099a5680d99c.js:2:570190)
  at t.value [as quotedMsgObj] (https://web.whatsapp.com/app2.13be54c9099a5680d99c.js:2:569415)
  at Object.window.WAPI._serializeMessageObj (/var/nodejs/whatsapp-service/node_modules/@open-wa/wa-automate/dist/lib/wapi.js:167:27)
  at Object.window.WAPI.processMessageObj (/var/nodejs/whatsapp-service/node_modules/@open-wa/wa-automate/dist/lib/wapi.js:691:21)
  at t.<anonymous> (/var/nodejs/whatsapp-service/node_modules/@open-wa/wa-automate/dist/lib/wapi.js:1237:35)
  at t.value (https://web.whatsapp.com/app.5be2ce7458b30031ac49.js:1:396831)
  at t.value (https://web.whatsapp.com/app.5be2ce7458b30031ac49.js:1:395192)
  at t.value (https://web.whatsapp.com/app2.13be54c9099a5680d99c.js:2:1776017)
  at ExecutionContext._evaluateInternal (/var/nodejs/whatsapp-service/node_modules/puppeteer/lib/ExecutionContext.js:102:19)
  at processTicksAndRejections (internal/process/task_queues.js:97:5)
  at async ExecutionContext.evaluate (/var/nodejs/whatsapp-service/node_modules/puppeteer/lib/ExecutionContext.js:33:16)
-- ASYNC --
  at ExecutionContext.<anonymous> (/var/nodejs/whatsapp-service/node_modules/puppeteer/lib/helper.js:94:19)
  at DOMWorld.evaluate (/var/nodejs/whatsapp-service/node_modules/puppeteer/lib/DOMWorld.js:89:24)
  at processTicksAndRejections (internal/process/task_queues.js:97:5)
-- ASYNC --
  at Frame.<anonymous> (/var/nodejs/whatsapp-service/node_modules/puppeteer/lib/helper.js:94:19)
  at Page.evaluate (/var/nodejs/whatsapp-service/node_modules/puppeteer/lib/Page.js:612:14)
  at Page.<anonymous> (/var/nodejs/whatsapp-service/node_modules/puppeteer/lib/helper.js:95:27)
  at Client.<anonymous> (/var/nodejs/whatsapp-service/node_modules/@open-wa/wa-automate/dist/api/Client.js:560:50)
  at step (/var/nodejs/whatsapp-service/node_modules/@open-wa/wa-automate/dist/api/Client.js:44:23)
  at Object.next (/var/nodejs/whatsapp-service/node_modules/@open-wa/wa-automate/dist/api/Client.js:25:53)
  at /var/nodejs/whatsapp-service/node_modules/@open-wa/wa-automate/dist/api/Client.js:19:71
  at new Promise (<anonymous>)
  at __awaiter (/var/nodejs/whatsapp-service/node_modules/@open-wa/wa-automate/dist/api/Client.js:15:12)
  at Client.reply (/var/nodejs/whatsapp-service/node_modules/@open-wa/wa-automate/dist/api/Client.js:551:16)
  at Readable.<anonymous>```

**Comment by smashah** [comment]
Are you sending the message object as third parameter? what is the message you're quoting? does this happen every time? Needs much more detail.

**Comment by UnKnoWn-Consortium** [comment]
@smashah Yes I am sending the whole message object. The message object is directly from the ```onMessage``` method. And yes it happens on every occasion. I have not yet tested it at the minimal ping-pong setting though.

**Comment by smashah** [comment]
@UnKnoWn-Consortium try sending only the message id instead of the whole object.

**Comment by UnKnoWn-Consortium** [comment]
@smashah Oh it works with ```message.id```. Thanks for your help.

**Comment by smashah** [comment]
Np. I'll change it so it only takes the I'd from now on. Thanks
