### ISSUE TITLE
Error Send IMAGE HELP

### ISSUE THREAD

**Issue by contatodct** [open-wa/wa-automate-nodejs#540]
(node:21860) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property '1' of null
    at Object.window.WAPI.base64ImageToFile (/var/www/anapolis/admin/node_modules/@open-wa/wa-automate/dist/lib/wapi.js:1662:39)
    at /var/www/anapolis/admin/node_modules/@open-wa/wa-automate/dist/lib/wapi.js:1513:37
    at H (https://web.whatsapp.com/app.5be2ce7458b30031ac49.js:1:1011872)
    at MutationObserver.W (https://web.whatsapp.com/app.5be2ce7458b30031ac49.js:1:1011453)
    at ExecutionContext._evaluateInternal (/var/www/anapolis/admin/node_modules/puppeteer/lib/ExecutionContext.js:102:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (/var/www/anapolis/admin/node_modules/puppeteer/lib/ExecutionContext.js:33:16)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/var/www/anapolis/admin/node_modules/puppeteer/lib/helper.js:94:19)
    at DOMWorld.evaluate (/var/www/anapolis/admin/node_modules/puppeteer/lib/DOMWorld.js:89:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
  -- ASYNC --
    at Frame.<anonymous> (/var/www/anapolis/admin/node_modules/puppeteer/lib/helper.js:94:19)
    at Page.evaluate (/var/www/anapolis/admin/node_modules/puppeteer/lib/Page.js:612:14)
    at Page.<anonymous> (/var/www/anapolis/admin/node_modules/puppeteer/lib/helper.js:95:27)
    at Client.<anonymous> (/var/www/anapolis/admin/node_modules/@open-wa/wa-automate/dist/api/Client.js:561:50)
    at step (/var/www/anapolis/admin/node_modules/@open-wa/wa-automate/dist/api/Client.js:44:23)
    at Object.next (/var/www/anapolis/admin/node_modules/@open-wa/wa-automate/dist/api/Client.js:25:53)
    at /var/www/anapolis/admin/node_modules/@open-wa/wa-automate/dist/api/Client.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/var/www/anapolis/admin/node_modules/@open-wa/wa-automate/dist/api/Client.js:15:12)
    at Client.sendImage (/var/www/anapolis/admin/node_modules/@open-wa/wa-automate/dist/api/Client.js:558:16)
  -- ASYNC --
    at Page.<anonymous> (/var/www/anapolis/admin/node_modules/puppeteer/lib/helper.js:94:19)
    at Client.<anonymous> (/var/www/anapolis/admin/node_modules/@open-wa/wa-automate/dist/api/Client.js:561:50)
    at step (/var/www/anapolis/admin/node_modules/@open-wa/wa-automate/dist/api/Client.js:44:23)
    at Object.next (/var/www/anapolis/admin/node_modules/@open-wa/wa-automate/dist/api/Client.js:25:53)
    at /var/www/anapolis/admin/node_modules/@open-wa/wa-automate/dist/api/Client.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/var/www/anapolis/admin/node_modules/@open-wa/wa-automate/dist/api/Client.js:15:12)
    at Client.sendImage (/var/www/anapolis/admin/node_modules/@open-wa/wa-automate/dist/api/Client.js:558:16)
    at Timeout._onTimeout (/var/www/anapolis/admin/index.js:389:20)
    at listOnTimeout (internal/timers.js:531:17)
(node:21860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21860) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mcroni** [comment]
kindly post the actual code that does the sending

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️
