### ISSUE TITLE
Rejected TimeoutError

### ISSUE THREAD

**Issue by mcroni** [open-wa/wa-automate-nodejs#541]
**Describe the bug**
I get this error after scanning the QR code and waiting for initialization

**Steps to Reproduce**

**create() code**
This is the code you use to create the client. e.g
```javascript
create('v3',
    {
        headless: false,
        // executablePath: '/usr/bin/google-chrome',
        executablePath: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
    },'WhatsApp/0.4.315 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36')
    .then(client => start(client)).catch((e)=>{
    console.log("Rejected",e);
})
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
- Initializing WA
Rejected TimeoutError: Navigation timeout of 30000 ms exceeded
    at C:\Users\MCRONI\Desktop\homechow\node_modules\puppeteer\lib\LifecycleWatcher.js:100:111
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\MCRONI\Desktop\homechow\node_modules\puppeteer\lib\helper.js:94:19)
    at Page.goto (C:\Users\MCRONI\Desktop\homechow\node_modules\puppeteer\lib\Page.js:485:53)
    at Page.<anonymous> (C:\Users\MCRONI\Desktop\homechow\node_modules\puppeteer\lib\helper.js:95:27)
    at Object.<anonymous> (C:\Users\MCRONI\Desktop\homechow\node_modules\@open-wa\wa-automate\dist\controllers\browser.js:146:44)
    at step (C:\Users\MCRONI\Desktop\homechow\node_modules\@open-wa\wa-automate\dist\controllers\browser.js:63:23)
    at Object.next (C:\Users\MCRONI\Desktop\homechow\node_modules\@open-wa\wa-automate\dist\controllers\browser.js:44:53)
    at fulfilled (C:\Users\MCRONI\Desktop\homechow\node_modules\@open-wa\wa-automate\dist\controllers\browser.js:35:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  name: 'TimeoutError'
}

```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**

**Additional context**

**Comment by smashah** [comment]
Thanks for filling this out.

Can you use the single parameter config and get rid of the ua and try again.

```javascript
create({
        sessionId:"v3",
        headless: false,
        // executablePath: '/usr/bin/google-chrome',
        executablePath: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
    })
```

**Comment by smashah** [comment]
@mcroni is it working?

**Comment by smashah** [comment]
@mcroni I'll close this for now. Report back if there are still issues.
