### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error

### ISSUE THREAD

**Issue by andazlan** [open-wa/wa-automate-nodejs#587]
I try to deploy this library on server, when i run it at the first time, i got this error

`UnhandledPromiseRejectionWarning: Error
    at new LauncherError (/home/project/myproject/node_modules/chrome-launcher/dist/utils.js:37:22)
    at new ChromePathNotSetError (/home/project/myproject/node_modules/chrome-launcher/dist/utils.js:44:9)
    at Object.linux (/home/project/myproject/node_modules/chrome-launcher/dist/chrome-finder.js:111:15)
    at Function.getInstallations (/home/project/myproject/node_modules/chrome-launcher/dist/chrome-launcher.js:128:51)
    at /home/project/myproject/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:194:73
    at step (/home/project/myproject/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:63:23)
    at Object.next (/home/project/myproject/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:44:53)
    at /home/project/myproject/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:38:71
    at new Promise (<anonymous>)
    at __awaiter (/home/project/myproject/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:34:12)`

**Comment by andazlan** [comment]
i forget to install chrome browser, my bad :D
