### ISSUE TITLE
Send A Msg for a new Contact(saved in phone) /Clear and Delete Chat/ Talk First time

### ISSUE THREAD

**Issue by DeLuca92** [open-wa/wa-automate-nodejs#614]
**Describe the bug**
Send a msg to a new number or if u delete the chat.
If u talked with the person the msg will send, but if u delete a chat U can't send a msg again
I test for a new number/cleared chat a few weeks ago and  it worked

The  msg will not send

**Steps to Reproduce**
1. Send a text by API

**create() code**
```
{
     "args" : 
     	{
      	  "to": "55XXXXXX5829@c.us",
          "content":"Hello, this is a test!"
     	}
    
}

{
    "success": false,
    "error": {}
}
```

**Expected behavior**
expected  the msg sent

**DEBUG INFO**
```
middleware -> error Error: Evaluation failed: t
    at ExecutionContext._evaluateInternal (/home/wa-whats/node_modules/puppeteer/lib/ExecutionContext.js:102:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/home/wa-whats/node_modules/puppeteer/lib/helper.js:116:19)
    at DOMWorld.evaluate (/home/wa-whats/node_modules/puppeteer/lib/DOMWorld.js:108:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/home/wa-whats/node_modules/puppeteer/lib/helper.js:116:19)
    at Page.evaluate (/home/wa-whats/node_modules/puppeteer/lib/Page.js:680:14)
    at Page.<anonymous> (/home/wa-whats/node_modules/puppeteer/lib/helper.js:117:27)
    at Client.<anonymous> (/home/wa-whats/node_modules/@open-wa/wa-automate/dist/api/Client.js:296:66)
    at step (/home/wa-whats/node_modules/@open-wa/wa-automate/dist/api/Client.js:44:23)
    at Object.next (/home/wa-whats/node_modules/@open-wa/wa-automate/dist/api/Client.js:25:53)
    at /home/wa-whats/node_modules/@open-wa/wa-automate/dist/api/Client.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/home/wa-whats/node_modules/@open-wa/wa-automate/dist/api/Client.js:15:12)
    at Client.pup (/home/wa-whats/node_modules/@open-wa/wa-automate/dist/api/Client.js:281:16)
  -- ASYNC --
    at Page.<anonymous> (/home/wa-whats/node_modules/puppeteer/lib/helper.js:116:19)
    at Client.<anonymous> (/home/wa-whats/node_modules/@open-wa/wa-automate/dist/api/Client.js:296:66)
    at step (/home/wa-whats/node_modules/@open-wa/wa-automate/dist/api/Client.js:44:23)
    at Object.next (/home/wa-whats/node_modules/@open-wa/wa-automate/dist/api/Client.js:25:53)
    at /home/wa-whats/node_modules/@open-wa/wa-automate/dist/api/Client.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/home/wa-whats/node_modules/@open-wa/wa-automate/dist/api/Client.js:15:12)
    at Client.pup (/home/wa-whats/node_modules/@open-wa/wa-automate/dist/api/Client.js:281:16)
    at Client.<anonymous> (/home/wa-whats/node_modules/@open-wa/wa-automate/dist/api/Client.js:686:45)
    at step (/home/wa-whats/node_modules/@open-wa/wa-automate/dist/api/Client.js:44:23)
```

```
Debug Info {
  WA_VERSION:  '2.2027.9' ,
  PAGE_UA: 'WhatsApp/2.2019.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36'
  WA_AUTOMATE_VERSION:  '1.9.91'
  BROWSER_VERSION: HeadlessChrome/81.0.4044.138
}
```

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.9.93](https://github.com/open-wa/wa-automate-nodejs/compare/1.9.92...1.9.93) (2020-07-02)

- Release 1.9.93 [`5084852`](https://github.com/open-wa/wa-automate-nodejs/commit/50848523d1475393358225fd2cad78ee540ef93b)
- Fix: insances connected through WS will now `kill` properly [`69c0afa`](https://github.com/open-wa/wa-automate-nodejs/commit/69c0afa329ea1102e180437dc7eb8acd423dd524)
- Messaging existing contacts without chats is now more reliable #614 [`2125f54`](https://github.com/open-wa/wa-automate-nodejs/commit/2125f548904bfcc0c3beab5576b58b1d50461903)

**Comment by smashah** [comment]
In the upcoming release, you will be more reliably be able to send messages to existing contacts and chats that have been deleted (with existing contacts). It will not allow reopening a chat (after it is deleted or cleared) with a contact that is NOT SAVED. So make sure to never delete a chat with a contact that you have not saved.

**Comment by DeLuca92** [comment]
Thx, bro 👍  😍😎😁
