### ISSUE TITLE
Send a image / file / to a non contact

### ISSUE THREAD

**Issue by jesusvalverde** [open-wa/wa-automate-nodejs#684]
**Describe the bug**
Send a image / file / to a non contact user with non license.

**Steps to Reproduce**
```javascript
const wa = require('@open-wa/wa-automate');
const axios = require('axios');
const fs = require('fs');
const mime = require('mime-types');
wa.create('test',{ headless: false,  useChrome: true, cacheEnabled:false,disableSpins: true,  }).then(client => start(client));
async function start(client) {
  console.log("1 de 3 -  Enviando texto " + await client.sendText('506CONCATUSER@c.us', 'Hello la prueba llega'));
   console.log("2 de 3 -  Enviando File URL" + await client.sendFileFromUrl('506CONCATUSER@c.us', 'https://test.io/wp-content/uploads/2019/02/testIO-logo-rgb-2.png', 'test.png', 'Caption', '','', true));
  console.log("3 de 3 -  Enviando File URL" + await client.sendFileFromUrl('506NONCONTACT@c.us', 'https://test.io/wp-content/uploads/2019/02/testIO-logo-rgb-2.png', 'test.png', 'Caption', '','', true));
}
```

**Expected behavior**
text 1 and image ok... 3 for sure not send , 'cos not a valid license,  but  not a screen full of code "error" more "non a contact" or something more user frendly

**DEBUG INFO**
```bash
│     WA_VERSION      │                                                                  '2.2029.4'                                                                   │
│       PAGE_UA       │ 'WhatsApp/2.2029.4 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                   '1.9.105'                                                                   │
│   BROWSER_VERSION   │                                                         'HeadlessChrome/83.0.4103.0'                                                          
```
**Screenshots**
```
Something went wrong Error: Evaluation failed: t
    at ExecutionContext._evaluateInternal (/Users/jesusvalverde/what/node_modules/puppeteer/lib/cjs/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/Users/jesusvalverde/what/node_modules/puppeteer/lib/cjs/common/ExecutionContext.js:106:16)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/jesusvalverde/what/node_modules/puppeteer/lib/cjs/common/helper.js:109:19)
    at DOMWorld.evaluate (/Users/jesusvalverde/what/node_modules/puppeteer/lib/cjs/common/DOMWorld.js:84:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at Frame.<anonymous> (/Users/jesusvalverde/what/node_modules/puppeteer/lib/cjs/common/helper.js:109:19)
    at Page.evaluate (/Users/jesusvalverde/what/node_modules/puppeteer/lib/cjs/common/Page.js:883:14)
    at Page.<anonymous> (/Users/jesusvalverde/what/node_modules/puppeteer/lib/cjs/common/helper.js:110:27)
    at Client.<anonymous> (/Users/jesusvalverde/what/node_modules/@open-wa/wa-automate/dist/api/Client.js:299:67)
    at step (/Users/jesusvalverde/what/node_modules/@open-wa/wa-automate/dist/api/Client.js:44:23)
    at Object.next (/Users/jesusvalverde/what/node_modules/@open-wa/wa-automate/dist/api/Client.js:25:53)
    at /Users/jesusvalverde/what/node_modules/@open-wa/wa-automate/dist/api/Client.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jesusvalverde/what/node_modules/@open-wa/wa-automate/dist/api/Client.js:15:12)
    at Client.pup (/Users/jesusvalverde/what/node_modules/@open-wa/wa-automate/dist/api/Client.js:284:16)
  -- ASYNC --
    at Page.<anonymous> (/Users/jesusvalverde/what/node_modules/puppeteer/lib/cjs/common/helper.js:109:19)
    at Client.<anonymous> (/Users/jesusvalverde/what/node_modules/@open-wa/wa-automate/dist/api/Client.js:299:67)
    at step (/Users/jesusvalverde/what/node_modules/@open-wa/wa-automate/dist/api/Client.js:44:23)
    at Object.next (/Users/jesusvalverde/what/node_modules/@open-wa/wa-automate/dist/api/Client.js:25:53)
    at /Users/jesusvalverde/what/node_modules/@open-wa/wa-automate/dist/api/Client.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jesusvalverde/what/node_modules/@open-wa/wa-automate/dist/api/Client.js:15:12)
    at Client.pup (/Users/jesusvalverde/what/node_modules/@open-wa/wa-automate/dist/api/Client.js:284:16)
    at Client.<anonymous> (/Users/jesusvalverde/what/node_modules/@open-wa/wa-automate/dist/api/Client.js:772:45)
    at step (/Users/jesusvalverde/what/node_modules/@open-wa/wa-automate/dist/api/Client.js:44:23)
(node:10635) UnhandledPromiseRejectionWarning: Error: Evaluation failed: t
    at ExecutionContext._evaluateInternal (/Users/jesusvalverde/what/node_modules/puppeteer/lib/cjs/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/Users/jesusvalverde/what/node_modules/puppeteer/lib/cjs/common/ExecutionContext.js:106:16)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/jesusvalverde/what/node_modules/puppeteer/lib/cjs/common/helper.js:109:19)
    at DOMWorld.evaluate (/Users/jesusvalverde/what/node_modules/puppeteer/lib/cjs/common/DOMWorld.js:84:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at Frame.<anonymous> (/Users/jesusvalverde/what/node_modules/puppeteer/lib/cjs/common/helper.js:109:19)
    at Page.evaluate (/Users/jesusvalverde/what/node_modules/puppeteer/lib/cjs/common/Page.js:883:14)
    at Page.<anonymous> (/Users/jesusvalverde/what/node_modules/puppeteer/lib/cjs/common/helper.js:110:27)
    at Client.<anonymous> (/Users/jesusvalverde/what/node_modules/@open-wa/wa-automate/dist/api/Client.js:299:67)
    at step (/Users/jesusvalverde/what/node_modules/@open-wa/wa-automate/dist/api/Client.js:44:23)
    at Object.next (/Users/jesusvalverde/what/node_modules/@open-wa/wa-automate/dist/api/Client.js:25:53)
    at /Users/jesusvalverde/what/node_modules/@open-wa/wa-automate/dist/api/Client.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jesusvalverde/what/node_modules/@open-wa/wa-automate/dist/api/Client.js:15:12)
    at Client.pup (/Users/jesusvalverde/what/node_modules/@open-wa/wa-automate/dist/api/Client.js:284:16)
  -- ASYNC --
    at Page.<anonymous> (/Users/jesusvalverde/what/node_modules/puppeteer/lib/cjs/common/helper.js:109:19)
    at Client.<anonymous> (/Users/jesusvalverde/what/node_modules/@open-wa/wa-automate/dist/api/Client.js:299:67)
    at step (/Users/jesusvalverde/what/node_modules/@open-wa/wa-automate/dist/api/Client.js:44:23)
    at Object.next (/Users/jesusvalverde/what/node_modules/@open-wa/wa-automate/dist/api/Client.js:25:53)
    at /Users/jesusvalverde/what/node_modules/@open-wa/wa-automate/dist/api/Client.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jesusvalverde/what/node_modules/@open-wa/wa-automate/dist/api/Client.js:15:12)
    at Client.pup (/Users/jesusvalverde/what/node_modules/@open-wa/wa-automate/dist/api/Client.js:284:16)
    at Client.<anonymous> (/Users/jesusvalverde/what/node_modules/@open-wa/wa-automate/dist/api/Client.js:772:45)
    at step (/Users/jesusvalverde/what/node_modules/@open-wa/wa-automate/dist/api/Client.js:44:23)
```

**Host (please complete the following information):**

**Additional context**
Sure if not a issue just something for "more frendly use"

**Comment by smashah** [comment]
@jesusvalverde I think the best solution to this would be to throw an error in the process.

I'll have to go through each `send...` function and fix it.

**Comment by jesusvalverde** [comment]
On more extensive test....

Having a license key and you try to send and image to a non contact user as the first message, not send, and the same t error.  " Error: Evaluation failed: t" and the seems to stop all the code if not using a try / catch ...

If need more test or code just let me know

**Comment by smashah** [comment]
In an upcoming version, this error will not happen, instead, it will log an error via `console.error` and return false if you're trying to send a file to a non contact
