### ISSUE TITLE
[Demo] Error when receiving sticker message type

### ISSUE THREAD

**Issue by rickricardo** [open-wa/wa-automate-nodejs#703]
Hi, I just downloaded the demo and I am making some tests with stickers.
I could successfully send stickers with sendStickerfromUrl().
I could also receive images and the demo worked perfectly sending back the image as sticker.

But when I send a sticker to the bot it presents an error trying to read it:

TCL: start -> error Error: message is missing critical data needed to download the file.
    at <path>/wa_automate/wa-automate-nodejs/node_modules/@open-wa/wa-decrypt/dist/decrypt.js:83:27
    at step (<path>/wa_automate/wa-automate-nodejs/node_modules/@open-wa/wa-decrypt/dist/decrypt.js:44:23)
    at Object.next (<path>/wa_automate/wa-automate-nodejs/node_modules/@open-wa/wa-decrypt/dist/decrypt.js:25:53)
    at <path>/wa_automate/wa-automate-nodejs/node_modules/@open-wa/wa-decrypt/dist/decrypt.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (<path>/wa_automate/wa-automate-nodejs/node_modules/@open-wa/wa-decrypt/dist/decrypt.js:15:12)
    at Object.exports.decryptMedia (<path>/wa_automate/wa-automate-nodejs/node_modules/@open-wa/wa-decrypt/dist/decrypt.js:67:71)
    at <path>/wa_automate/wa-automate-nodejs/demo/index.ts:106:27
    at step (<path>/wa_automate/wa-automate-nodejs/demo/index.ts:33:23)
    at Object.next (<path>/wa_automate/wa-automate-nodejs/demo/index.ts:14:53)

**Comment by smashah** [comment]
@rickricardo you need an [Insiders Key](https://open-wa.github.io/wa-automate-nodejs/pages/The%20Client/licensed-features.html#insiders-features) to use `getStickerDecryptable` (https://open-wa.github.io/wa-automate-nodejs/classes/client.html#getstickerdecryptable). If you don't have a valid key it will return false which will cause decryption to throw this error.

**Comment by smashah** [comment]
This has been clarified in the documentation and the demo
