### ISSUE TITLE
Problem sending new messages using Easy API

### ISSUE THREAD

**Issue by silvaartur** [open-wa/wa-automate-nodejs#765]
at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/home/ubuntu/.npm/_npx/1496/lib/node_modules/@open-wa/wa-automate/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
middleware -> error Error: Evaluation failed: TypeError: Cannot read property 'includes' of null
    at Object.window.WAPI.sendMessage (/home/ubuntu/.npm/_npx/1496/lib/node_modules/@open-wa/wa-automate/dist/lib/wapi.js:815:22)
    at __puppeteer_evaluation_script__:4:45
    at ExecutionContext._evaluateInternal (/home/ubuntu/.npm/_npx/1496/lib/node_modules/@open-wa/wa-automate/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)

**Comment by silvaartur** [comment]
Found the problem. Trying to send a message to non WhatsApp number.

Closing because I can check the number before sending.
