### ISSUE TITLE
Bot crashes after some time   (client.reply)

### ISSUE THREAD

**Issue by shubham8550** [open-wa/wa-automate-nodejs#780]
Everything works fine at first but after  fave hours client.reply doesn't work   but it can still listen for new massages. 

### Config
```
const launchConfig = {
    useChrome: true,
    autoRefresh:true,
    headless: true,
   // cacheEnabled:false,
   // executablePath: "/usr/bin/chromium-browser",
  //  customUserAgent:"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36",
  //   cacheEnabled: false,
  //   chromiumArgs: [
  //       '--no-sandbox',
  //       '--disable-setuid-sandbox'
//    ]
};
wa.create(launchConfig).then(client => start(client));

```
**### Logs**

```
                   │
0|server   | ├─────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
0|server   | │     WA_VERSION      │                                                                  '2.2035.14'                                                                  │
0|server   | │       PAGE_UA       │ 'WhatsApp/2.2029.4 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36' │
0|server   | │ WA_AUTOMATE_VERSION │                                                       '2.0.12 UPDATE AVAILABLE: 2.0.13'                                                       │
0|server   | │   BROWSER_VERSION   │                                                        'HeadlessChrome/78.0.3904.108'                                                         │
0|server   | │     SESSION_ID      │                                                                   'session'                                                                   │
0|server   | └─────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
0|server   | Error: Evaluation failed: TypeError: Object prototype may only be an Object or null: undefined
0|server   |     at Function.create (<anonymous>)
0|server   |     at Object.window.WAPI.reply (/home/pi/deploys/aqua-wa-automate/node_modules/@open-wa/wa-automate/dist/lib/wapi.js:1819:26)
0|server   |     at __puppeteer_evaluation_script__:3:41
0|server   |     at ExecutionContext._evaluateInternal (/home/pi/deploys/aqua-wa-automate/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
0|server   |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
0|server   |     at async ExecutionContext.evaluate (/home/pi/deploys/aqua-wa-automate/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
```

**Comment by shubham8550** [comment]
I found reason for this it's because my what's app Android app goes offline because of battery optimization
