### ISSUE TITLE
Cannot Read Property sessionId of undefined

### ISSUE THREAD

**Issue by mashdah** [open-wa/wa-automate-nodejs#854]
**Describe the bug**
when I run the index.js script, I get an error in the form of `Cannot Read Property "sessionId" of undefined`

**Steps to Reproduce**
1. run your app `node index.js`
2. see the error

**Code**
This is usage code
```javascript
const wa = require('@open-wa/wa-automate');

wa.create().then(client => start(client));

function start(client) {
  client.onMessage(message => {
    if (message.body === 'Hi') {
      client.sendText(message.from, '👋 Hello!');
    }
  });
}
```

**Expected behavior**
previously in version 2.0.23 after I run index.js it will bring up the qr code which is ready to be scanned

**Screenshots**
here is the full error

> (node:10036) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'sessionId' of undefined
    at Object.<anonymous> (/home/user/wabot/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:117:44)
    at step (/home/user/wabot/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:63:23)
    at Object.next (/home/user/wabot/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:44:53)
    at fulfilled (/home/user/wabot/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:35:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
(node:10036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10036) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

thanks,

**Comment by mashdah** [comment]
**Added :**
will works when use chrome `create({useChrome: ....})`, but when it default it will return `sessionId` error

**Comment by smashah** [comment]
Please try the latest version

And if it still doesn't work do this

`wa.create({})`

**Comment by mashdah** [comment]
@smashah ya, the latest version will works when it use config object. thanks
