### ISSUE TITLE
The session is invalid. Retrying

### ISSUE THREAD

**Issue by AlessandroSantos** [open-wa/wa-automate-nodejs#861]
After scan the qrcode, the log show:

✓ Authenticate to continue
✓ Loading QR
✓ WAPI Reinjected
✖ The session is invalid. Retrying

(node:7708) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at CDPSession.send (/Users/Shared/projects/wa-automate-server/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:195:35)
    at ExecutionContext._evaluateInternal (/Users/Shared/projects/wa-automate-server/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:200:50)
    at ExecutionContext.evaluate (/Users/Shared/projects/wa-automate-server/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:27)
    at DOMWorld.evaluate (/Users/Shared/projects/wa-automate-server/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:79:24)
(node:7708) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:7708) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by AlessandroSantos** [comment]
Sorry, it was my fault.
I was using an older version.
