### ISSUE TITLE
The reply function causes exceptions

### ISSUE THREAD

**Issue by hbarcellos** [open-wa/wa-automate-nodejs#869]
Here are the two situations that I came across with exceptions in the reply function:

When the chat has no messages and when the chat goes long without any messages.
Even though there are messages from the host in the chat, the exception occurs.

```
 [ERROR] Error: Evaluation failed: TypeError: Object prototype may only be an Object or null: undefined
     at Function.create (<anonymous>)
     at Object.window.WAPI.reply (/app/node_modules/@open-wa/wa-automate/dist/lib/wapi.js:1819:26)
     at __puppeteer_evaluation_script__:3:41
     at ExecutionContext._evaluateInternal (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
     at processTicksAndRejections (internal/process/task_queues.js:97:5)
     at ExecutionContext.evaluate (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
```

Sending a message with sendText before the reply solves the problem.

**Comment by smashah** [comment]
@hbarcellos although it throws an error this isn't really a bug. A normal message is required for most features to work. I guess the solution to this would be to mention in the docs to not run functions on accounts with empty chats/at least have sent 1 normal text first.

**Comment by smashah** [comment]
I've added this to the docs. Closing. Thanks
