### ISSUE TITLE
How to send audios with the sendFile function

### ISSUE THREAD

**Issue by Trobat** [open-wa/wa-automate-nodejs#883]
I am trying to send reproducible audio with the sendFile function but it is returning this error

```
(node:9384) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property '1' of null
    at Object.window.WAPI.base64ImageToFile (C:\Users\Davi\Coding\whassapbot\node_modules\@open-wa\wa-automate\dist\lib\wapi.js:1606:39)
    at Object.window.<computed>.<computed> [as sendImage] (__puppeteer_evaluation_script__:1:42746)
    at __puppeteer_evaluation_script__:3:45
    at ExecutionContext._evaluateInternal (C:\Users\Davi\Coding\whassapbot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at ExecutionContext.evaluate (C:\Users\Davi\Coding\whassapbot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
(node:9384) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9384) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

My code is this:

```
    return client.sendFile(
      message.from,
      path.resolve(__dirname, '../downloads', `${videoId}.mp3`),
      'music.mpeg',
      'a cool music',
      message.quotedMsg,
    );
```

**Comment by smashah** [comment]
@Trobat please see this comment for how to reference a file:

https://github.com/open-wa/wa-automate-nodejs/issues/876#issuecomment-702239822

The reason for that error is that the program cannot find the file.

You can send audio using: https://open-wa.github.io/wa-automate-nodejs/classes/client.html#sendptt

but I'm pretty sure you can't send mp3s using that
